/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.BatchVerificationRequestOnlyIfFree

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonValue

/**
 * 
 *
 * @param emails 
 * @param cacheMaxAge 
 * @param onlyIfFree 
 */


data class BatchVerificationRequest (

    @param:JsonProperty(value = "emails", required = true)
    @get:JsonProperty("emails")
    val emails: kotlin.collections.List<kotlin.String>,

    @param:JsonProperty("cacheMaxAge")
    @get:JsonProperty("cacheMaxAge")
    val cacheMaxAge: BatchVerificationRequest.CacheMaxAge? = null,

    @param:JsonProperty("onlyIfFree")
    @get:JsonProperty("onlyIfFree")
    val onlyIfFree: BatchVerificationRequestOnlyIfFree? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("emails", if (cacheMaxAge != null) "cacheMaxAge" else null, if (onlyIfFree != null) "onlyIfFree" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("emails", "cacheMaxAge", "onlyIfFree")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("emails")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (cacheMaxAge == null) "cacheMaxAge" else null, if (onlyIfFree == null) "onlyIfFree" else null)


    /**
     * 
     *
     * Values: LIVE,_1D,_1W,_1M
     */
    enum class CacheMaxAge(@get:JsonValue val value: kotlin.String) {
        @JsonProperty(value = "live") LIVE("live"),
        @JsonProperty(value = "1d") _1D("1d"),
        @JsonProperty(value = "1w") _1W("1w"),
        @JsonProperty(value = "1m") _1M("1m");
    }

}

