/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonValue

/**
 * 
 *
 * @param capability 
 * @param connectionId 
 * @param fieldMapping 
 * @param formId 
 */


data class BindWebflowFormRequest (

    @param:JsonProperty(value = "capability", required = true)
    @get:JsonProperty("capability")
    val capability: BindWebflowFormRequest.Capability,

    @param:JsonProperty(value = "connectionId", required = true)
    @get:JsonProperty("connectionId")
    val connectionId: java.util.UUID,

    @param:JsonProperty(value = "fieldMapping", required = true)
    @get:JsonProperty("fieldMapping")
    val fieldMapping: kotlin.collections.Map<kotlin.String, kotlin.String>,

    @param:JsonProperty(value = "formId", required = true)
    @get:JsonProperty("formId")
    val formId: kotlin.String,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("capability", "connectionId", "fieldMapping", "formId"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("capability", "connectionId", "fieldMapping", "formId")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("capability", "connectionId", "fieldMapping", "formId")
    override fun reaconNullFields(): Set<String> = setOfNotNull()


    /**
     * 
     *
     * Values: EMAIL_PERIOD_FIND,EMAIL_PERIOD_VERIFY,DOMAIN_PERIOD_SEARCH
     */
    enum class Capability(@get:JsonValue val value: kotlin.String) {
        @JsonProperty(value = "email.find") EMAIL_PERIOD_FIND("email.find"),
        @JsonProperty(value = "email.verify") EMAIL_PERIOD_VERIFY("email.verify"),
        @JsonProperty(value = "domain.search") DOMAIN_PERIOD_SEARCH("domain.search");
    }

}

