/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param acceptAll 
 * @param disposable 
 * @param mxRecords 
 * @param smtpCheck 
 * @param webmail 
 */


data class CapabilityEmailVerifiedDetails (

    @param:JsonProperty(value = "acceptAll", required = true)
    @get:JsonProperty("acceptAll")
    val acceptAll: kotlin.Boolean,

    @param:JsonProperty(value = "disposable", required = true)
    @get:JsonProperty("disposable")
    val disposable: kotlin.Boolean,

    @param:JsonProperty(value = "mxRecords", required = true)
    @get:JsonProperty("mxRecords")
    val mxRecords: kotlin.Boolean,

    @param:JsonProperty(value = "smtpCheck", required = true)
    @get:JsonProperty("smtpCheck")
    val smtpCheck: kotlin.Boolean,

    @param:JsonProperty(value = "webmail", required = true)
    @get:JsonProperty("webmail")
    val webmail: kotlin.Boolean,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("acceptAll", "disposable", "mxRecords", "smtpCheck", "webmail"),
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    val additionalProperties: MutableMap<String, Any?> = mutableMapOf(),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("acceptAll", "disposable", "mxRecords", "smtpCheck", "webmail")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("acceptAll", "disposable", "mxRecords", "smtpCheck", "webmail")
    override fun reaconNullFields(): Set<String> = setOfNotNull()

    @com.fasterxml.jackson.annotation.JsonAnyGetter
    fun additionalProperties(): Map<String, Any?> = additionalProperties
    @com.fasterxml.jackson.annotation.JsonAnySetter
    fun putAdditionalProperty(key: String, value: Any?) {
        require(key !in reaconKnownFields) { "Declared property cannot be overridden as an additional property" }
        additionalProperties[key] = value
    }



}

