/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param employmentType 
 * @param id 
 * @param location 
 * @param postedAt 
 * @param seniorityLevel 
 * @param source 
 * @param title 
 * @param url 
 */


data class CompanyContextJob (

    @param:JsonProperty(value = "employmentType", required = true)
    @get:JsonProperty("employmentType")
    val employmentType: kotlin.String?,

    @param:JsonProperty(value = "id", required = true)
    @get:JsonProperty("id")
    val id: kotlin.String,

    @param:JsonProperty(value = "location", required = true)
    @get:JsonProperty("location")
    val location: kotlin.String?,

    @param:JsonProperty(value = "postedAt", required = true)
    @get:JsonProperty("postedAt")
    val postedAt: kotlin.String,

    @param:JsonProperty(value = "seniorityLevel", required = true)
    @get:JsonProperty("seniorityLevel")
    val seniorityLevel: kotlin.String?,

    @param:JsonProperty(value = "source", required = true)
    @get:JsonProperty("source")
    val source: kotlin.String,

    @param:JsonProperty(value = "title", required = true)
    @get:JsonProperty("title")
    val title: kotlin.String,

    @param:JsonProperty(value = "url", required = true)
    @get:JsonProperty("url")
    val url: kotlin.String?,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("employmentType", "id", "location", "postedAt", "seniorityLevel", "source", "title", "url"),
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    val additionalProperties: MutableMap<String, Any?> = mutableMapOf(),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("employmentType", "id", "location", "postedAt", "seniorityLevel", "source", "title", "url")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("employmentType", "id", "location", "postedAt", "seniorityLevel", "source", "title", "url")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (employmentType == null) "employmentType" else null, if (location == null) "location" else null, if (seniorityLevel == null) "seniorityLevel" else null, if (url == null) "url" else null)

    @com.fasterxml.jackson.annotation.JsonAnyGetter
    fun additionalProperties(): Map<String, Any?> = additionalProperties
    @com.fasterxml.jackson.annotation.JsonAnySetter
    fun putAdditionalProperty(key: String, value: Any?) {
        require(key !in reaconKnownFields) { "Declared property cannot be overridden as an additional property" }
        additionalProperties[key] = value
    }



}

