/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.CompanyListResultsInnerAddressesInner

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param createdAt 
 * @param domains 
 * @param id 
 * @param updatedAt 
 * @param addresses 
 * @param foundedOn 
 * @param industry 
 * @param linkedin 
 * @param location 
 * @param name 
 * @param numberOfEmployees 
 * @param stock 
 * @param twitter 
 * @param type 
 * @param website 
 */


data class CompanyListResultsInner (

    @param:JsonProperty(value = "created_at", required = true)
    @get:JsonProperty("created_at")
    val createdAt: kotlin.String,

    @param:JsonProperty(value = "domains", required = true)
    @get:JsonProperty("domains")
    val domains: kotlin.collections.List<kotlin.String>,

    @param:JsonProperty(value = "id", required = true)
    @get:JsonProperty("id")
    val id: kotlin.String,

    @param:JsonProperty(value = "updated_at", required = true)
    @get:JsonProperty("updated_at")
    val updatedAt: kotlin.String,

    @param:JsonProperty("addresses")
    @get:JsonProperty("addresses")
    val addresses: kotlin.collections.List<CompanyListResultsInnerAddressesInner>? = null,

    @param:JsonProperty("founded_on")
    @get:JsonProperty("founded_on")
    val foundedOn: kotlin.String? = null,

    @param:JsonProperty("industry")
    @get:JsonProperty("industry")
    val industry: kotlin.String? = null,

    @param:JsonProperty("linkedin")
    @get:JsonProperty("linkedin")
    val linkedin: kotlin.String? = null,

    @param:JsonProperty("location")
    @get:JsonProperty("location")
    val location: kotlin.String? = null,

    @param:JsonProperty("name")
    @get:JsonProperty("name")
    val name: kotlin.String? = null,

    @param:JsonProperty("number_of_employees")
    @get:JsonProperty("number_of_employees")
    val numberOfEmployees: kotlin.Int? = null,

    @param:JsonProperty("stock")
    @get:JsonProperty("stock")
    val stock: kotlin.String? = null,

    @param:JsonProperty("twitter")
    @get:JsonProperty("twitter")
    val twitter: kotlin.String? = null,

    @param:JsonProperty("type")
    @get:JsonProperty("type")
    val type: kotlin.String? = null,

    @param:JsonProperty("website")
    @get:JsonProperty("website")
    val website: kotlin.String? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("created_at", "domains", "id", "updated_at", if (addresses != null) "addresses" else null, if (foundedOn != null) "founded_on" else null, if (industry != null) "industry" else null, if (linkedin != null) "linkedin" else null, if (location != null) "location" else null, if (name != null) "name" else null, if (numberOfEmployees != null) "number_of_employees" else null, if (stock != null) "stock" else null, if (twitter != null) "twitter" else null, if (type != null) "type" else null, if (website != null) "website" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("created_at", "domains", "id", "updated_at", "addresses", "founded_on", "industry", "linkedin", "location", "name", "number_of_employees", "stock", "twitter", "type", "website")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("created_at", "domains", "id", "updated_at")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (addresses == null) "addresses" else null, if (foundedOn == null) "founded_on" else null, if (industry == null) "industry" else null, if (linkedin == null) "linkedin" else null, if (location == null) "location" else null, if (name == null) "name" else null, if (numberOfEmployees == null) "number_of_employees" else null, if (stock == null) "stock" else null, if (twitter == null) "twitter" else null, if (type == null) "type" else null, if (website == null) "website" else null)



}

