/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonValue

/**
 * 
 *
 * @param config 
 * @param credential 
 * @param label 
 * @param provider 
 * @param mode 
 */


data class ConfigureWarehouseRequest (

    @param:JsonProperty(value = "config", required = true)
    @get:JsonProperty("config")
    val config: kotlin.collections.Map<kotlin.String, kotlin.String>,

    @param:JsonProperty(value = "credential", required = true)
    @get:JsonProperty("credential")
    val credential: kotlin.collections.Map<kotlin.String, kotlin.String>,

    @param:JsonProperty(value = "label", required = true)
    @get:JsonProperty("label")
    val label: kotlin.String,

    @param:JsonProperty(value = "provider", required = true)
    @get:JsonProperty("provider")
    val provider: ConfigureWarehouseRequest.Provider,

    @param:JsonProperty("mode")
    @get:JsonProperty("mode")
    val mode: ConfigureWarehouseRequest.Mode? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("config", "credential", "label", "provider", if (mode != null) "mode" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("config", "credential", "label", "provider", "mode")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("config", "credential", "label", "provider")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (mode == null) "mode" else null)


    /**
     * 
     *
     * Values: POSTGRESQL,BIGQUERY,SNOWFLAKE,REDSHIFT
     */
    enum class Provider(@get:JsonValue val value: kotlin.String) {
        @JsonProperty(value = "postgresql") POSTGRESQL("postgresql"),
        @JsonProperty(value = "bigquery") BIGQUERY("bigquery"),
        @JsonProperty(value = "snowflake") SNOWFLAKE("snowflake"),
        @JsonProperty(value = "redshift") REDSHIFT("redshift");
    }
    /**
     * 
     *
     * Values: LIVE,EMULATED
     */
    enum class Mode(@get:JsonValue val value: kotlin.String) {
        @JsonProperty(value = "live") LIVE("live"),
        @JsonProperty(value = "emulated") EMULATED("emulated");
    }

}

