/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param email 
 * @param lastName 
 * @param localId 
 * @param company 
 * @param firstName 
 * @param jobTitle 
 * @param phone 
 */


data class ConfigureCodaRequestMapping (

    @param:JsonProperty(value = "email", required = true)
    @get:JsonProperty("email")
    val email: kotlin.String,

    @param:JsonProperty(value = "lastName", required = true)
    @get:JsonProperty("lastName")
    val lastName: kotlin.String,

    @param:JsonProperty(value = "localId", required = true)
    @get:JsonProperty("localId")
    val localId: kotlin.String,

    @param:JsonProperty("company")
    @get:JsonProperty("company")
    val company: kotlin.String? = null,

    @param:JsonProperty("firstName")
    @get:JsonProperty("firstName")
    val firstName: kotlin.String? = null,

    @param:JsonProperty("jobTitle")
    @get:JsonProperty("jobTitle")
    val jobTitle: kotlin.String? = null,

    @param:JsonProperty("phone")
    @get:JsonProperty("phone")
    val phone: kotlin.String? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("email", "lastName", "localId", if (company != null) "company" else null, if (firstName != null) "firstName" else null, if (jobTitle != null) "jobTitle" else null, if (phone != null) "phone" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("email", "lastName", "localId", "company", "firstName", "jobTitle", "phone")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("email", "lastName", "localId")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (company == null) "company" else null, if (firstName == null) "firstName" else null, if (jobTitle == null) "jobTitle" else null, if (phone == null) "phone" else null)



}

