/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonValue

/**
 * 
 *
 * @param label 
 * @param webhookUrl 
 * @param mode 
 */


data class ConfigureTeamsWorkflowRequest (

    @param:JsonProperty(value = "label", required = true)
    @get:JsonProperty("label")
    val label: kotlin.String,

    @param:JsonProperty(value = "webhookUrl", required = true)
    @get:JsonProperty("webhookUrl")
    val webhookUrl: kotlin.String,

    @param:JsonProperty("mode")
    @get:JsonProperty("mode")
    val mode: ConfigureTeamsWorkflowRequest.Mode? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("label", "webhookUrl", if (mode != null) "mode" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("label", "webhookUrl", "mode")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("label", "webhookUrl")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (mode == null) "mode" else null)


    /**
     * 
     *
     * Values: LIVE,EMULATED
     */
    enum class Mode(@get:JsonValue val value: kotlin.String) {
        @JsonProperty(value = "live") LIVE("live"),
        @JsonProperty(value = "emulated") EMULATED("emulated");
    }

}

