/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param dataType 
 * @param externalId 
 * @param key 
 * @param label 
 * @param required 
 * @param unique 
 */


data class CrmRemoteField (

    @param:JsonProperty(value = "dataType", required = true)
    @get:JsonProperty("dataType")
    val dataType: kotlin.String,

    @param:JsonProperty(value = "externalId", required = true)
    @get:JsonProperty("externalId")
    val externalId: kotlin.Boolean,

    @param:JsonProperty(value = "key", required = true)
    @get:JsonProperty("key")
    val key: kotlin.String,

    @param:JsonProperty(value = "label", required = true)
    @get:JsonProperty("label")
    val label: kotlin.String,

    @param:JsonProperty(value = "required", required = true)
    @get:JsonProperty("required")
    val required: kotlin.Boolean,

    @param:JsonProperty(value = "unique", required = true)
    @get:JsonProperty("unique")
    val unique: kotlin.Boolean,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("dataType", "externalId", "key", "label", "required", "unique"),
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    val additionalProperties: MutableMap<String, Any?> = mutableMapOf(),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("dataType", "externalId", "key", "label", "required", "unique")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("dataType", "externalId", "key", "label", "required", "unique")
    override fun reaconNullFields(): Set<String> = setOfNotNull()

    @com.fasterxml.jackson.annotation.JsonAnyGetter
    fun additionalProperties(): Map<String, Any?> = additionalProperties
    @com.fasterxml.jackson.annotation.JsonAnySetter
    fun putAdditionalProperty(key: String, value: Any?) {
        require(key !in reaconKnownFields) { "Declared property cannot be overridden as an additional property" }
        additionalProperties[key] = value
    }



}

