/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.CrmSyncConfigurationHubspot
import io.reacon.sdk.kotlin.models.CrmSyncConfigurationPolicy

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param hubspot 
 * @param policy 
 */


data class CrmSyncConfiguration (

    @param:JsonProperty(value = "hubspot", required = true)
    @get:JsonProperty("hubspot")
    val hubspot: CrmSyncConfigurationHubspot?,

    @param:JsonProperty(value = "policy", required = true)
    @get:JsonProperty("policy")
    val policy: CrmSyncConfigurationPolicy,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("hubspot", "policy"),
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    val additionalProperties: MutableMap<String, Any?> = mutableMapOf(),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("hubspot", "policy")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("hubspot", "policy")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (hubspot == null) "hubspot" else null)

    @com.fasterxml.jackson.annotation.JsonAnyGetter
    fun additionalProperties(): Map<String, Any?> = additionalProperties
    @com.fasterxml.jackson.annotation.JsonAnySetter
    fun putAdditionalProperty(key: String, value: Any?) {
        require(key !in reaconKnownFields) { "Declared property cannot be overridden as an additional property" }
        additionalProperties[key] = value
    }



}

