/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.CompanyContextAddress
import io.reacon.sdk.kotlin.models.CompanyContextJob
import io.reacon.sdk.kotlin.models.CompanyContextSource

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param address 
 * @param companyType 
 * @param description 
 * @param domain 
 * @param employeeCount 
 * @param employeeRange 
 * @param followerCount 
 * @param foundedOn 
 * @param headquarters 
 * @param id 
 * @param industry 
 * @param jobs 
 * @param linkedin 
 * @param name 
 * @param sources 
 * @param specialties 
 * @param stockSymbol 
 * @param tagline 
 * @param website 
 */


data class DomainCompanyContextCompany (

    @param:JsonProperty(value = "address", required = true)
    @get:JsonProperty("address")
    val address: CompanyContextAddress?,

    @param:JsonProperty(value = "companyType", required = true)
    @get:JsonProperty("companyType")
    val companyType: kotlin.String?,

    @param:JsonProperty(value = "description", required = true)
    @get:JsonProperty("description")
    val description: kotlin.String?,

    @param:JsonProperty(value = "domain", required = true)
    @get:JsonProperty("domain")
    val domain: kotlin.String,

    @param:JsonProperty(value = "employeeCount", required = true)
    @get:JsonProperty("employeeCount")
    val employeeCount: kotlin.Int?,

    @param:JsonProperty(value = "employeeRange", required = true)
    @get:JsonProperty("employeeRange")
    val employeeRange: kotlin.String?,

    @param:JsonProperty(value = "followerCount", required = true)
    @get:JsonProperty("followerCount")
    val followerCount: kotlin.Int?,

    @param:JsonProperty(value = "foundedOn", required = true)
    @get:JsonProperty("foundedOn")
    val foundedOn: kotlin.String?,

    @param:JsonProperty(value = "headquarters", required = true)
    @get:JsonProperty("headquarters")
    val headquarters: kotlin.String?,

    @param:JsonProperty(value = "id", required = true)
    @get:JsonProperty("id")
    val id: kotlin.String,

    @param:JsonProperty(value = "industry", required = true)
    @get:JsonProperty("industry")
    val industry: kotlin.String?,

    @param:JsonProperty(value = "jobs", required = true)
    @get:JsonProperty("jobs")
    val jobs: kotlin.collections.List<CompanyContextJob>,

    @param:JsonProperty(value = "linkedin", required = true)
    @get:JsonProperty("linkedin")
    val linkedin: kotlin.String?,

    @param:JsonProperty(value = "name", required = true)
    @get:JsonProperty("name")
    val name: kotlin.String,

    @param:JsonProperty(value = "sources", required = true)
    @get:JsonProperty("sources")
    val sources: kotlin.collections.List<CompanyContextSource>,

    @param:JsonProperty(value = "specialties", required = true)
    @get:JsonProperty("specialties")
    val specialties: kotlin.collections.List<kotlin.String>,

    @param:JsonProperty(value = "stockSymbol", required = true)
    @get:JsonProperty("stockSymbol")
    val stockSymbol: kotlin.String?,

    @param:JsonProperty(value = "tagline", required = true)
    @get:JsonProperty("tagline")
    val tagline: kotlin.String?,

    @param:JsonProperty(value = "website", required = true)
    @get:JsonProperty("website")
    val website: kotlin.String?,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("address", "companyType", "description", "domain", "employeeCount", "employeeRange", "followerCount", "foundedOn", "headquarters", "id", "industry", "jobs", "linkedin", "name", "sources", "specialties", "stockSymbol", "tagline", "website"),
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    val additionalProperties: MutableMap<String, Any?> = mutableMapOf(),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("address", "companyType", "description", "domain", "employeeCount", "employeeRange", "followerCount", "foundedOn", "headquarters", "id", "industry", "jobs", "linkedin", "name", "sources", "specialties", "stockSymbol", "tagline", "website")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("address", "companyType", "description", "domain", "employeeCount", "employeeRange", "followerCount", "foundedOn", "headquarters", "id", "industry", "jobs", "linkedin", "name", "sources", "specialties", "stockSymbol", "tagline", "website")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (address == null) "address" else null, if (companyType == null) "companyType" else null, if (description == null) "description" else null, if (employeeCount == null) "employeeCount" else null, if (employeeRange == null) "employeeRange" else null, if (followerCount == null) "followerCount" else null, if (foundedOn == null) "foundedOn" else null, if (headquarters == null) "headquarters" else null, if (industry == null) "industry" else null, if (linkedin == null) "linkedin" else null, if (stockSymbol == null) "stockSymbol" else null, if (tagline == null) "tagline" else null, if (website == null) "website" else null)

    @com.fasterxml.jackson.annotation.JsonAnyGetter
    fun additionalProperties(): Map<String, Any?> = additionalProperties
    @com.fasterxml.jackson.annotation.JsonAnySetter
    fun putAdditionalProperty(key: String, value: Any?) {
        require(key !in reaconKnownFields) { "Declared property cannot be overridden as an additional property" }
        additionalProperties[key] = value
    }



}

