/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param driveItemId 
 * @param headers 
 * @param name 
 * @param provider 
 * @param usedRangeAddress 
 * @param worksheet 
 * @param worksheets 
 */


data class ExcelWorkbookInspectionResponseInspection (

    @param:JsonProperty(value = "driveItemId", required = true)
    @get:JsonProperty("driveItemId")
    val driveItemId: kotlin.String,

    @param:JsonProperty(value = "headers", required = true)
    @get:JsonProperty("headers")
    val headers: kotlin.collections.List<kotlin.String>,

    @param:JsonProperty(value = "name", required = true)
    @get:JsonProperty("name")
    val name: kotlin.String,

    @param:JsonProperty(value = "provider", required = true)
    @get:JsonProperty("provider")
    val provider: kotlin.String,

    @param:JsonProperty(value = "usedRangeAddress", required = true)
    @get:JsonProperty("usedRangeAddress")
    val usedRangeAddress: kotlin.String,

    @param:JsonProperty(value = "worksheet", required = true)
    @get:JsonProperty("worksheet")
    val worksheet: kotlin.String,

    @param:JsonProperty(value = "worksheets", required = true)
    @get:JsonProperty("worksheets")
    val worksheets: kotlin.collections.List<kotlin.String>,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("driveItemId", "headers", "name", "provider", "usedRangeAddress", "worksheet", "worksheets"),
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    val additionalProperties: MutableMap<String, Any?> = mutableMapOf(),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("driveItemId", "headers", "name", "provider", "usedRangeAddress", "worksheet", "worksheets")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("driveItemId", "headers", "name", "provider", "usedRangeAddress", "worksheet", "worksheets")
    override fun reaconNullFields(): Set<String> = setOfNotNull()

    @com.fasterxml.jackson.annotation.JsonAnyGetter
    fun additionalProperties(): Map<String, Any?> = additionalProperties
    @com.fasterxml.jackson.annotation.JsonAnySetter
    fun putAdditionalProperty(key: String, value: Any?) {
        require(key !in reaconKnownFields) { "Declared property cannot be overridden as an additional property" }
        additionalProperties[key] = value
    }



}

