/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param email 
 * @param kind Known values: platform_progress. Clients preserve future values.
 * @param progress 
 */


data class InsightPlatformProgressEvent (

    @param:JsonProperty(value = "email", required = true)
    @get:JsonProperty("email")
    val email: kotlin.String,

    /* Known values: platform_progress. Clients preserve future values. */
    @param:JsonProperty(value = "kind", required = true)
    @get:JsonProperty("kind")
    val kind: kotlin.String,

    @param:JsonProperty(value = "progress", required = true)
    @get:JsonProperty("progress")
    val progress: java.math.BigDecimal,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("email", "kind", "progress"),
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    val additionalProperties: MutableMap<String, Any?> = mutableMapOf(),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("email", "kind", "progress")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("email", "kind", "progress")
    override fun reaconNullFields(): Set<String> = setOfNotNull()

    @com.fasterxml.jackson.annotation.JsonAnyGetter
    fun additionalProperties(): Map<String, Any?> = additionalProperties
    @com.fasterxml.jackson.annotation.JsonAnySetter
    fun putAdditionalProperty(key: String, value: Any?) {
        require(key !in reaconKnownFields) { "Declared property cannot be overridden as an additional property" }
        additionalProperties[key] = value
    }



}

