/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.InsightAddress

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param address 
 * @param type Known values: physical, mailing, billing, shipping, registered, other. Clients preserve future values.
 * @param label 
 */


data class InsightAddressEntry (

    @param:JsonProperty(value = "address", required = true)
    @get:JsonProperty("address")
    val address: InsightAddress,

    /* Known values: physical, mailing, billing, shipping, registered, other. Clients preserve future values. */
    @param:JsonProperty(value = "type", required = true)
    @get:JsonProperty("type")
    val type: kotlin.String,

    @param:JsonProperty("label")
    @get:JsonProperty("label")
    val label: kotlin.String? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("address", "type", if (label != null) "label" else null),
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    val additionalProperties: MutableMap<String, Any?> = mutableMapOf(),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("address", "type", "label")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("address", "type")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (label == null) "label" else null)

    @com.fasterxml.jackson.annotation.JsonAnyGetter
    fun additionalProperties(): Map<String, Any?> = additionalProperties
    @com.fasterxml.jackson.annotation.JsonAnySetter
    fun putAdditionalProperty(key: String, value: Any?) {
        require(key !in reaconKnownFields) { "Declared property cannot be overridden as an additional property" }
        additionalProperties[key] = value
    }



}

