/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.InsightGeo

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param alternates 
 * @param city 
 * @param country 
 * @param countryCode 
 * @param formatted 
 * @param geo 
 * @param postalCode 
 * @param region 
 * @param street1 
 * @param street2 
 */


data class InsightAddress (

    @param:JsonProperty("alternates")
    @get:JsonProperty("alternates")
    val alternates: kotlin.collections.List<kotlin.String>? = null,

    @param:JsonProperty("city")
    @get:JsonProperty("city")
    val city: kotlin.String? = null,

    @param:JsonProperty("country")
    @get:JsonProperty("country")
    val country: kotlin.String? = null,

    @param:JsonProperty("countryCode")
    @get:JsonProperty("countryCode")
    val countryCode: kotlin.String? = null,

    @param:JsonProperty("formatted")
    @get:JsonProperty("formatted")
    val formatted: kotlin.String? = null,

    @param:JsonProperty("geo")
    @get:JsonProperty("geo")
    val geo: InsightGeo? = null,

    @param:JsonProperty("postalCode")
    @get:JsonProperty("postalCode")
    val postalCode: kotlin.String? = null,

    @param:JsonProperty("region")
    @get:JsonProperty("region")
    val region: kotlin.String? = null,

    @param:JsonProperty("street1")
    @get:JsonProperty("street1")
    val street1: kotlin.String? = null,

    @param:JsonProperty("street2")
    @get:JsonProperty("street2")
    val street2: kotlin.String? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull(if (alternates != null) "alternates" else null, if (city != null) "city" else null, if (country != null) "country" else null, if (countryCode != null) "countryCode" else null, if (formatted != null) "formatted" else null, if (geo != null) "geo" else null, if (postalCode != null) "postalCode" else null, if (region != null) "region" else null, if (street1 != null) "street1" else null, if (street2 != null) "street2" else null),
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    val additionalProperties: MutableMap<String, Any?> = mutableMapOf(),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("alternates", "city", "country", "countryCode", "formatted", "geo", "postalCode", "region", "street1", "street2")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf()
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (alternates == null) "alternates" else null, if (city == null) "city" else null, if (country == null) "country" else null, if (countryCode == null) "countryCode" else null, if (formatted == null) "formatted" else null, if (geo == null) "geo" else null, if (postalCode == null) "postalCode" else null, if (region == null) "region" else null, if (street1 == null) "street1" else null, if (street2 == null) "street2" else null)

    @com.fasterxml.jackson.annotation.JsonAnyGetter
    fun additionalProperties(): Map<String, Any?> = additionalProperties
    @com.fasterxml.jackson.annotation.JsonAnySetter
    fun putAdditionalProperty(key: String, value: Any?) {
        require(key !in reaconKnownFields) { "Declared property cannot be overridden as an additional property" }
        additionalProperties[key] = value
    }



}

