/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param handle 
 * @param platform 
 * @param url 
 */


data class InsightSocialProfile (

    @param:JsonProperty("handle")
    @get:JsonProperty("handle")
    val handle: kotlin.String? = null,

    @param:JsonProperty("platform")
    @get:JsonProperty("platform")
    val platform: kotlin.String? = null,

    @param:JsonProperty("url")
    @get:JsonProperty("url")
    val url: kotlin.String? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull(if (handle != null) "handle" else null, if (platform != null) "platform" else null, if (url != null) "url" else null),
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    val additionalProperties: MutableMap<String, Any?> = mutableMapOf(),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("handle", "platform", "url")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf()
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (handle == null) "handle" else null, if (platform == null) "platform" else null, if (url == null) "url" else null)

    @com.fasterxml.jackson.annotation.JsonAnyGetter
    fun additionalProperties(): Map<String, Any?> = additionalProperties
    @com.fasterxml.jackson.annotation.JsonAnySetter
    fun putAdditionalProperty(key: String, value: Any?) {
        require(key !in reaconKnownFields) { "Declared property cannot be overridden as an additional property" }
        additionalProperties[key] = value
    }



}

