/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param scheme 
 * @param `value` 
 * @param authority 
 * @param countryCode 
 * @param flags 
 * @param notes 
 * @param regionCode 
 * @param sourceLabel 
 * @param status 
 * @param validFrom 
 * @param validTo 
 */


data class InsightIdentifier (

    @param:JsonProperty(value = "scheme", required = true)
    @get:JsonProperty("scheme")
    val scheme: kotlin.String,

    @param:JsonProperty("value")
    @get:JsonProperty("value")
    val `value`: kotlin.String,

    @param:JsonProperty("authority")
    @get:JsonProperty("authority")
    val authority: kotlin.String? = null,

    @param:JsonProperty("countryCode")
    @get:JsonProperty("countryCode")
    val countryCode: kotlin.String? = null,

    @param:JsonProperty("flags")
    @get:JsonProperty("flags")
    val flags: kotlin.collections.List<kotlin.String>? = null,

    @param:JsonProperty("notes")
    @get:JsonProperty("notes")
    val notes: kotlin.String? = null,

    @param:JsonProperty("regionCode")
    @get:JsonProperty("regionCode")
    val regionCode: kotlin.String? = null,

    @param:JsonProperty("sourceLabel")
    @get:JsonProperty("sourceLabel")
    val sourceLabel: kotlin.String? = null,

    @param:JsonProperty("status")
    @get:JsonProperty("status")
    val status: kotlin.String? = null,

    @param:JsonProperty("validFrom")
    @get:JsonProperty("validFrom")
    val validFrom: kotlin.String? = null,

    @param:JsonProperty("validTo")
    @get:JsonProperty("validTo")
    val validTo: kotlin.String? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("scheme", if (authority != null) "authority" else null, if (countryCode != null) "countryCode" else null, if (flags != null) "flags" else null, if (notes != null) "notes" else null, if (regionCode != null) "regionCode" else null, if (sourceLabel != null) "sourceLabel" else null, if (status != null) "status" else null, if (validFrom != null) "validFrom" else null, if (validTo != null) "validTo" else null),
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    val additionalProperties: MutableMap<String, Any?> = mutableMapOf(),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("scheme", "authority", "countryCode", "flags", "notes", "regionCode", "sourceLabel", "status", "validFrom", "validTo")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("scheme")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (authority == null) "authority" else null, if (countryCode == null) "countryCode" else null, if (flags == null) "flags" else null, if (notes == null) "notes" else null, if (regionCode == null) "regionCode" else null, if (sourceLabel == null) "sourceLabel" else null, if (status == null) "status" else null, if (validFrom == null) "validFrom" else null, if (validTo == null) "validTo" else null)

    @com.fasterxml.jackson.annotation.JsonAnyGetter
    fun additionalProperties(): Map<String, Any?> = additionalProperties
    @com.fasterxml.jackson.annotation.JsonAnySetter
    fun putAdditionalProperty(key: String, value: Any?) {
        require(key !in reaconKnownFields) { "Declared property cannot be overridden as an additional property" }
        additionalProperties[key] = value
    }



}

