/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param connectionId 
 * @param driveItemId 
 * @param shareUrl 
 * @param worksheet 
 */


data class InspectExcelWorkbookRequest (

    @param:JsonProperty(value = "connectionId", required = true)
    @get:JsonProperty("connectionId")
    val connectionId: kotlin.String,

    @param:JsonProperty("driveItemId")
    @get:JsonProperty("driveItemId")
    val driveItemId: kotlin.String? = null,

    @param:JsonProperty("shareUrl")
    @get:JsonProperty("shareUrl")
    val shareUrl: kotlin.String? = null,

    @param:JsonProperty("worksheet")
    @get:JsonProperty("worksheet")
    val worksheet: kotlin.String? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("connectionId", if (driveItemId != null) "driveItemId" else null, if (shareUrl != null) "shareUrl" else null, if (worksheet != null) "worksheet" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("connectionId", "driveItemId", "shareUrl", "worksheet")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("connectionId")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (driveItemId == null) "driveItemId" else null, if (shareUrl == null) "shareUrl" else null, if (worksheet == null) "worksheet" else null)



}

