/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param connectionId 
 * @param spreadsheetId 
 * @param headerRow 
 * @param sheetName 
 */


data class InspectGoogleSheetRequest (

    @param:JsonProperty(value = "connectionId", required = true)
    @get:JsonProperty("connectionId")
    val connectionId: kotlin.String,

    @param:JsonProperty(value = "spreadsheetId", required = true)
    @get:JsonProperty("spreadsheetId")
    val spreadsheetId: kotlin.String,

    @param:JsonProperty("headerRow")
    @get:JsonProperty("headerRow")
    val headerRow: kotlin.Int? = null,

    @param:JsonProperty("sheetName")
    @get:JsonProperty("sheetName")
    val sheetName: kotlin.String? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("connectionId", "spreadsheetId", if (headerRow != null) "headerRow" else null, if (sheetName != null) "sheetName" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("connectionId", "spreadsheetId", "headerRow", "sheetName")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("connectionId", "spreadsheetId")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (headerRow == null) "headerRow" else null, if (sheetName == null) "sheetName" else null)



}

