/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.CapabilityDomainSearch
import io.reacon.sdk.kotlin.models.CapabilityDomainSearchContactsInner
import io.reacon.sdk.kotlin.models.CapabilityEmailFound
import io.reacon.sdk.kotlin.models.CapabilityEmailVerified
import io.reacon.sdk.kotlin.models.CapabilityEmailVerifiedDetails

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Null in preview mode; otherwise the result for the selected capability.
 *
 * @param confidence 
 * @param email 
 * @param freshness 
 * @param status 
 * @param checkedAt 
 * @param details 
 * @param score 
 * @param sources 
 * @param contacts 
 * @param domain 
 * @param organization 
 */


data class IntegrationCapabilityResponseOutput (

    @param:JsonProperty(value = "confidence", required = true)
    @get:JsonProperty("confidence")
    val confidence: java.math.BigDecimal,

    @param:JsonProperty(value = "email", required = true)
    @get:JsonProperty("email")
    val email: kotlin.String,

    @param:JsonProperty(value = "freshness", required = true)
    @get:JsonProperty("freshness")
    val freshness: kotlin.String,

    @param:JsonProperty(value = "status", required = true)
    @get:JsonProperty("status")
    val status: kotlin.String,

    @param:JsonProperty(value = "checkedAt", required = true)
    @get:JsonProperty("checkedAt")
    val checkedAt: kotlin.String,

    @param:JsonProperty(value = "details", required = true)
    @get:JsonProperty("details")
    val details: CapabilityEmailVerifiedDetails,

    @param:JsonProperty(value = "score", required = true)
    @get:JsonProperty("score")
    val score: java.math.BigDecimal,

    @param:JsonProperty(value = "sources", required = true)
    @get:JsonProperty("sources")
    val sources: kotlin.Int,

    @param:JsonProperty(value = "contacts", required = true)
    @get:JsonProperty("contacts")
    val contacts: kotlin.collections.List<CapabilityDomainSearchContactsInner>,

    @param:JsonProperty(value = "domain", required = true)
    @get:JsonProperty("domain")
    val domain: kotlin.String,

    @param:JsonProperty("organization")
    @get:JsonProperty("organization")
    val organization: kotlin.String? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("confidence", "email", "freshness", "status", "checkedAt", "details", "score", "sources", "contacts", "domain", if (organization != null) "organization" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("confidence", "email", "freshness", "status", "checkedAt", "details", "score", "sources", "contacts", "domain", "organization")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("confidence", "email", "freshness", "status", "checkedAt", "details", "score", "sources", "contacts", "domain")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (organization == null) "organization" else null)



}

