/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param deterministicAcceptance Known values: passed. Clients preserve future values.
 * @param distribution Known values: private_ready, external_gate, not_applicable. Clients preserve future values.
 * @param implementation Known values: complete, partial, retired. Clients preserve future values.
 * @param liveAcceptance Known values: passed, external_blocked, not_applicable. Clients preserve future values.
 * @param productSurface Known values: complete, partial, external. Clients preserve future values.
 */


data class IntegrationProviderListProvidersInnerReadiness (

    /* Known values: passed. Clients preserve future values. */
    @param:JsonProperty(value = "deterministicAcceptance", required = true)
    @get:JsonProperty("deterministicAcceptance")
    val deterministicAcceptance: kotlin.String,

    /* Known values: private_ready, external_gate, not_applicable. Clients preserve future values. */
    @param:JsonProperty(value = "distribution", required = true)
    @get:JsonProperty("distribution")
    val distribution: kotlin.String,

    /* Known values: complete, partial, retired. Clients preserve future values. */
    @param:JsonProperty(value = "implementation", required = true)
    @get:JsonProperty("implementation")
    val implementation: kotlin.String,

    /* Known values: passed, external_blocked, not_applicable. Clients preserve future values. */
    @param:JsonProperty(value = "liveAcceptance", required = true)
    @get:JsonProperty("liveAcceptance")
    val liveAcceptance: kotlin.String,

    /* Known values: complete, partial, external. Clients preserve future values. */
    @param:JsonProperty(value = "productSurface", required = true)
    @get:JsonProperty("productSurface")
    val productSurface: kotlin.String,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("deterministicAcceptance", "distribution", "implementation", "liveAcceptance", "productSurface"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("deterministicAcceptance", "distribution", "implementation", "liveAcceptance", "productSurface")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("deterministicAcceptance", "distribution", "implementation", "liveAcceptance", "productSurface")
    override fun reaconNullFields(): Set<String> = setOfNotNull()



}

