/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.MailMailboxConnectionRecord
import io.reacon.sdk.kotlin.models.MailMailboxRecord

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param connection 
 * @param mailbox 
 */


data class MailPostMailboxesManualResponse200 (

    @param:JsonProperty(value = "connection", required = true)
    @get:JsonProperty("connection")
    val connection: MailMailboxConnectionRecord,

    @param:JsonProperty(value = "mailbox", required = true)
    @get:JsonProperty("mailbox")
    val mailbox: MailMailboxRecord,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("connection", "mailbox"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("connection", "mailbox")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("connection", "mailbox")
    override fun reaconNullFields(): Set<String> = setOfNotNull()



}

