/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.MailPostTemplatesRequestWhatsappApproval

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonValue

/**
 * 
 *
 * @param body 
 * @param channel 
 * @param name 
 * @param status 
 * @param id 
 * @param subject 
 * @param whatsappApproval 
 */


data class MailPostTemplatesRequest (

    @param:JsonProperty(value = "body", required = true)
    @get:JsonProperty("body")
    val body: kotlin.String,

    @param:JsonProperty(value = "channel", required = true)
    @get:JsonProperty("channel")
    val channel: MailPostTemplatesRequest.Channel,

    @param:JsonProperty(value = "name", required = true)
    @get:JsonProperty("name")
    val name: kotlin.String,

    @param:JsonProperty(value = "status", required = true)
    @get:JsonProperty("status")
    val status: MailPostTemplatesRequest.Status,

    @param:JsonProperty("id")
    @get:JsonProperty("id")
    val id: kotlin.String? = null,

    @param:JsonProperty("subject")
    @get:JsonProperty("subject")
    val subject: kotlin.String? = null,

    @param:JsonProperty("whatsappApproval")
    @get:JsonProperty("whatsappApproval")
    val whatsappApproval: MailPostTemplatesRequestWhatsappApproval? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("body", "channel", "name", "status", if (id != null) "id" else null, if (subject != null) "subject" else null, if (whatsappApproval != null) "whatsappApproval" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("body", "channel", "name", "status", "id", "subject", "whatsappApproval")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("body", "channel", "name", "status")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (id == null) "id" else null, if (subject == null) "subject" else null, if (whatsappApproval == null) "whatsappApproval" else null)


    /**
     * 
     *
     * Values: EMAIL,SMS,WHATSAPP
     */
    enum class Channel(@get:JsonValue val value: kotlin.String) {
        @JsonProperty(value = "email") EMAIL("email"),
        @JsonProperty(value = "sms") SMS("sms"),
        @JsonProperty(value = "whatsapp") WHATSAPP("whatsapp");
    }
    /**
     * 
     *
     * Values: DRAFT,PUBLISHED,ARCHIVED
     */
    enum class Status(@get:JsonValue val value: kotlin.String) {
        @JsonProperty(value = "draft") DRAFT("draft"),
        @JsonProperty(value = "published") PUBLISHED("published"),
        @JsonProperty(value = "archived") ARCHIVED("archived");
    }

}

