/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param createdAt 
 * @param enabled 
 * @param mailboxId 
 * @param poolId 
 * @param priority 
 * @param tenantId 
 * @param updatedAt 
 * @param weight 
 */


data class MailMailboxPoolMember (

    @param:JsonProperty(value = "createdAt", required = true)
    @get:JsonProperty("createdAt")
    val createdAt: kotlin.String,

    @param:JsonProperty(value = "enabled", required = true)
    @get:JsonProperty("enabled")
    val enabled: kotlin.Boolean,

    @param:JsonProperty(value = "mailboxId", required = true)
    @get:JsonProperty("mailboxId")
    val mailboxId: kotlin.String,

    @param:JsonProperty(value = "poolId", required = true)
    @get:JsonProperty("poolId")
    val poolId: kotlin.String,

    @param:JsonProperty(value = "priority", required = true)
    @get:JsonProperty("priority")
    val priority: java.math.BigDecimal,

    @param:JsonProperty(value = "tenantId", required = true)
    @get:JsonProperty("tenantId")
    val tenantId: kotlin.String,

    @param:JsonProperty(value = "updatedAt", required = true)
    @get:JsonProperty("updatedAt")
    val updatedAt: kotlin.String,

    @param:JsonProperty(value = "weight", required = true)
    @get:JsonProperty("weight")
    val weight: java.math.BigDecimal,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("createdAt", "enabled", "mailboxId", "poolId", "priority", "tenantId", "updatedAt", "weight"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("createdAt", "enabled", "mailboxId", "poolId", "priority", "tenantId", "updatedAt", "weight")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("createdAt", "enabled", "mailboxId", "poolId", "priority", "tenantId", "updatedAt", "weight")
    override fun reaconNullFields(): Set<String> = setOfNotNull()



}

