/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param delayMs 
 * @param subject 
 * @param text 
 * @param html 
 * @param id 
 * @param variants 
 */


data class MailPatchCampaignsByCampaignIdRequestStepsInner (

    @param:JsonProperty(value = "delayMs", required = true)
    @get:JsonProperty("delayMs")
    val delayMs: kotlin.Int,

    @param:JsonProperty(value = "subject", required = true)
    @get:JsonProperty("subject")
    val subject: kotlin.String,

    @param:JsonProperty(value = "text", required = true)
    @get:JsonProperty("text")
    val text: kotlin.String,

    @param:JsonProperty("html")
    @get:JsonProperty("html")
    val html: kotlin.String? = null,

    @param:JsonProperty("id")
    @get:JsonProperty("id")
    val id: kotlin.String? = null,

    @param:JsonProperty("variants")
    @get:JsonProperty("variants")
    val variants: kotlin.collections.List<MailPatchCampaignsByCampaignIdRequestStepsInnerVariantsInner>? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("delayMs", "subject", "text", if (html != null) "html" else null, if (id != null) "id" else null, if (variants != null) "variants" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("delayMs", "subject", "text", "html", "id", "variants")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("delayMs", "subject", "text")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (html == null) "html" else null, if (id == null) "id" else null, if (variants == null) "variants" else null)



}

