/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.MailCadenceExperimentContext

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param actorId 
 * @param attemptCount 
 * @param cadenceId 
 * @param cadenceVersion 
 * @param contactId 
 * @param createdAt 
 * @param currentNodeId 
 * @param dueAt 
 * @param id 
 * @param idempotencyKey 
 * @param mailboxId 
 * @param status 
 * @param tenantId 
 * @param updatedAt 
 * @param version 
 * @param audienceListId 
 * @param campaignId 
 * @param campaignName 
 * @param experimentContexts 
 * @param lastAcceptedMessageId 
 * @param lastError 
 * @param leaseExpiresAt 
 * @param leaseOwner 
 * @param outcome 
 * @param pendingMessageId 
 * @param pendingNextNodeId 
 * @param taskId 
 */


data class MailCadenceRunRecord (

    @param:JsonProperty(value = "actorId", required = true)
    @get:JsonProperty("actorId")
    val actorId: kotlin.String,

    @param:JsonProperty(value = "attemptCount", required = true)
    @get:JsonProperty("attemptCount")
    val attemptCount: java.math.BigDecimal,

    @param:JsonProperty(value = "cadenceId", required = true)
    @get:JsonProperty("cadenceId")
    val cadenceId: kotlin.String,

    @param:JsonProperty(value = "cadenceVersion", required = true)
    @get:JsonProperty("cadenceVersion")
    val cadenceVersion: java.math.BigDecimal,

    @param:JsonProperty(value = "contactId", required = true)
    @get:JsonProperty("contactId")
    val contactId: kotlin.String,

    @param:JsonProperty(value = "createdAt", required = true)
    @get:JsonProperty("createdAt")
    val createdAt: kotlin.String,

    @param:JsonProperty(value = "currentNodeId", required = true)
    @get:JsonProperty("currentNodeId")
    val currentNodeId: kotlin.String,

    @param:JsonProperty(value = "dueAt", required = true)
    @get:JsonProperty("dueAt")
    val dueAt: kotlin.String,

    @param:JsonProperty(value = "id", required = true)
    @get:JsonProperty("id")
    val id: kotlin.String,

    @param:JsonProperty(value = "idempotencyKey", required = true)
    @get:JsonProperty("idempotencyKey")
    val idempotencyKey: kotlin.String,

    @param:JsonProperty(value = "mailboxId", required = true)
    @get:JsonProperty("mailboxId")
    val mailboxId: kotlin.String,

    @param:JsonProperty(value = "status", required = true)
    @get:JsonProperty("status")
    val status: kotlin.String,

    @param:JsonProperty(value = "tenantId", required = true)
    @get:JsonProperty("tenantId")
    val tenantId: kotlin.String,

    @param:JsonProperty(value = "updatedAt", required = true)
    @get:JsonProperty("updatedAt")
    val updatedAt: kotlin.String,

    @param:JsonProperty(value = "version", required = true)
    @get:JsonProperty("version")
    val version: java.math.BigDecimal,

    @param:JsonProperty("audienceListId")
    @get:JsonProperty("audienceListId")
    val audienceListId: kotlin.String? = null,

    @param:JsonProperty("campaignId")
    @get:JsonProperty("campaignId")
    val campaignId: kotlin.String? = null,

    @param:JsonProperty("campaignName")
    @get:JsonProperty("campaignName")
    val campaignName: kotlin.String? = null,

    @param:JsonProperty("experimentContexts")
    @get:JsonProperty("experimentContexts")
    val experimentContexts: kotlin.collections.List<MailCadenceExperimentContext>? = null,

    @param:JsonProperty("lastAcceptedMessageId")
    @get:JsonProperty("lastAcceptedMessageId")
    val lastAcceptedMessageId: kotlin.String? = null,

    @param:JsonProperty("lastError")
    @get:JsonProperty("lastError")
    val lastError: kotlin.String? = null,

    @param:JsonProperty("leaseExpiresAt")
    @get:JsonProperty("leaseExpiresAt")
    val leaseExpiresAt: kotlin.String? = null,

    @param:JsonProperty("leaseOwner")
    @get:JsonProperty("leaseOwner")
    val leaseOwner: kotlin.String? = null,

    @param:JsonProperty("outcome")
    @get:JsonProperty("outcome")
    val outcome: kotlin.String? = null,

    @param:JsonProperty("pendingMessageId")
    @get:JsonProperty("pendingMessageId")
    val pendingMessageId: kotlin.String? = null,

    @param:JsonProperty("pendingNextNodeId")
    @get:JsonProperty("pendingNextNodeId")
    val pendingNextNodeId: kotlin.String? = null,

    @param:JsonProperty("taskId")
    @get:JsonProperty("taskId")
    val taskId: kotlin.String? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("actorId", "attemptCount", "cadenceId", "cadenceVersion", "contactId", "createdAt", "currentNodeId", "dueAt", "id", "idempotencyKey", "mailboxId", "status", "tenantId", "updatedAt", "version", if (audienceListId != null) "audienceListId" else null, if (campaignId != null) "campaignId" else null, if (campaignName != null) "campaignName" else null, if (experimentContexts != null) "experimentContexts" else null, if (lastAcceptedMessageId != null) "lastAcceptedMessageId" else null, if (lastError != null) "lastError" else null, if (leaseExpiresAt != null) "leaseExpiresAt" else null, if (leaseOwner != null) "leaseOwner" else null, if (outcome != null) "outcome" else null, if (pendingMessageId != null) "pendingMessageId" else null, if (pendingNextNodeId != null) "pendingNextNodeId" else null, if (taskId != null) "taskId" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("actorId", "attemptCount", "cadenceId", "cadenceVersion", "contactId", "createdAt", "currentNodeId", "dueAt", "id", "idempotencyKey", "mailboxId", "status", "tenantId", "updatedAt", "version", "audienceListId", "campaignId", "campaignName", "experimentContexts", "lastAcceptedMessageId", "lastError", "leaseExpiresAt", "leaseOwner", "outcome", "pendingMessageId", "pendingNextNodeId", "taskId")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("actorId", "attemptCount", "cadenceId", "cadenceVersion", "contactId", "createdAt", "currentNodeId", "dueAt", "id", "idempotencyKey", "mailboxId", "status", "tenantId", "updatedAt", "version")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (audienceListId == null) "audienceListId" else null, if (campaignId == null) "campaignId" else null, if (campaignName == null) "campaignName" else null, if (experimentContexts == null) "experimentContexts" else null, if (lastAcceptedMessageId == null) "lastAcceptedMessageId" else null, if (lastError == null) "lastError" else null, if (leaseExpiresAt == null) "leaseExpiresAt" else null, if (leaseOwner == null) "leaseOwner" else null, if (outcome == null) "outcome" else null, if (pendingMessageId == null) "pendingMessageId" else null, if (pendingNextNodeId == null) "pendingNextNodeId" else null, if (taskId == null) "taskId" else null)



}

