/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonValue

/**
 * 
 *
 * @param reason 
 * @param revision 
 * @param winnerVariantId 
 * @param allowInconclusiveManualDecision 
 * @param method 
 */


data class MailPostExperimentsByExperimentKeyDecideRequest (

    @param:JsonProperty(value = "reason", required = true)
    @get:JsonProperty("reason")
    val reason: kotlin.String,

    @param:JsonProperty(value = "revision", required = true)
    @get:JsonProperty("revision")
    val revision: kotlin.Int,

    @param:JsonProperty(value = "winnerVariantId", required = true)
    @get:JsonProperty("winnerVariantId")
    val winnerVariantId: kotlin.String,

    @param:JsonProperty("allowInconclusiveManualDecision")
    @get:JsonProperty("allowInconclusiveManualDecision")
    val allowInconclusiveManualDecision: kotlin.Boolean? = null,

    @param:JsonProperty("method")
    @get:JsonProperty("method")
    val method: MailPostExperimentsByExperimentKeyDecideRequest.Method? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("reason", "revision", "winnerVariantId", if (allowInconclusiveManualDecision != null) "allowInconclusiveManualDecision" else null, if (method != null) "method" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("reason", "revision", "winnerVariantId", "allowInconclusiveManualDecision", "method")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("reason", "revision", "winnerVariantId")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (allowInconclusiveManualDecision == null) "allowInconclusiveManualDecision" else null, if (method == null) "method" else null)


    /**
     * 
     *
     * Values: MANUAL,AUTOMATIC
     */
    enum class Method(@get:JsonValue val value: kotlin.String) {
        @JsonProperty(value = "manual") MANUAL("manual"),
        @JsonProperty(value = "automatic") AUTOMATIC("automatic");
    }

}

