/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param activeConnections 
 * @param activeMailboxes 
 * @param configured 
 * @param replySyncEnabled 
 * @param sequenceSupported 
 */


data class MailGetChannelsResponse200Email (

    @param:JsonProperty(value = "activeConnections", required = true)
    @get:JsonProperty("activeConnections")
    val activeConnections: java.math.BigDecimal,

    @param:JsonProperty(value = "activeMailboxes", required = true)
    @get:JsonProperty("activeMailboxes")
    val activeMailboxes: java.math.BigDecimal,

    @param:JsonProperty(value = "configured", required = true)
    @get:JsonProperty("configured")
    val configured: kotlin.Boolean,

    @param:JsonProperty(value = "replySyncEnabled", required = true)
    @get:JsonProperty("replySyncEnabled")
    val replySyncEnabled: kotlin.Boolean,

    @param:JsonProperty(value = "sequenceSupported", required = true)
    @get:JsonProperty("sequenceSupported")
    val sequenceSupported: kotlin.Boolean,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("activeConnections", "activeMailboxes", "configured", "replySyncEnabled", "sequenceSupported"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("activeConnections", "activeMailboxes", "configured", "replySyncEnabled", "sequenceSupported")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("activeConnections", "activeMailboxes", "configured", "replySyncEnabled", "sequenceSupported")
    override fun reaconNullFields(): Set<String> = setOfNotNull()



}

