/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.MailPostCadencesRequestNodesInnerAnyOf1ExperimentVariantsInner

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonValue

/**
 * Additional server validation applies; this structural schema does not express every contextual or cross-field rule.
 *
 * @param assignmentUnit 
 * @param id 
 * @param name 
 * @param variants 
 * @param attributionWindowMs 
 * @param guardrailMetrics 
 * @param hypothesis 
 * @param minimumRuntimeMs 
 * @param minimumSampleSize 
 * @param primaryMetric 
 */


data class MailPostCadencesRequestNodesInnerAnyOf1Experiment (

    @param:JsonProperty(value = "assignmentUnit", required = true)
    @get:JsonProperty("assignmentUnit")
    val assignmentUnit: MailPostCadencesRequestNodesInnerAnyOf1Experiment.AssignmentUnit,

    @param:JsonProperty(value = "id", required = true)
    @get:JsonProperty("id")
    val id: kotlin.String,

    @param:JsonProperty(value = "name", required = true)
    @get:JsonProperty("name")
    val name: kotlin.String,

    @param:JsonProperty(value = "variants", required = true)
    @get:JsonProperty("variants")
    val variants: kotlin.collections.List<MailPostCadencesRequestNodesInnerAnyOf1ExperimentVariantsInner>,

    @param:JsonProperty("attributionWindowMs")
    @get:JsonProperty("attributionWindowMs")
    val attributionWindowMs: kotlin.Int? = null,

    @param:JsonProperty("guardrailMetrics")
    @get:JsonProperty("guardrailMetrics")
    val guardrailMetrics: kotlin.collections.List<MailPostCadencesRequestNodesInnerAnyOf1Experiment.GuardrailMetrics>? = null,

    @param:JsonProperty("hypothesis")
    @get:JsonProperty("hypothesis")
    val hypothesis: kotlin.String? = null,

    @param:JsonProperty("minimumRuntimeMs")
    @get:JsonProperty("minimumRuntimeMs")
    val minimumRuntimeMs: kotlin.Int? = null,

    @param:JsonProperty("minimumSampleSize")
    @get:JsonProperty("minimumSampleSize")
    val minimumSampleSize: kotlin.Int? = null,

    @param:JsonProperty("primaryMetric")
    @get:JsonProperty("primaryMetric")
    val primaryMetric: MailPostCadencesRequestNodesInnerAnyOf1Experiment.PrimaryMetric? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("assignmentUnit", "id", "name", "variants", if (attributionWindowMs != null) "attributionWindowMs" else null, if (guardrailMetrics != null) "guardrailMetrics" else null, if (hypothesis != null) "hypothesis" else null, if (minimumRuntimeMs != null) "minimumRuntimeMs" else null, if (minimumSampleSize != null) "minimumSampleSize" else null, if (primaryMetric != null) "primaryMetric" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("assignmentUnit", "id", "name", "variants", "attributionWindowMs", "guardrailMetrics", "hypothesis", "minimumRuntimeMs", "minimumSampleSize", "primaryMetric")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("assignmentUnit", "id", "name", "variants")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (attributionWindowMs == null) "attributionWindowMs" else null, if (guardrailMetrics == null) "guardrailMetrics" else null, if (hypothesis == null) "hypothesis" else null, if (minimumRuntimeMs == null) "minimumRuntimeMs" else null, if (minimumSampleSize == null) "minimumSampleSize" else null, if (primaryMetric == null) "primaryMetric" else null)


    /**
     * 
     *
     * Values: CONTACT
     */
    enum class AssignmentUnit(@get:JsonValue val value: kotlin.String) {
        @JsonProperty(value = "contact") CONTACT("contact");
    }
    /**
     * 
     *
     * Values: BOUNCE,COMPLAINT,UNSUBSCRIBE,PERMANENT_FAILURE
     */
    enum class GuardrailMetrics(@get:JsonValue val value: kotlin.String) {
        @JsonProperty(value = "bounce") BOUNCE("bounce"),
        @JsonProperty(value = "complaint") COMPLAINT("complaint"),
        @JsonProperty(value = "unsubscribe") UNSUBSCRIBE("unsubscribe"),
        @JsonProperty(value = "permanent_failure") PERMANENT_FAILURE("permanent_failure");
    }
    /**
     * 
     *
     * Values: POSITIVE_REPLY,MEETING_BOOKED,HUMAN_REPLY,CLICK,OPEN,CUSTOM
     */
    enum class PrimaryMetric(@get:JsonValue val value: kotlin.String) {
        @JsonProperty(value = "positive_reply") POSITIVE_REPLY("positive_reply"),
        @JsonProperty(value = "meeting_booked") MEETING_BOOKED("meeting_booked"),
        @JsonProperty(value = "human_reply") HUMAN_REPLY("human_reply"),
        @JsonProperty(value = "click") CLICK("click"),
        @JsonProperty(value = "open") OPEN("open"),
        @JsonProperty(value = "custom") CUSTOM("custom");
    }

}

