/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.MailCadenceMessageExperiment

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonValue

/**
 * 
 *
 * @param id 
 * @param name 
 * @param channel 
 * @param kind 
 * @param nextNodeId 
 * @param templateId 
 * @param templateVersion 
 * @param experiment 
 */


data class MailCadenceNodeAnyOf1 (

    @param:JsonProperty(value = "id", required = true)
    @get:JsonProperty("id")
    val id: kotlin.String,

    @param:JsonProperty(value = "name", required = true)
    @get:JsonProperty("name")
    val name: kotlin.String,

    @param:JsonProperty(value = "channel", required = true)
    @get:JsonProperty("channel")
    val channel: kotlin.String,

    @param:JsonProperty(value = "kind", required = true)
    @get:JsonProperty("kind")
    val kind: MailCadenceNodeAnyOf1.Kind,

    @param:JsonProperty(value = "nextNodeId", required = true)
    @get:JsonProperty("nextNodeId")
    val nextNodeId: kotlin.String,

    @param:JsonProperty(value = "templateId", required = true)
    @get:JsonProperty("templateId")
    val templateId: kotlin.String,

    @param:JsonProperty(value = "templateVersion", required = true)
    @get:JsonProperty("templateVersion")
    val templateVersion: java.math.BigDecimal,

    @param:JsonProperty("experiment")
    @get:JsonProperty("experiment")
    val experiment: MailCadenceMessageExperiment? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("id", "name", "channel", "kind", "nextNodeId", "templateId", "templateVersion", if (experiment != null) "experiment" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("id", "name", "channel", "kind", "nextNodeId", "templateId", "templateVersion", "experiment")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("id", "name", "channel", "kind", "nextNodeId", "templateId", "templateVersion")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (experiment == null) "experiment" else null)


    /**
     * 
     *
     * Values: MESSAGE
     */
    enum class Kind(@get:JsonValue val value: kotlin.String) {
        @JsonProperty(value = "message") MESSAGE("message");
    }

}

