/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.MailGetChannelsResponse200Email
import io.reacon.sdk.kotlin.models.MailGetChannelsResponse200Execution
import io.reacon.sdk.kotlin.models.MailGetChannelsResponse200Sms
import io.reacon.sdk.kotlin.models.MailGetChannelsResponse200Whatsapp

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param email 
 * @param execution 
 * @param sms 
 * @param whatsapp 
 */


data class MailGetChannelsResponse200 (

    @param:JsonProperty(value = "email", required = true)
    @get:JsonProperty("email")
    val email: MailGetChannelsResponse200Email,

    @param:JsonProperty(value = "execution", required = true)
    @get:JsonProperty("execution")
    val execution: MailGetChannelsResponse200Execution,

    @param:JsonProperty(value = "sms", required = true)
    @get:JsonProperty("sms")
    val sms: MailGetChannelsResponse200Sms,

    @param:JsonProperty(value = "whatsapp", required = true)
    @get:JsonProperty("whatsapp")
    val whatsapp: MailGetChannelsResponse200Whatsapp,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("email", "execution", "sms", "whatsapp"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("email", "execution", "sms", "whatsapp")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("email", "execution", "sms", "whatsapp")
    override fun reaconNullFields(): Set<String> = setOfNotNull()



}

