/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.MailCadenceMessageExperimentVariant

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonValue

/**
 * 
 *
 * @param assignmentUnit 
 * @param id 
 * @param name 
 * @param variants 
 * @param attributionWindowMs 
 * @param guardrailMetrics 
 * @param hypothesis 
 * @param minimumRuntimeMs 
 * @param minimumSampleSize 
 * @param primaryMetric 
 */


data class MailCadenceMessageExperiment (

    @param:JsonProperty(value = "assignmentUnit", required = true)
    @get:JsonProperty("assignmentUnit")
    val assignmentUnit: MailCadenceMessageExperiment.AssignmentUnit,

    @param:JsonProperty(value = "id", required = true)
    @get:JsonProperty("id")
    val id: kotlin.String,

    @param:JsonProperty(value = "name", required = true)
    @get:JsonProperty("name")
    val name: kotlin.String,

    @param:JsonProperty(value = "variants", required = true)
    @get:JsonProperty("variants")
    val variants: kotlin.collections.List<MailCadenceMessageExperimentVariant>,

    @param:JsonProperty("attributionWindowMs")
    @get:JsonProperty("attributionWindowMs")
    val attributionWindowMs: java.math.BigDecimal? = null,

    @param:JsonProperty("guardrailMetrics")
    @get:JsonProperty("guardrailMetrics")
    val guardrailMetrics: kotlin.collections.List<kotlin.String>? = null,

    @param:JsonProperty("hypothesis")
    @get:JsonProperty("hypothesis")
    val hypothesis: kotlin.String? = null,

    @param:JsonProperty("minimumRuntimeMs")
    @get:JsonProperty("minimumRuntimeMs")
    val minimumRuntimeMs: java.math.BigDecimal? = null,

    @param:JsonProperty("minimumSampleSize")
    @get:JsonProperty("minimumSampleSize")
    val minimumSampleSize: java.math.BigDecimal? = null,

    @param:JsonProperty("primaryMetric")
    @get:JsonProperty("primaryMetric")
    val primaryMetric: kotlin.String? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("assignmentUnit", "id", "name", "variants", if (attributionWindowMs != null) "attributionWindowMs" else null, if (guardrailMetrics != null) "guardrailMetrics" else null, if (hypothesis != null) "hypothesis" else null, if (minimumRuntimeMs != null) "minimumRuntimeMs" else null, if (minimumSampleSize != null) "minimumSampleSize" else null, if (primaryMetric != null) "primaryMetric" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("assignmentUnit", "id", "name", "variants", "attributionWindowMs", "guardrailMetrics", "hypothesis", "minimumRuntimeMs", "minimumSampleSize", "primaryMetric")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("assignmentUnit", "id", "name", "variants")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (attributionWindowMs == null) "attributionWindowMs" else null, if (guardrailMetrics == null) "guardrailMetrics" else null, if (hypothesis == null) "hypothesis" else null, if (minimumRuntimeMs == null) "minimumRuntimeMs" else null, if (minimumSampleSize == null) "minimumSampleSize" else null, if (primaryMetric == null) "primaryMetric" else null)


    /**
     * 
     *
     * Values: CONTACT
     */
    enum class AssignmentUnit(@get:JsonValue val value: kotlin.String) {
        @JsonProperty(value = "contact") CONTACT("contact");
    }

}

