/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonValue

/**
 * 
 *
 * @param id 
 * @param name 
 * @param durationMs 
 * @param kind 
 * @param nextNodeId 
 */


data class MailCadenceNodeAnyOf2 (

    @param:JsonProperty(value = "id", required = true)
    @get:JsonProperty("id")
    val id: kotlin.String,

    @param:JsonProperty(value = "name", required = true)
    @get:JsonProperty("name")
    val name: kotlin.String,

    @param:JsonProperty(value = "durationMs", required = true)
    @get:JsonProperty("durationMs")
    val durationMs: java.math.BigDecimal,

    @param:JsonProperty(value = "kind", required = true)
    @get:JsonProperty("kind")
    val kind: MailCadenceNodeAnyOf2.Kind,

    @param:JsonProperty(value = "nextNodeId", required = true)
    @get:JsonProperty("nextNodeId")
    val nextNodeId: kotlin.String,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("id", "name", "durationMs", "kind", "nextNodeId"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("id", "name", "durationMs", "kind", "nextNodeId")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("id", "name", "durationMs", "kind", "nextNodeId")
    override fun reaconNullFields(): Set<String> = setOfNotNull()


    /**
     * 
     *
     * Values: WAIT
     */
    enum class Kind(@get:JsonValue val value: kotlin.String) {
        @JsonProperty(value = "wait") WAIT("wait");
    }

}

