/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonValue

/**
 * 
 *
 * @param meetingBooked 
 * @param negativeReply 
 * @param outOfOffice 
 * @param positiveReply 
 * @param unknownHumanReply 
 */


data class MailPostCadencesRequestStopConditions (

    @param:JsonProperty(value = "meetingBooked", required = true)
    @get:JsonProperty("meetingBooked")
    val meetingBooked: MailPostCadencesRequestStopConditions.MeetingBooked,

    @param:JsonProperty(value = "negativeReply", required = true)
    @get:JsonProperty("negativeReply")
    val negativeReply: MailPostCadencesRequestStopConditions.NegativeReply,

    @param:JsonProperty(value = "outOfOffice", required = true)
    @get:JsonProperty("outOfOffice")
    val outOfOffice: MailPostCadencesRequestStopConditions.OutOfOffice,

    @param:JsonProperty(value = "positiveReply", required = true)
    @get:JsonProperty("positiveReply")
    val positiveReply: MailPostCadencesRequestStopConditions.PositiveReply,

    @param:JsonProperty(value = "unknownHumanReply", required = true)
    @get:JsonProperty("unknownHumanReply")
    val unknownHumanReply: MailPostCadencesRequestStopConditions.UnknownHumanReply,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("meetingBooked", "negativeReply", "outOfOffice", "positiveReply", "unknownHumanReply"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("meetingBooked", "negativeReply", "outOfOffice", "positiveReply", "unknownHumanReply")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("meetingBooked", "negativeReply", "outOfOffice", "positiveReply", "unknownHumanReply")
    override fun reaconNullFields(): Set<String> = setOfNotNull()


    /**
     * 
     *
     * Values: STOP,CONTINUE
     */
    enum class MeetingBooked(@get:JsonValue val value: kotlin.String) {
        @JsonProperty(value = "stop") STOP("stop"),
        @JsonProperty(value = "continue") CONTINUE("continue");
    }
    /**
     * 
     *
     * Values: STOP,CONTINUE
     */
    enum class NegativeReply(@get:JsonValue val value: kotlin.String) {
        @JsonProperty(value = "stop") STOP("stop"),
        @JsonProperty(value = "continue") CONTINUE("continue");
    }
    /**
     * 
     *
     * Values: PAUSE,STOP,CONTINUE
     */
    enum class OutOfOffice(@get:JsonValue val value: kotlin.String) {
        @JsonProperty(value = "pause") PAUSE("pause"),
        @JsonProperty(value = "stop") STOP("stop"),
        @JsonProperty(value = "continue") CONTINUE("continue");
    }
    /**
     * 
     *
     * Values: STOP,CONTINUE
     */
    enum class PositiveReply(@get:JsonValue val value: kotlin.String) {
        @JsonProperty(value = "stop") STOP("stop"),
        @JsonProperty(value = "continue") CONTINUE("continue");
    }
    /**
     * 
     *
     * Values: STOP,CONTINUE
     */
    enum class UnknownHumanReply(@get:JsonValue val value: kotlin.String) {
        @JsonProperty(value = "stop") STOP("stop"),
        @JsonProperty(value = "continue") CONTINUE("continue");
    }

}

