/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param meetingBooked 
 * @param negativeReply 
 * @param outOfOffice 
 * @param positiveReply 
 * @param unknownHumanReply 
 */


data class MailCadenceStopConditions (

    @param:JsonProperty(value = "meetingBooked", required = true)
    @get:JsonProperty("meetingBooked")
    val meetingBooked: kotlin.String,

    @param:JsonProperty(value = "negativeReply", required = true)
    @get:JsonProperty("negativeReply")
    val negativeReply: kotlin.String,

    @param:JsonProperty(value = "outOfOffice", required = true)
    @get:JsonProperty("outOfOffice")
    val outOfOffice: kotlin.String,

    @param:JsonProperty(value = "positiveReply", required = true)
    @get:JsonProperty("positiveReply")
    val positiveReply: kotlin.String,

    @param:JsonProperty(value = "unknownHumanReply", required = true)
    @get:JsonProperty("unknownHumanReply")
    val unknownHumanReply: kotlin.String,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("meetingBooked", "negativeReply", "outOfOffice", "positiveReply", "unknownHumanReply"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("meetingBooked", "negativeReply", "outOfOffice", "positiveReply", "unknownHumanReply")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("meetingBooked", "negativeReply", "outOfOffice", "positiveReply", "unknownHumanReply")
    override fun reaconNullFields(): Set<String> = setOfNotNull()



}

