/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.MailConversationEntryFrom
import io.reacon.sdk.kotlin.models.MailInboxMessageRecord
import io.reacon.sdk.kotlin.models.MailReplyClassificationResult

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param from 
 * @param id 
 * @param inboundClassification 
 * @param mailboxId 
 * @param outboundMessageId 
 * @param providerEventId 
 * @param receivedAt 
 * @param replyClassification 
 * @param status 
 * @param subject 
 * @param tenantId 
 * @param text 
 * @param threadKey 
 * @param updatedAt 
 * @param assignedToActorId 
 * @param contactId 
 */


data class MailPostInboxByMessageIdResponse200Message (

    @param:JsonProperty(value = "from", required = true)
    @get:JsonProperty("from")
    val from: MailConversationEntryFrom,

    @param:JsonProperty(value = "id", required = true)
    @get:JsonProperty("id")
    val id: kotlin.String,

    @param:JsonProperty(value = "inboundClassification", required = true)
    @get:JsonProperty("inboundClassification")
    val inboundClassification: kotlin.String,

    @param:JsonProperty(value = "mailboxId", required = true)
    @get:JsonProperty("mailboxId")
    val mailboxId: kotlin.String,

    @param:JsonProperty(value = "outboundMessageId", required = true)
    @get:JsonProperty("outboundMessageId")
    val outboundMessageId: kotlin.String,

    @param:JsonProperty(value = "providerEventId", required = true)
    @get:JsonProperty("providerEventId")
    val providerEventId: kotlin.String,

    @param:JsonProperty(value = "receivedAt", required = true)
    @get:JsonProperty("receivedAt")
    val receivedAt: kotlin.String,

    @param:JsonProperty(value = "replyClassification", required = true)
    @get:JsonProperty("replyClassification")
    val replyClassification: MailReplyClassificationResult,

    @param:JsonProperty(value = "status", required = true)
    @get:JsonProperty("status")
    val status: kotlin.String,

    @param:JsonProperty(value = "subject", required = true)
    @get:JsonProperty("subject")
    val subject: kotlin.String,

    @param:JsonProperty(value = "tenantId", required = true)
    @get:JsonProperty("tenantId")
    val tenantId: kotlin.String,

    @param:JsonProperty(value = "text", required = true)
    @get:JsonProperty("text")
    val text: kotlin.String,

    @param:JsonProperty(value = "threadKey", required = true)
    @get:JsonProperty("threadKey")
    val threadKey: kotlin.String,

    @param:JsonProperty(value = "updatedAt", required = true)
    @get:JsonProperty("updatedAt")
    val updatedAt: kotlin.String,

    @param:JsonProperty("assignedToActorId")
    @get:JsonProperty("assignedToActorId")
    val assignedToActorId: kotlin.String? = null,

    @param:JsonProperty("contactId")
    @get:JsonProperty("contactId")
    val contactId: kotlin.String? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("from", "id", "inboundClassification", "mailboxId", "outboundMessageId", "providerEventId", "receivedAt", "replyClassification", "status", "subject", "tenantId", "text", "threadKey", "updatedAt", if (assignedToActorId != null) "assignedToActorId" else null, if (contactId != null) "contactId" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("from", "id", "inboundClassification", "mailboxId", "outboundMessageId", "providerEventId", "receivedAt", "replyClassification", "status", "subject", "tenantId", "text", "threadKey", "updatedAt", "assignedToActorId", "contactId")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("from", "id", "inboundClassification", "mailboxId", "outboundMessageId", "providerEventId", "receivedAt", "replyClassification", "status", "subject", "tenantId", "text", "threadKey", "updatedAt")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (assignedToActorId == null) "assignedToActorId" else null, if (contactId == null) "contactId" else null)



}

