/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.MailCampaignDraftRecord
import io.reacon.sdk.kotlin.models.MailPostCampaignsByCampaignIdLaunchResponse200AnyOf
import io.reacon.sdk.kotlin.models.MailPostCampaignsByCampaignIdLaunchResponse200AnyOf1
import io.reacon.sdk.kotlin.models.MailPostCampaignsByCampaignIdLaunchResponse200AnyOfCampaign
import io.reacon.sdk.kotlin.models.MailSequenceRunRecord

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param campaign 
 * @param draft 
 * @param sequences 
 */


data class MailPostCampaignsByCampaignIdLaunchResponse200 (

    @param:JsonProperty(value = "campaign", required = true)
    @get:JsonProperty("campaign")
    val campaign: MailPostCampaignsByCampaignIdLaunchResponse200AnyOfCampaign,

    @param:JsonProperty(value = "draft", required = true)
    @get:JsonProperty("draft")
    val draft: MailCampaignDraftRecord,

    @param:JsonProperty(value = "sequences", required = true)
    @get:JsonProperty("sequences")
    val sequences: kotlin.collections.List<MailSequenceRunRecord>,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("campaign", "draft", "sequences"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("campaign", "draft", "sequences")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("campaign", "draft", "sequences")
    override fun reaconNullFields(): Set<String> = setOfNotNull()



}

