/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.MailEvidenceField
import io.reacon.sdk.kotlin.models.MailSignatureCandidateFieldsPhonesInner

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param emails 
 * @param phones 
 * @param socialProfiles 
 * @param websites 
 * @param address 
 * @param company 
 * @param jobTitle 
 * @param personName 
 */


data class MailSignatureCandidateFields (

    @param:JsonProperty(value = "emails", required = true)
    @get:JsonProperty("emails")
    val emails: kotlin.collections.List<MailEvidenceField>,

    @param:JsonProperty(value = "phones", required = true)
    @get:JsonProperty("phones")
    val phones: kotlin.collections.List<MailSignatureCandidateFieldsPhonesInner>,

    @param:JsonProperty(value = "socialProfiles", required = true)
    @get:JsonProperty("socialProfiles")
    val socialProfiles: kotlin.collections.List<MailEvidenceField>,

    @param:JsonProperty(value = "websites", required = true)
    @get:JsonProperty("websites")
    val websites: kotlin.collections.List<MailEvidenceField>,

    @param:JsonProperty("address")
    @get:JsonProperty("address")
    val address: MailEvidenceField? = null,

    @param:JsonProperty("company")
    @get:JsonProperty("company")
    val company: MailEvidenceField? = null,

    @param:JsonProperty("jobTitle")
    @get:JsonProperty("jobTitle")
    val jobTitle: MailEvidenceField? = null,

    @param:JsonProperty("personName")
    @get:JsonProperty("personName")
    val personName: MailEvidenceField? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("emails", "phones", "socialProfiles", "websites", if (address != null) "address" else null, if (company != null) "company" else null, if (jobTitle != null) "jobTitle" else null, if (personName != null) "personName" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("emails", "phones", "socialProfiles", "websites", "address", "company", "jobTitle", "personName")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("emails", "phones", "socialProfiles", "websites")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (address == null) "address" else null, if (company == null) "company" else null, if (jobTitle == null) "jobTitle" else null, if (personName == null) "personName" else null)



}

