/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param acceptanceRate30d 
 * @param averageHealthScore 
 * @param bounceRate30d 
 * @param contacts 
 * @param degradedMailboxes 
 * @param mailboxes 
 * @param memberSeats 
 * @param messages30d 
 * @param monthlySends 
 * @param name 
 * @param pausedMailboxes 
 * @param replyRate30d 
 * @param teamId 
 */


data class MailMailPortfolioOverviewRow (

    @param:JsonProperty(value = "acceptanceRate30d", required = true)
    @get:JsonProperty("acceptanceRate30d")
    val acceptanceRate30d: java.math.BigDecimal,

    @param:JsonProperty(value = "averageHealthScore", required = true)
    @get:JsonProperty("averageHealthScore")
    val averageHealthScore: java.math.BigDecimal?,

    @param:JsonProperty(value = "bounceRate30d", required = true)
    @get:JsonProperty("bounceRate30d")
    val bounceRate30d: java.math.BigDecimal,

    @param:JsonProperty(value = "contacts", required = true)
    @get:JsonProperty("contacts")
    val contacts: java.math.BigDecimal,

    @param:JsonProperty(value = "degradedMailboxes", required = true)
    @get:JsonProperty("degradedMailboxes")
    val degradedMailboxes: java.math.BigDecimal,

    @param:JsonProperty(value = "mailboxes", required = true)
    @get:JsonProperty("mailboxes")
    val mailboxes: java.math.BigDecimal,

    @param:JsonProperty(value = "memberSeats", required = true)
    @get:JsonProperty("memberSeats")
    val memberSeats: java.math.BigDecimal,

    @param:JsonProperty(value = "messages30d", required = true)
    @get:JsonProperty("messages30d")
    val messages30d: java.math.BigDecimal,

    @param:JsonProperty(value = "monthlySends", required = true)
    @get:JsonProperty("monthlySends")
    val monthlySends: java.math.BigDecimal,

    @param:JsonProperty(value = "name", required = true)
    @get:JsonProperty("name")
    val name: kotlin.String,

    @param:JsonProperty(value = "pausedMailboxes", required = true)
    @get:JsonProperty("pausedMailboxes")
    val pausedMailboxes: java.math.BigDecimal,

    @param:JsonProperty(value = "replyRate30d", required = true)
    @get:JsonProperty("replyRate30d")
    val replyRate30d: java.math.BigDecimal,

    @param:JsonProperty(value = "teamId", required = true)
    @get:JsonProperty("teamId")
    val teamId: kotlin.String,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("acceptanceRate30d", "averageHealthScore", "bounceRate30d", "contacts", "degradedMailboxes", "mailboxes", "memberSeats", "messages30d", "monthlySends", "name", "pausedMailboxes", "replyRate30d", "teamId"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("acceptanceRate30d", "averageHealthScore", "bounceRate30d", "contacts", "degradedMailboxes", "mailboxes", "memberSeats", "messages30d", "monthlySends", "name", "pausedMailboxes", "replyRate30d", "teamId")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("acceptanceRate30d", "averageHealthScore", "bounceRate30d", "contacts", "degradedMailboxes", "mailboxes", "memberSeats", "messages30d", "monthlySends", "name", "pausedMailboxes", "replyRate30d", "teamId")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (averageHealthScore == null) "averageHealthScore" else null)



}

