/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.MailConversationEntry

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param propertyEntries 
 * @param id 
 * @param latestAt 
 * @param latestDirection 
 * @param latestStatus 
 * @param mailboxId 
 * @param participants 
 * @param subject 
 * @param unreadCount 
 */


data class MailConversationThread (

    @param:JsonProperty(value = "entries", required = true)
    @get:JsonProperty("entries")
    val propertyEntries: kotlin.collections.List<MailConversationEntry>,

    @param:JsonProperty(value = "id", required = true)
    @get:JsonProperty("id")
    val id: kotlin.String,

    @param:JsonProperty(value = "latestAt", required = true)
    @get:JsonProperty("latestAt")
    val latestAt: kotlin.String,

    @param:JsonProperty(value = "latestDirection", required = true)
    @get:JsonProperty("latestDirection")
    val latestDirection: kotlin.String,

    @param:JsonProperty(value = "latestStatus", required = true)
    @get:JsonProperty("latestStatus")
    val latestStatus: kotlin.String,

    @param:JsonProperty(value = "mailboxId", required = true)
    @get:JsonProperty("mailboxId")
    val mailboxId: kotlin.String,

    @param:JsonProperty(value = "participants", required = true)
    @get:JsonProperty("participants")
    val participants: kotlin.collections.List<kotlin.String>,

    @param:JsonProperty(value = "subject", required = true)
    @get:JsonProperty("subject")
    val subject: kotlin.String,

    @param:JsonProperty(value = "unreadCount", required = true)
    @get:JsonProperty("unreadCount")
    val unreadCount: java.math.BigDecimal,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("entries", "id", "latestAt", "latestDirection", "latestStatus", "mailboxId", "participants", "subject", "unreadCount"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("entries", "id", "latestAt", "latestDirection", "latestStatus", "mailboxId", "participants", "subject", "unreadCount")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("entries", "id", "latestAt", "latestDirection", "latestStatus", "mailboxId", "participants", "subject", "unreadCount")
    override fun reaconNullFields(): Set<String> = setOfNotNull()



}

