/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param `field` 
 * @param `operator` 
 * @param `value` 
 */


data class MailCadenceNodeAnyOf4AllOfCondition (

    @param:JsonProperty("field")
    @get:JsonProperty("field")
    val `field`: kotlin.String,

    @param:JsonProperty("operator")
    @get:JsonProperty("operator")
    val `operator`: kotlin.String,

    @param:JsonProperty("value")
    @get:JsonProperty("value")
    val `value`: kotlin.String

) {


}

