/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param id 
 * @param subject 
 * @param text 
 * @param weight 
 * @param html 
 * @param variables 
 */


data class MailMessageVariantInput (

    @param:JsonProperty(value = "id", required = true)
    @get:JsonProperty("id")
    val id: kotlin.String,

    @param:JsonProperty(value = "subject", required = true)
    @get:JsonProperty("subject")
    val subject: kotlin.String,

    @param:JsonProperty(value = "text", required = true)
    @get:JsonProperty("text")
    val text: kotlin.String,

    @param:JsonProperty(value = "weight", required = true)
    @get:JsonProperty("weight")
    val weight: java.math.BigDecimal,

    @param:JsonProperty("html")
    @get:JsonProperty("html")
    val html: kotlin.String? = null,

    @param:JsonProperty("variables")
    @get:JsonProperty("variables")
    val variables: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("id", "subject", "text", "weight", if (html != null) "html" else null, if (variables != null) "variables" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("id", "subject", "text", "weight", "html", "variables")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("id", "subject", "text", "weight")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (html == null) "html" else null, if (variables == null) "variables" else null)



}

