/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param contactCount 
 * @param variable 
 */


data class MailCadenceEnrollmentVariableGap (

    @param:JsonProperty(value = "contactCount", required = true)
    @get:JsonProperty("contactCount")
    val contactCount: java.math.BigDecimal,

    @param:JsonProperty(value = "variable", required = true)
    @get:JsonProperty("variable")
    val variable: kotlin.String,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("contactCount", "variable"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("contactCount", "variable")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("contactCount", "variable")
    override fun reaconNullFields(): Set<String> = setOfNotNull()



}

