/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param addedAt 
 * @param addedByActorId 
 * @param portfolioId 
 * @param teamId 
 * @param teamName 
 */


data class MailMailPortfolioTeam (

    @param:JsonProperty(value = "addedAt", required = true)
    @get:JsonProperty("addedAt")
    val addedAt: kotlin.String,

    @param:JsonProperty(value = "addedByActorId", required = true)
    @get:JsonProperty("addedByActorId")
    val addedByActorId: kotlin.String,

    @param:JsonProperty(value = "portfolioId", required = true)
    @get:JsonProperty("portfolioId")
    val portfolioId: kotlin.String,

    @param:JsonProperty(value = "teamId", required = true)
    @get:JsonProperty("teamId")
    val teamId: kotlin.String,

    @param:JsonProperty(value = "teamName", required = true)
    @get:JsonProperty("teamName")
    val teamName: kotlin.String,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("addedAt", "addedByActorId", "portfolioId", "teamId", "teamName"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("addedAt", "addedByActorId", "portfolioId", "teamId", "teamName")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("addedAt", "addedByActorId", "portfolioId", "teamId", "teamName")
    override fun reaconNullFields(): Set<String> = setOfNotNull()



}

