/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Identifies the host-owned delivery adapter used by a mailbox.  The built-in values retain editor completion, while the string intersection allows applications to register adapters for an existing transactional email service without changing Reacon Mail.
 *
 */


class MailMailboxProviderKind (

) {


}

