/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param cadence 
 * @param inbound 
 * @param outbound 
 */


data class MailGetChannelsResponse200Execution (

    @param:JsonProperty(value = "cadence", required = true)
    @get:JsonProperty("cadence")
    val cadence: kotlin.Boolean,

    @param:JsonProperty(value = "inbound", required = true)
    @get:JsonProperty("inbound")
    val inbound: kotlin.Boolean,

    @param:JsonProperty(value = "outbound", required = true)
    @get:JsonProperty("outbound")
    val outbound: kotlin.Boolean,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("cadence", "inbound", "outbound"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("cadence", "inbound", "outbound")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("cadence", "inbound", "outbound")
    override fun reaconNullFields(): Set<String> = setOfNotNull()



}

