/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.MailCampaignDraftStep
import io.reacon.sdk.kotlin.models.MailMessagePolicyInput

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param audienceListIds 
 * @param createdAt 
 * @param id 
 * @param mailboxIds 
 * @param name 
 * @param policy 
 * @param status 
 * @param steps 
 * @param tenantId 
 * @param updatedAt 
 * @param version 
 * @param launchedAt 
 * @param mailboxPoolId 
 * @param scheduledAt 
 */


data class MailCampaignDraftRecord (

    @param:JsonProperty(value = "audienceListIds", required = true)
    @get:JsonProperty("audienceListIds")
    val audienceListIds: kotlin.collections.List<kotlin.String>,

    @param:JsonProperty(value = "createdAt", required = true)
    @get:JsonProperty("createdAt")
    val createdAt: kotlin.String,

    @param:JsonProperty(value = "id", required = true)
    @get:JsonProperty("id")
    val id: kotlin.String,

    @param:JsonProperty(value = "mailboxIds", required = true)
    @get:JsonProperty("mailboxIds")
    val mailboxIds: kotlin.collections.List<kotlin.String>,

    @param:JsonProperty(value = "name", required = true)
    @get:JsonProperty("name")
    val name: kotlin.String,

    @param:JsonProperty(value = "policy", required = true)
    @get:JsonProperty("policy")
    val policy: MailMessagePolicyInput,

    @param:JsonProperty(value = "status", required = true)
    @get:JsonProperty("status")
    val status: kotlin.String,

    @param:JsonProperty(value = "steps", required = true)
    @get:JsonProperty("steps")
    val steps: kotlin.collections.List<MailCampaignDraftStep>,

    @param:JsonProperty(value = "tenantId", required = true)
    @get:JsonProperty("tenantId")
    val tenantId: kotlin.String,

    @param:JsonProperty(value = "updatedAt", required = true)
    @get:JsonProperty("updatedAt")
    val updatedAt: kotlin.String,

    @param:JsonProperty(value = "version", required = true)
    @get:JsonProperty("version")
    val version: java.math.BigDecimal,

    @param:JsonProperty("launchedAt")
    @get:JsonProperty("launchedAt")
    val launchedAt: kotlin.String? = null,

    @param:JsonProperty("mailboxPoolId")
    @get:JsonProperty("mailboxPoolId")
    val mailboxPoolId: kotlin.String? = null,

    @param:JsonProperty("scheduledAt")
    @get:JsonProperty("scheduledAt")
    val scheduledAt: kotlin.String? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("audienceListIds", "createdAt", "id", "mailboxIds", "name", "policy", "status", "steps", "tenantId", "updatedAt", "version", if (launchedAt != null) "launchedAt" else null, if (mailboxPoolId != null) "mailboxPoolId" else null, if (scheduledAt != null) "scheduledAt" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("audienceListIds", "createdAt", "id", "mailboxIds", "name", "policy", "status", "steps", "tenantId", "updatedAt", "version", "launchedAt", "mailboxPoolId", "scheduledAt")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("audienceListIds", "createdAt", "id", "mailboxIds", "name", "policy", "status", "steps", "tenantId", "updatedAt", "version")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (launchedAt == null) "launchedAt" else null, if (mailboxPoolId == null) "mailboxPoolId" else null, if (scheduledAt == null) "scheduledAt" else null)



}

