/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.MailPostMailboxesManualRequestImap
import io.reacon.sdk.kotlin.models.MailPostMailboxesManualRequestSmtp

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param email 
 * @param smtp 
 * @param dailyLimit 
 * @param hourlyLimit 
 * @param imap 
 * @param name 
 * @param rampEnabled 
 * @param rampIntervalHours 
 * @param rampStep 
 * @param startingDailyLimit 
 */


data class MailPostMailboxesManualRequest (

    @param:JsonProperty(value = "email", required = true)
    @get:JsonProperty("email")
    val email: kotlin.String,

    @param:JsonProperty(value = "smtp", required = true)
    @get:JsonProperty("smtp")
    val smtp: MailPostMailboxesManualRequestSmtp,

    @param:JsonProperty("dailyLimit")
    @get:JsonProperty("dailyLimit")
    val dailyLimit: kotlin.Int? = null,

    @param:JsonProperty("hourlyLimit")
    @get:JsonProperty("hourlyLimit")
    val hourlyLimit: kotlin.Int? = null,

    @param:JsonProperty("imap")
    @get:JsonProperty("imap")
    val imap: MailPostMailboxesManualRequestImap? = null,

    @param:JsonProperty("name")
    @get:JsonProperty("name")
    val name: kotlin.String? = null,

    @param:JsonProperty("rampEnabled")
    @get:JsonProperty("rampEnabled")
    val rampEnabled: kotlin.Boolean? = null,

    @param:JsonProperty("rampIntervalHours")
    @get:JsonProperty("rampIntervalHours")
    val rampIntervalHours: kotlin.Int? = null,

    @param:JsonProperty("rampStep")
    @get:JsonProperty("rampStep")
    val rampStep: kotlin.Int? = null,

    @param:JsonProperty("startingDailyLimit")
    @get:JsonProperty("startingDailyLimit")
    val startingDailyLimit: kotlin.Int? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("email", "smtp", if (dailyLimit != null) "dailyLimit" else null, if (hourlyLimit != null) "hourlyLimit" else null, if (imap != null) "imap" else null, if (name != null) "name" else null, if (rampEnabled != null) "rampEnabled" else null, if (rampIntervalHours != null) "rampIntervalHours" else null, if (rampStep != null) "rampStep" else null, if (startingDailyLimit != null) "startingDailyLimit" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("email", "smtp", "dailyLimit", "hourlyLimit", "imap", "name", "rampEnabled", "rampIntervalHours", "rampStep", "startingDailyLimit")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("email", "smtp")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (dailyLimit == null) "dailyLimit" else null, if (hourlyLimit == null) "hourlyLimit" else null, if (imap == null) "imap" else null, if (name == null) "name" else null, if (rampEnabled == null) "rampEnabled" else null, if (rampIntervalHours == null) "rampIntervalHours" else null, if (rampStep == null) "rampStep" else null, if (startingDailyLimit == null) "startingDailyLimit" else null)



}

