/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonValue

/**
 * Additional server validation applies; this structural schema does not express every contextual or cross-field rule.
 *
 * @param endpoint 
 * @param eventTypes 
 */


data class MailPatchWebhooksBySubscriptionIdRequest (

    @param:JsonProperty("endpoint")
    @get:JsonProperty("endpoint")
    val endpoint: java.net.URI? = null,

    @param:JsonProperty("eventTypes")
    @get:JsonProperty("eventTypes")
    val eventTypes: kotlin.collections.List<MailPatchWebhooksBySubscriptionIdRequest.EventTypes>? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull(if (endpoint != null) "endpoint" else null, if (eventTypes != null) "eventTypes" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("endpoint", "eventTypes")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf()
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (endpoint == null) "endpoint" else null, if (eventTypes == null) "eventTypes" else null)


    /**
     * 
     *
     * Values: MESSAGE_PERIOD_QUEUED,MESSAGE_PERIOD_SUPPRESSED,MESSAGE_PERIOD_SENDING,MESSAGE_PERIOD_PROVIDER_ACCEPTED,MESSAGE_PERIOD_DELIVERED,MESSAGE_PERIOD_DELIVERY_DEFERRED,MESSAGE_PERIOD_RETRY_SCHEDULED,MESSAGE_PERIOD_POLICY_DEFERRED,MESSAGE_PERIOD_FAILED,MESSAGE_PERIOD_CANCELLED,MESSAGE_PERIOD_REPLIED,MESSAGE_PERIOD_AUTO_REPLIED,MESSAGE_PERIOD_BOUNCED,MESSAGE_PERIOD_UNSUBSCRIBED,MESSAGE_PERIOD_COMPLAINED,MESSAGE_PERIOD_OPENED,MESSAGE_PERIOD_CLICKED,MESSAGE_PERIOD_ENGAGEMENT_OBSERVED,SIGNATURE_PERIOD_EXTRACTED,SEQUENCE_PERIOD_STARTED,SEQUENCE_PERIOD_PAUSED,SEQUENCE_PERIOD_RESUMED,SEQUENCE_PERIOD_CANCELLED,SEQUENCE_PERIOD_COMPLETED,CAMPAIGN_PERIOD_STARTED,CAMPAIGN_PERIOD_PAUSED,CAMPAIGN_PERIOD_RESUMED,CAMPAIGN_PERIOD_CANCELLED,CAMPAIGN_PERIOD_COMPLETED,CONTACT_PERIOD_CREATED,CONTACT_PERIOD_UPDATED,CONTACT_PERIOD_DELETED,CONTACT_PERIOD_STAGE_CHANGED,CONTACT_PERIOD_NOTE_ADDED,TASK_PERIOD_CREATED,TASK_PERIOD_COMPLETED,REPLY_PERIOD_CLASSIFIED,EXPERIMENT_PERIOD_ASSIGNED,EXPERIMENT_PERIOD_EXPOSED,EXPERIMENT_PERIOD_DECIDED,EXPERIMENT_PERIOD_PAUSED,EXPERIMENT_PERIOD_RESUMED,EXPERIMENT_PERIOD_ARCHIVED
     */
    enum class EventTypes(@get:JsonValue val value: kotlin.String) {
        @JsonProperty(value = "message.queued") MESSAGE_PERIOD_QUEUED("message.queued"),
        @JsonProperty(value = "message.suppressed") MESSAGE_PERIOD_SUPPRESSED("message.suppressed"),
        @JsonProperty(value = "message.sending") MESSAGE_PERIOD_SENDING("message.sending"),
        @JsonProperty(value = "message.provider_accepted") MESSAGE_PERIOD_PROVIDER_ACCEPTED("message.provider_accepted"),
        @JsonProperty(value = "message.delivered") MESSAGE_PERIOD_DELIVERED("message.delivered"),
        @JsonProperty(value = "message.delivery_deferred") MESSAGE_PERIOD_DELIVERY_DEFERRED("message.delivery_deferred"),
        @JsonProperty(value = "message.retry_scheduled") MESSAGE_PERIOD_RETRY_SCHEDULED("message.retry_scheduled"),
        @JsonProperty(value = "message.policy_deferred") MESSAGE_PERIOD_POLICY_DEFERRED("message.policy_deferred"),
        @JsonProperty(value = "message.failed") MESSAGE_PERIOD_FAILED("message.failed"),
        @JsonProperty(value = "message.cancelled") MESSAGE_PERIOD_CANCELLED("message.cancelled"),
        @JsonProperty(value = "message.replied") MESSAGE_PERIOD_REPLIED("message.replied"),
        @JsonProperty(value = "message.auto_replied") MESSAGE_PERIOD_AUTO_REPLIED("message.auto_replied"),
        @JsonProperty(value = "message.bounced") MESSAGE_PERIOD_BOUNCED("message.bounced"),
        @JsonProperty(value = "message.unsubscribed") MESSAGE_PERIOD_UNSUBSCRIBED("message.unsubscribed"),
        @JsonProperty(value = "message.complained") MESSAGE_PERIOD_COMPLAINED("message.complained"),
        @JsonProperty(value = "message.opened") MESSAGE_PERIOD_OPENED("message.opened"),
        @JsonProperty(value = "message.clicked") MESSAGE_PERIOD_CLICKED("message.clicked"),
        @JsonProperty(value = "message.engagement_observed") MESSAGE_PERIOD_ENGAGEMENT_OBSERVED("message.engagement_observed"),
        @JsonProperty(value = "signature.extracted") SIGNATURE_PERIOD_EXTRACTED("signature.extracted"),
        @JsonProperty(value = "sequence.started") SEQUENCE_PERIOD_STARTED("sequence.started"),
        @JsonProperty(value = "sequence.paused") SEQUENCE_PERIOD_PAUSED("sequence.paused"),
        @JsonProperty(value = "sequence.resumed") SEQUENCE_PERIOD_RESUMED("sequence.resumed"),
        @JsonProperty(value = "sequence.cancelled") SEQUENCE_PERIOD_CANCELLED("sequence.cancelled"),
        @JsonProperty(value = "sequence.completed") SEQUENCE_PERIOD_COMPLETED("sequence.completed"),
        @JsonProperty(value = "campaign.started") CAMPAIGN_PERIOD_STARTED("campaign.started"),
        @JsonProperty(value = "campaign.paused") CAMPAIGN_PERIOD_PAUSED("campaign.paused"),
        @JsonProperty(value = "campaign.resumed") CAMPAIGN_PERIOD_RESUMED("campaign.resumed"),
        @JsonProperty(value = "campaign.cancelled") CAMPAIGN_PERIOD_CANCELLED("campaign.cancelled"),
        @JsonProperty(value = "campaign.completed") CAMPAIGN_PERIOD_COMPLETED("campaign.completed"),
        @JsonProperty(value = "contact.created") CONTACT_PERIOD_CREATED("contact.created"),
        @JsonProperty(value = "contact.updated") CONTACT_PERIOD_UPDATED("contact.updated"),
        @JsonProperty(value = "contact.deleted") CONTACT_PERIOD_DELETED("contact.deleted"),
        @JsonProperty(value = "contact.stage_changed") CONTACT_PERIOD_STAGE_CHANGED("contact.stage_changed"),
        @JsonProperty(value = "contact.note_added") CONTACT_PERIOD_NOTE_ADDED("contact.note_added"),
        @JsonProperty(value = "task.created") TASK_PERIOD_CREATED("task.created"),
        @JsonProperty(value = "task.completed") TASK_PERIOD_COMPLETED("task.completed"),
        @JsonProperty(value = "reply.classified") REPLY_PERIOD_CLASSIFIED("reply.classified"),
        @JsonProperty(value = "experiment.assigned") EXPERIMENT_PERIOD_ASSIGNED("experiment.assigned"),
        @JsonProperty(value = "experiment.exposed") EXPERIMENT_PERIOD_EXPOSED("experiment.exposed"),
        @JsonProperty(value = "experiment.decided") EXPERIMENT_PERIOD_DECIDED("experiment.decided"),
        @JsonProperty(value = "experiment.paused") EXPERIMENT_PERIOD_PAUSED("experiment.paused"),
        @JsonProperty(value = "experiment.resumed") EXPERIMENT_PERIOD_RESUMED("experiment.resumed"),
        @JsonProperty(value = "experiment.archived") EXPERIMENT_PERIOD_ARCHIVED("experiment.archived");
    }

}

