/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.MailReplyAutomationRuleActionsTask

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param stopCadences 
 * @param assignToActorId 
 * @param stage 
 * @param task 
 */


data class MailReplyAutomationRuleActions (

    @param:JsonProperty(value = "stopCadences", required = true)
    @get:JsonProperty("stopCadences")
    val stopCadences: kotlin.Boolean,

    @param:JsonProperty("assignToActorId")
    @get:JsonProperty("assignToActorId")
    val assignToActorId: kotlin.String? = null,

    @param:JsonProperty("stage")
    @get:JsonProperty("stage")
    val stage: kotlin.String? = null,

    @param:JsonProperty("task")
    @get:JsonProperty("task")
    val task: MailReplyAutomationRuleActionsTask? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("stopCadences", if (assignToActorId != null) "assignToActorId" else null, if (stage != null) "stage" else null, if (task != null) "task" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("stopCadences", "assignToActorId", "stage", "task")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("stopCadences")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (assignToActorId == null) "assignToActorId" else null, if (stage == null) "stage" else null, if (task == null) "task" else null)



}

