/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonValue

/**
 * 
 *
 * @param assignmentUnit 
 * @param attributionWindowMs 
 * @param cadenceId 
 * @param createdAt 
 * @param createdByActorId 
 * @param experimentId 
 * @param experimentKey 
 * @param guardrailMetrics 
 * @param minimumRuntimeMs 
 * @param minimumSampleSize 
 * @param name 
 * @param primaryMetric 
 * @param status 
 * @param stepId 
 * @param tenantId 
 * @param updatedAt 
 */


data class MailExperimentDefinitionRecord (

    @param:JsonProperty(value = "assignmentUnit", required = true)
    @get:JsonProperty("assignmentUnit")
    val assignmentUnit: MailExperimentDefinitionRecord.AssignmentUnit,

    @param:JsonProperty(value = "attributionWindowMs", required = true)
    @get:JsonProperty("attributionWindowMs")
    val attributionWindowMs: java.math.BigDecimal,

    @param:JsonProperty(value = "cadenceId", required = true)
    @get:JsonProperty("cadenceId")
    val cadenceId: kotlin.String,

    @param:JsonProperty(value = "createdAt", required = true)
    @get:JsonProperty("createdAt")
    val createdAt: kotlin.String,

    @param:JsonProperty(value = "createdByActorId", required = true)
    @get:JsonProperty("createdByActorId")
    val createdByActorId: kotlin.String,

    @param:JsonProperty(value = "experimentId", required = true)
    @get:JsonProperty("experimentId")
    val experimentId: kotlin.String,

    @param:JsonProperty(value = "experimentKey", required = true)
    @get:JsonProperty("experimentKey")
    val experimentKey: kotlin.String,

    @param:JsonProperty(value = "guardrailMetrics", required = true)
    @get:JsonProperty("guardrailMetrics")
    val guardrailMetrics: kotlin.collections.List<kotlin.String>,

    @param:JsonProperty(value = "minimumRuntimeMs", required = true)
    @get:JsonProperty("minimumRuntimeMs")
    val minimumRuntimeMs: java.math.BigDecimal,

    @param:JsonProperty(value = "minimumSampleSize", required = true)
    @get:JsonProperty("minimumSampleSize")
    val minimumSampleSize: java.math.BigDecimal,

    @param:JsonProperty(value = "name", required = true)
    @get:JsonProperty("name")
    val name: kotlin.String,

    @param:JsonProperty(value = "primaryMetric", required = true)
    @get:JsonProperty("primaryMetric")
    val primaryMetric: kotlin.String,

    @param:JsonProperty(value = "status", required = true)
    @get:JsonProperty("status")
    val status: kotlin.String,

    @param:JsonProperty(value = "stepId", required = true)
    @get:JsonProperty("stepId")
    val stepId: kotlin.String,

    @param:JsonProperty(value = "tenantId", required = true)
    @get:JsonProperty("tenantId")
    val tenantId: kotlin.String,

    @param:JsonProperty(value = "updatedAt", required = true)
    @get:JsonProperty("updatedAt")
    val updatedAt: kotlin.String,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("assignmentUnit", "attributionWindowMs", "cadenceId", "createdAt", "createdByActorId", "experimentId", "experimentKey", "guardrailMetrics", "minimumRuntimeMs", "minimumSampleSize", "name", "primaryMetric", "status", "stepId", "tenantId", "updatedAt"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("assignmentUnit", "attributionWindowMs", "cadenceId", "createdAt", "createdByActorId", "experimentId", "experimentKey", "guardrailMetrics", "minimumRuntimeMs", "minimumSampleSize", "name", "primaryMetric", "status", "stepId", "tenantId", "updatedAt")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("assignmentUnit", "attributionWindowMs", "cadenceId", "createdAt", "createdByActorId", "experimentId", "experimentKey", "guardrailMetrics", "minimumRuntimeMs", "minimumSampleSize", "name", "primaryMetric", "status", "stepId", "tenantId", "updatedAt")
    override fun reaconNullFields(): Set<String> = setOfNotNull()


    /**
     * 
     *
     * Values: CONTACT
     */
    enum class AssignmentUnit(@get:JsonValue val value: kotlin.String) {
        @JsonProperty(value = "contact") CONTACT("contact");
    }

}

