/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param decidedAt 
 * @param decidedByActorId 
 * @param experimentKey 
 * @param id 
 * @param method 
 * @param reason 
 * @param resultSnapshot 
 * @param revision 
 * @param tenantId 
 * @param winnerVariantId 
 */


data class MailExperimentDecisionRecord (

    @param:JsonProperty(value = "decidedAt", required = true)
    @get:JsonProperty("decidedAt")
    val decidedAt: kotlin.String,

    @param:JsonProperty(value = "decidedByActorId", required = true)
    @get:JsonProperty("decidedByActorId")
    val decidedByActorId: kotlin.String,

    @param:JsonProperty(value = "experimentKey", required = true)
    @get:JsonProperty("experimentKey")
    val experimentKey: kotlin.String,

    @param:JsonProperty(value = "id", required = true)
    @get:JsonProperty("id")
    val id: kotlin.String,

    @param:JsonProperty(value = "method", required = true)
    @get:JsonProperty("method")
    val method: kotlin.String,

    @param:JsonProperty(value = "reason", required = true)
    @get:JsonProperty("reason")
    val reason: kotlin.String,

    @param:JsonProperty(value = "resultSnapshot", required = true)
    @get:JsonProperty("resultSnapshot")
    val resultSnapshot: kotlin.Any,

    @param:JsonProperty(value = "revision", required = true)
    @get:JsonProperty("revision")
    val revision: java.math.BigDecimal,

    @param:JsonProperty(value = "tenantId", required = true)
    @get:JsonProperty("tenantId")
    val tenantId: kotlin.String,

    @param:JsonProperty(value = "winnerVariantId", required = true)
    @get:JsonProperty("winnerVariantId")
    val winnerVariantId: kotlin.String,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("decidedAt", "decidedByActorId", "experimentKey", "id", "method", "reason", "resultSnapshot", "revision", "tenantId", "winnerVariantId"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("decidedAt", "decidedByActorId", "experimentKey", "id", "method", "reason", "resultSnapshot", "revision", "tenantId", "winnerVariantId")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("decidedAt", "decidedByActorId", "experimentKey", "id", "method", "reason", "resultSnapshot", "revision", "tenantId", "winnerVariantId")
    override fun reaconNullFields(): Set<String> = setOfNotNull()



}

