/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.MailCadenceRunRecord
import io.reacon.sdk.kotlin.models.MailCampaignDraftRecord
import io.reacon.sdk.kotlin.models.MailGetOverviewResponse200Inbox
import io.reacon.sdk.kotlin.models.MailMailboxConnectionRecord
import io.reacon.sdk.kotlin.models.MailMailboxHealthRecord
import io.reacon.sdk.kotlin.models.MailMailboxRecord
import io.reacon.sdk.kotlin.models.MailMessageAnalyticsOverview

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param analytics 
 * @param cadenceRuns 
 * @param campaigns 
 * @param connections 
 * @param health 
 * @param inbox 
 * @param mailboxes 
 */


data class MailGetOverviewResponse200 (

    @param:JsonProperty(value = "analytics", required = true)
    @get:JsonProperty("analytics")
    val analytics: MailMessageAnalyticsOverview,

    @param:JsonProperty(value = "cadenceRuns", required = true)
    @get:JsonProperty("cadenceRuns")
    val cadenceRuns: kotlin.collections.List<MailCadenceRunRecord>,

    @param:JsonProperty(value = "campaigns", required = true)
    @get:JsonProperty("campaigns")
    val campaigns: kotlin.collections.List<MailCampaignDraftRecord>,

    @param:JsonProperty(value = "connections", required = true)
    @get:JsonProperty("connections")
    val connections: kotlin.collections.List<MailMailboxConnectionRecord>,

    @param:JsonProperty(value = "health", required = true)
    @get:JsonProperty("health")
    val health: kotlin.collections.List<MailMailboxHealthRecord>,

    @param:JsonProperty(value = "inbox", required = true)
    @get:JsonProperty("inbox")
    val inbox: MailGetOverviewResponse200Inbox,

    @param:JsonProperty(value = "mailboxes", required = true)
    @get:JsonProperty("mailboxes")
    val mailboxes: kotlin.collections.List<MailMailboxRecord>,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("analytics", "cadenceRuns", "campaigns", "connections", "health", "inbox", "mailboxes"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("analytics", "cadenceRuns", "campaigns", "connections", "health", "inbox", "mailboxes")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("analytics", "cadenceRuns", "campaigns", "connections", "health", "inbox", "mailboxes")
    override fun reaconNullFields(): Set<String> = setOfNotNull()



}

