/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.MailPostMessagesRequestTo

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param idempotencyKey 
 * @param mailboxId 
 * @param subject 
 * @param text 
 * @param to 
 * @param delayMs 
 * @param html 
 */


data class MailPostMessagesRequest (

    @param:JsonProperty(value = "idempotencyKey", required = true)
    @get:JsonProperty("idempotencyKey")
    val idempotencyKey: kotlin.String,

    @param:JsonProperty(value = "mailboxId", required = true)
    @get:JsonProperty("mailboxId")
    val mailboxId: kotlin.String,

    @param:JsonProperty(value = "subject", required = true)
    @get:JsonProperty("subject")
    val subject: kotlin.String,

    @param:JsonProperty(value = "text", required = true)
    @get:JsonProperty("text")
    val text: kotlin.String,

    @param:JsonProperty(value = "to", required = true)
    @get:JsonProperty("to")
    val to: MailPostMessagesRequestTo,

    @param:JsonProperty("delayMs")
    @get:JsonProperty("delayMs")
    val delayMs: kotlin.Int? = null,

    @param:JsonProperty("html")
    @get:JsonProperty("html")
    val html: kotlin.String? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("idempotencyKey", "mailboxId", "subject", "text", "to", if (delayMs != null) "delayMs" else null, if (html != null) "html" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("idempotencyKey", "mailboxId", "subject", "text", "to", "delayMs", "html")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("idempotencyKey", "mailboxId", "subject", "text", "to")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (delayMs == null) "delayMs" else null, if (html == null) "html" else null)



}

