/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.MailImapCursor
import io.reacon.sdk.kotlin.models.MailStoredImapSettings
import io.reacon.sdk.kotlin.models.MailStoredSmtpSettings

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param createdAt 
 * @param cursors 
 * @param integrationConnectionId 
 * @param lastVerifiedAt 
 * @param mailboxId 
 * @param nextPollAt 
 * @param status 
 * @param tenantId 
 * @param updatedAt 
 * @param version 
 * @param credentialId 
 * @param imap 
 * @param lastErrorCode 
 * @param lastPolledAt 
 * @param oauthProvider 
 * @param smtp 
 */


data class MailMailboxConnectionRecord (

    @param:JsonProperty(value = "createdAt", required = true)
    @get:JsonProperty("createdAt")
    val createdAt: kotlin.String,

    @param:JsonProperty(value = "cursors", required = true)
    @get:JsonProperty("cursors")
    val cursors: kotlin.collections.Map<kotlin.String, MailImapCursor>,

    @param:JsonProperty(value = "integrationConnectionId", required = true)
    @get:JsonProperty("integrationConnectionId")
    val integrationConnectionId: kotlin.String,

    @param:JsonProperty(value = "lastVerifiedAt", required = true)
    @get:JsonProperty("lastVerifiedAt")
    val lastVerifiedAt: kotlin.String,

    @param:JsonProperty(value = "mailboxId", required = true)
    @get:JsonProperty("mailboxId")
    val mailboxId: kotlin.String,

    @param:JsonProperty(value = "nextPollAt", required = true)
    @get:JsonProperty("nextPollAt")
    val nextPollAt: kotlin.String,

    @param:JsonProperty(value = "status", required = true)
    @get:JsonProperty("status")
    val status: kotlin.String,

    @param:JsonProperty(value = "tenantId", required = true)
    @get:JsonProperty("tenantId")
    val tenantId: kotlin.String,

    @param:JsonProperty(value = "updatedAt", required = true)
    @get:JsonProperty("updatedAt")
    val updatedAt: kotlin.String,

    @param:JsonProperty(value = "version", required = true)
    @get:JsonProperty("version")
    val version: java.math.BigDecimal,

    @param:JsonProperty("credentialId")
    @get:JsonProperty("credentialId")
    val credentialId: kotlin.String? = null,

    @param:JsonProperty("imap")
    @get:JsonProperty("imap")
    val imap: MailStoredImapSettings? = null,

    @param:JsonProperty("lastErrorCode")
    @get:JsonProperty("lastErrorCode")
    val lastErrorCode: kotlin.String? = null,

    @param:JsonProperty("lastPolledAt")
    @get:JsonProperty("lastPolledAt")
    val lastPolledAt: kotlin.String? = null,

    @param:JsonProperty("oauthProvider")
    @get:JsonProperty("oauthProvider")
    val oauthProvider: kotlin.String? = null,

    @param:JsonProperty("smtp")
    @get:JsonProperty("smtp")
    val smtp: MailStoredSmtpSettings? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("createdAt", "cursors", "integrationConnectionId", "lastVerifiedAt", "mailboxId", "nextPollAt", "status", "tenantId", "updatedAt", "version", if (credentialId != null) "credentialId" else null, if (imap != null) "imap" else null, if (lastErrorCode != null) "lastErrorCode" else null, if (lastPolledAt != null) "lastPolledAt" else null, if (oauthProvider != null) "oauthProvider" else null, if (smtp != null) "smtp" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("createdAt", "cursors", "integrationConnectionId", "lastVerifiedAt", "mailboxId", "nextPollAt", "status", "tenantId", "updatedAt", "version", "credentialId", "imap", "lastErrorCode", "lastPolledAt", "oauthProvider", "smtp")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("createdAt", "cursors", "integrationConnectionId", "lastVerifiedAt", "mailboxId", "nextPollAt", "status", "tenantId", "updatedAt", "version")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (credentialId == null) "credentialId" else null, if (imap == null) "imap" else null, if (lastErrorCode == null) "lastErrorCode" else null, if (lastPolledAt == null) "lastPolledAt" else null, if (oauthProvider == null) "oauthProvider" else null, if (smtp == null) "smtp" else null)



}

