/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.MailMessageTemplateVersionWhatsappApproval

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param body 
 * @param channel 
 * @param createdAt 
 * @param createdByActorId 
 * @param id 
 * @param name 
 * @param status 
 * @param tenantId 
 * @param variables 
 * @param version 
 * @param subject 
 * @param whatsappApproval 
 */


data class MailMessageTemplateVersion (

    @param:JsonProperty(value = "body", required = true)
    @get:JsonProperty("body")
    val body: kotlin.String,

    @param:JsonProperty(value = "channel", required = true)
    @get:JsonProperty("channel")
    val channel: kotlin.String,

    @param:JsonProperty(value = "createdAt", required = true)
    @get:JsonProperty("createdAt")
    val createdAt: kotlin.String,

    @param:JsonProperty(value = "createdByActorId", required = true)
    @get:JsonProperty("createdByActorId")
    val createdByActorId: kotlin.String,

    @param:JsonProperty(value = "id", required = true)
    @get:JsonProperty("id")
    val id: kotlin.String,

    @param:JsonProperty(value = "name", required = true)
    @get:JsonProperty("name")
    val name: kotlin.String,

    @param:JsonProperty(value = "status", required = true)
    @get:JsonProperty("status")
    val status: kotlin.String,

    @param:JsonProperty(value = "tenantId", required = true)
    @get:JsonProperty("tenantId")
    val tenantId: kotlin.String,

    @param:JsonProperty(value = "variables", required = true)
    @get:JsonProperty("variables")
    val variables: kotlin.collections.List<kotlin.String>,

    @param:JsonProperty(value = "version", required = true)
    @get:JsonProperty("version")
    val version: java.math.BigDecimal,

    @param:JsonProperty("subject")
    @get:JsonProperty("subject")
    val subject: kotlin.String? = null,

    @param:JsonProperty("whatsappApproval")
    @get:JsonProperty("whatsappApproval")
    val whatsappApproval: MailMessageTemplateVersionWhatsappApproval? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("body", "channel", "createdAt", "createdByActorId", "id", "name", "status", "tenantId", "variables", "version", if (subject != null) "subject" else null, if (whatsappApproval != null) "whatsappApproval" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("body", "channel", "createdAt", "createdByActorId", "id", "name", "status", "tenantId", "variables", "version", "subject", "whatsappApproval")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("body", "channel", "createdAt", "createdByActorId", "id", "name", "status", "tenantId", "variables", "version")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (subject == null) "subject" else null, if (whatsappApproval == null) "whatsappApproval" else null)



}

