/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param experimentKey 
 * @param metadata 
 * @param occurredAt 
 * @param outcome 
 * @param revision 
 * @param sourceId 
 * @param tenantId 
 * @param unitId 
 * @param `value` 
 */


data class MailExperimentOutcomeRecord (

    @param:JsonProperty(value = "experimentKey", required = true)
    @get:JsonProperty("experimentKey")
    val experimentKey: kotlin.String,

    @param:JsonProperty(value = "metadata", required = true)
    @get:JsonProperty("metadata")
    val metadata: kotlin.Any,

    @param:JsonProperty(value = "occurredAt", required = true)
    @get:JsonProperty("occurredAt")
    val occurredAt: kotlin.String,

    @param:JsonProperty(value = "outcome", required = true)
    @get:JsonProperty("outcome")
    val outcome: kotlin.String,

    @param:JsonProperty(value = "revision", required = true)
    @get:JsonProperty("revision")
    val revision: java.math.BigDecimal,

    @param:JsonProperty(value = "sourceId", required = true)
    @get:JsonProperty("sourceId")
    val sourceId: kotlin.String,

    @param:JsonProperty(value = "tenantId", required = true)
    @get:JsonProperty("tenantId")
    val tenantId: kotlin.String,

    @param:JsonProperty(value = "unitId", required = true)
    @get:JsonProperty("unitId")
    val unitId: kotlin.String,

    @param:JsonProperty("value")
    @get:JsonProperty("value")
    val `value`: java.math.BigDecimal,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("experimentKey", "metadata", "occurredAt", "outcome", "revision", "sourceId", "tenantId", "unitId"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("experimentKey", "metadata", "occurredAt", "outcome", "revision", "sourceId", "tenantId", "unitId")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("experimentKey", "metadata", "occurredAt", "outcome", "revision", "sourceId", "tenantId", "unitId")
    override fun reaconNullFields(): Set<String> = setOfNotNull()



}

