/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonValue

/**
 * 
 *
 * @param provider 
 * @param name 
 * @param returnTo 
 */


data class MailPostOauthBeginRequest (

    @param:JsonProperty(value = "provider", required = true)
    @get:JsonProperty("provider")
    val provider: MailPostOauthBeginRequest.Provider,

    @param:JsonProperty("name")
    @get:JsonProperty("name")
    val name: kotlin.String? = null,

    @param:JsonProperty("returnTo")
    @get:JsonProperty("returnTo")
    val returnTo: kotlin.String? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("provider", if (name != null) "name" else null, if (returnTo != null) "returnTo" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("provider", "name", "returnTo")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("provider")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (name == null) "name" else null, if (returnTo == null) "returnTo" else null)


    /**
     * 
     *
     * Values: GMAIL,MICROSOFT
     */
    enum class Provider(@get:JsonValue val value: kotlin.String) {
        @JsonProperty(value = "gmail") GMAIL("gmail"),
        @JsonProperty(value = "microsoft") MICROSOFT("microsoft");
    }

}

