/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonValue

/**
 * 
 *
 * @param code 
 * @param message 
 * @param outcome 
 */


data class MailConversationEntryLastErrorAnyOf1 (

    @param:JsonProperty(value = "code", required = true)
    @get:JsonProperty("code")
    val code: kotlin.String,

    @param:JsonProperty(value = "message", required = true)
    @get:JsonProperty("message")
    val message: kotlin.String,

    @param:JsonProperty(value = "outcome", required = true)
    @get:JsonProperty("outcome")
    val outcome: MailConversationEntryLastErrorAnyOf1.Outcome,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("code", "message", "outcome"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("code", "message", "outcome")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("code", "message", "outcome")
    override fun reaconNullFields(): Set<String> = setOfNotNull()


    /**
     * 
     *
     * Values: PERMANENT_FAILURE
     */
    enum class Outcome(@get:JsonValue val value: kotlin.String) {
        @JsonProperty(value = "permanent_failure") PERMANENT_FAILURE("permanent_failure");
    }

}

