/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.MailMailAddress

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param createdAt 
 * @param id 
 * @param mailboxId 
 * @param messageIds 
 * @param recipient 
 * @param status 
 * @param tenantId 
 * @param updatedAt 
 * @param campaignId 
 * @param campaignName 
 */


data class MailSequenceRunRecord (

    @param:JsonProperty(value = "createdAt", required = true)
    @get:JsonProperty("createdAt")
    val createdAt: kotlin.String,

    @param:JsonProperty(value = "id", required = true)
    @get:JsonProperty("id")
    val id: kotlin.String,

    @param:JsonProperty(value = "mailboxId", required = true)
    @get:JsonProperty("mailboxId")
    val mailboxId: kotlin.String,

    @param:JsonProperty(value = "messageIds", required = true)
    @get:JsonProperty("messageIds")
    val messageIds: kotlin.collections.List<kotlin.String>,

    @param:JsonProperty(value = "recipient", required = true)
    @get:JsonProperty("recipient")
    val recipient: MailMailAddress,

    @param:JsonProperty(value = "status", required = true)
    @get:JsonProperty("status")
    val status: kotlin.String,

    @param:JsonProperty(value = "tenantId", required = true)
    @get:JsonProperty("tenantId")
    val tenantId: kotlin.String,

    @param:JsonProperty(value = "updatedAt", required = true)
    @get:JsonProperty("updatedAt")
    val updatedAt: kotlin.String,

    @param:JsonProperty("campaignId")
    @get:JsonProperty("campaignId")
    val campaignId: kotlin.String? = null,

    @param:JsonProperty("campaignName")
    @get:JsonProperty("campaignName")
    val campaignName: kotlin.String? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("createdAt", "id", "mailboxId", "messageIds", "recipient", "status", "tenantId", "updatedAt", if (campaignId != null) "campaignId" else null, if (campaignName != null) "campaignName" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("createdAt", "id", "mailboxId", "messageIds", "recipient", "status", "tenantId", "updatedAt", "campaignId", "campaignName")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("createdAt", "id", "mailboxId", "messageIds", "recipient", "status", "tenantId", "updatedAt")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (campaignId == null) "campaignId" else null, if (campaignName == null) "campaignName" else null)



}

