/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param accepted 
 * @param bounced 
 * @param complained 
 * @param replied 
 * @param total 
 * @param variantId 
 * @param campaignId 
 * @param experimentId 
 * @param experimentName 
 * @param stepId 
 */


data class MailMessageAnalyticsOverviewVariantsInner (

    @param:JsonProperty(value = "accepted", required = true)
    @get:JsonProperty("accepted")
    val accepted: java.math.BigDecimal,

    @param:JsonProperty(value = "bounced", required = true)
    @get:JsonProperty("bounced")
    val bounced: java.math.BigDecimal,

    @param:JsonProperty(value = "complained", required = true)
    @get:JsonProperty("complained")
    val complained: java.math.BigDecimal,

    @param:JsonProperty(value = "replied", required = true)
    @get:JsonProperty("replied")
    val replied: java.math.BigDecimal,

    @param:JsonProperty(value = "total", required = true)
    @get:JsonProperty("total")
    val total: java.math.BigDecimal,

    @param:JsonProperty(value = "variantId", required = true)
    @get:JsonProperty("variantId")
    val variantId: kotlin.String,

    @param:JsonProperty("campaignId")
    @get:JsonProperty("campaignId")
    val campaignId: kotlin.String? = null,

    @param:JsonProperty("experimentId")
    @get:JsonProperty("experimentId")
    val experimentId: kotlin.String? = null,

    @param:JsonProperty("experimentName")
    @get:JsonProperty("experimentName")
    val experimentName: kotlin.String? = null,

    @param:JsonProperty("stepId")
    @get:JsonProperty("stepId")
    val stepId: kotlin.String? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("accepted", "bounced", "complained", "replied", "total", "variantId", if (campaignId != null) "campaignId" else null, if (experimentId != null) "experimentId" else null, if (experimentName != null) "experimentName" else null, if (stepId != null) "stepId" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("accepted", "bounced", "complained", "replied", "total", "variantId", "campaignId", "experimentId", "experimentName", "stepId")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("accepted", "bounced", "complained", "replied", "total", "variantId")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (campaignId == null) "campaignId" else null, if (experimentId == null) "experimentId" else null, if (experimentName == null) "experimentName" else null, if (stepId == null) "stepId" else null)



}

