/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.MailCadenceWorkflowExperiment

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonValue

/**
 * 
 *
 * @param id 
 * @param name 
 * @param experiment 
 * @param kind 
 */


data class MailCadenceNodeAnyOf5 (

    @param:JsonProperty(value = "id", required = true)
    @get:JsonProperty("id")
    val id: kotlin.String,

    @param:JsonProperty(value = "name", required = true)
    @get:JsonProperty("name")
    val name: kotlin.String,

    @param:JsonProperty(value = "experiment", required = true)
    @get:JsonProperty("experiment")
    val experiment: MailCadenceWorkflowExperiment,

    @param:JsonProperty(value = "kind", required = true)
    @get:JsonProperty("kind")
    val kind: MailCadenceNodeAnyOf5.Kind,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("id", "name", "experiment", "kind"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("id", "name", "experiment", "kind")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("id", "name", "experiment", "kind")
    override fun reaconNullFields(): Set<String> = setOfNotNull()


    /**
     * 
     *
     * Values: EXPERIMENT_SPLIT
     */
    enum class Kind(@get:JsonValue val value: kotlin.String) {
        @JsonProperty(value = "experiment_split") EXPERIMENT_SPLIT("experiment_split");
    }

}

