/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param createdAt 
 * @param domain 
 * @param status 
 * @param tenantId 
 * @param updatedAt 
 * @param verificationToken 
 * @param verifiedAt 
 */


data class MailTrackingDomainRecord (

    @param:JsonProperty(value = "createdAt", required = true)
    @get:JsonProperty("createdAt")
    val createdAt: kotlin.String,

    @param:JsonProperty(value = "domain", required = true)
    @get:JsonProperty("domain")
    val domain: kotlin.String,

    @param:JsonProperty(value = "status", required = true)
    @get:JsonProperty("status")
    val status: kotlin.String,

    @param:JsonProperty(value = "tenantId", required = true)
    @get:JsonProperty("tenantId")
    val tenantId: kotlin.String,

    @param:JsonProperty(value = "updatedAt", required = true)
    @get:JsonProperty("updatedAt")
    val updatedAt: kotlin.String,

    @param:JsonProperty(value = "verificationToken", required = true)
    @get:JsonProperty("verificationToken")
    val verificationToken: kotlin.String,

    @param:JsonProperty("verifiedAt")
    @get:JsonProperty("verifiedAt")
    val verifiedAt: kotlin.String? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("createdAt", "domain", "status", "tenantId", "updatedAt", "verificationToken", if (verifiedAt != null) "verifiedAt" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("createdAt", "domain", "status", "tenantId", "updatedAt", "verificationToken", "verifiedAt")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("createdAt", "domain", "status", "tenantId", "updatedAt", "verificationToken")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (verifiedAt == null) "verifiedAt" else null)



}

