/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.MailPostCrmNotesResponse200EventPayload

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param actorId 
 * @param contactId 
 * @param id 
 * @param occurredAt 
 * @param payload 
 * @param tenantId 
 * @param type 
 */


data class MailPostCrmNotesResponse200Event (

    @param:JsonProperty(value = "actorId", required = true)
    @get:JsonProperty("actorId")
    val actorId: kotlin.String,

    @param:JsonProperty(value = "contactId", required = true)
    @get:JsonProperty("contactId")
    val contactId: kotlin.String,

    @param:JsonProperty(value = "id", required = true)
    @get:JsonProperty("id")
    val id: kotlin.String,

    @param:JsonProperty(value = "occurredAt", required = true)
    @get:JsonProperty("occurredAt")
    val occurredAt: kotlin.String,

    @param:JsonProperty(value = "payload", required = true)
    @get:JsonProperty("payload")
    val payload: MailPostCrmNotesResponse200EventPayload,

    @param:JsonProperty(value = "tenantId", required = true)
    @get:JsonProperty("tenantId")
    val tenantId: kotlin.String,

    @param:JsonProperty(value = "type", required = true)
    @get:JsonProperty("type")
    val type: kotlin.String,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("actorId", "contactId", "id", "occurredAt", "payload", "tenantId", "type"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("actorId", "contactId", "id", "occurredAt", "payload", "tenantId", "type")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("actorId", "contactId", "id", "occurredAt", "payload", "tenantId", "type")
    override fun reaconNullFields(): Set<String> = setOfNotNull()



}

