/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.MailPostCadencesRequestNodesInnerAnyOf
import io.reacon.sdk.kotlin.models.MailPostCadencesRequestNodesInnerAnyOf1
import io.reacon.sdk.kotlin.models.MailPostCadencesRequestNodesInnerAnyOf2
import io.reacon.sdk.kotlin.models.MailPostCadencesRequestNodesInnerAnyOf3
import io.reacon.sdk.kotlin.models.MailPostCadencesRequestNodesInnerAnyOf4
import io.reacon.sdk.kotlin.models.MailPostCadencesRequestNodesInnerAnyOf4Condition
import io.reacon.sdk.kotlin.models.MailPostCadencesRequestNodesInnerAnyOf5
import io.reacon.sdk.kotlin.models.MailPostCadencesRequestNodesInnerAnyOf5Experiment
import io.reacon.sdk.kotlin.models.MailPostCadencesRequestNodesInnerAnyOf6

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonValue

/**
 * Additional server validation applies; this structural schema does not express every contextual or cross-field rule.
 *
 * @param id 
 * @param kind 
 * @param name 
 * @param nextNodeId 
 * @param channel 
 * @param experiment 
 * @param templateId 
 * @param templateVersion 
 * @param durationMs 
 * @param taskType 
 * @param title 
 * @param condition 
 * @param falseNodeId 
 * @param trueNodeId 
 * @param outcome 
 */


data class MailPostCadencesRequestNodesInner (

    @param:JsonProperty(value = "id", required = true)
    @get:JsonProperty("id")
    val id: kotlin.String,

    @param:JsonProperty(value = "kind", required = true)
    @get:JsonProperty("kind")
    val kind: MailPostCadencesRequestNodesInner.Kind,

    @param:JsonProperty(value = "name", required = true)
    @get:JsonProperty("name")
    val name: kotlin.String,

    @param:JsonProperty(value = "nextNodeId", required = true)
    @get:JsonProperty("nextNodeId")
    val nextNodeId: kotlin.String,

    @param:JsonProperty(value = "channel", required = true)
    @get:JsonProperty("channel")
    val channel: MailPostCadencesRequestNodesInner.Channel,

    @param:JsonProperty(value = "experiment", required = true)
    @get:JsonProperty("experiment")
    val experiment: MailPostCadencesRequestNodesInnerAnyOf5Experiment,

    @param:JsonProperty(value = "templateId", required = true)
    @get:JsonProperty("templateId")
    val templateId: kotlin.String,

    @param:JsonProperty(value = "templateVersion", required = true)
    @get:JsonProperty("templateVersion")
    val templateVersion: kotlin.Int,

    @param:JsonProperty(value = "durationMs", required = true)
    @get:JsonProperty("durationMs")
    val durationMs: kotlin.Int,

    @param:JsonProperty(value = "taskType", required = true)
    @get:JsonProperty("taskType")
    val taskType: MailPostCadencesRequestNodesInner.TaskType,

    @param:JsonProperty(value = "title", required = true)
    @get:JsonProperty("title")
    val title: kotlin.String,

    @param:JsonProperty(value = "condition", required = true)
    @get:JsonProperty("condition")
    val condition: MailPostCadencesRequestNodesInnerAnyOf4Condition,

    @param:JsonProperty(value = "falseNodeId", required = true)
    @get:JsonProperty("falseNodeId")
    val falseNodeId: kotlin.String,

    @param:JsonProperty(value = "trueNodeId", required = true)
    @get:JsonProperty("trueNodeId")
    val trueNodeId: kotlin.String,

    @param:JsonProperty(value = "outcome", required = true)
    @get:JsonProperty("outcome")
    val outcome: kotlin.String,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("id", "kind", "name", "nextNodeId", "channel", "experiment", "templateId", "templateVersion", "durationMs", "taskType", "title", "condition", "falseNodeId", "trueNodeId", "outcome"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("id", "kind", "name", "nextNodeId", "channel", "experiment", "templateId", "templateVersion", "durationMs", "taskType", "title", "condition", "falseNodeId", "trueNodeId", "outcome")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("id", "kind", "name", "nextNodeId", "channel", "experiment", "templateId", "templateVersion", "durationMs", "taskType", "title", "condition", "falseNodeId", "trueNodeId", "outcome")
    override fun reaconNullFields(): Set<String> = setOfNotNull()


    /**
     * 
     *
     * Values: STOP
     */
    enum class Kind(@get:JsonValue val value: kotlin.String) {
        @JsonProperty(value = "stop") STOP("stop");
    }
    /**
     * 
     *
     * Values: EMAIL,SMS,WHATSAPP
     */
    enum class Channel(@get:JsonValue val value: kotlin.String) {
        @JsonProperty(value = "email") EMAIL("email"),
        @JsonProperty(value = "sms") SMS("sms"),
        @JsonProperty(value = "whatsapp") WHATSAPP("whatsapp");
    }
    /**
     * 
     *
     * Values: CALL,MANUAL_EMAIL,LINKEDIN_PROFILE_VISIT,LINKEDIN_FOLLOW,LINKEDIN_CONNECTION,LINKEDIN_MESSAGE,LINKEDIN_VOICE,RESEARCH,PERSONALIZATION,REVIEW,FOLLOW_UP,OTHER
     */
    enum class TaskType(@get:JsonValue val value: kotlin.String) {
        @JsonProperty(value = "call") CALL("call"),
        @JsonProperty(value = "manual_email") MANUAL_EMAIL("manual_email"),
        @JsonProperty(value = "linkedin_profile_visit") LINKEDIN_PROFILE_VISIT("linkedin_profile_visit"),
        @JsonProperty(value = "linkedin_follow") LINKEDIN_FOLLOW("linkedin_follow"),
        @JsonProperty(value = "linkedin_connection") LINKEDIN_CONNECTION("linkedin_connection"),
        @JsonProperty(value = "linkedin_message") LINKEDIN_MESSAGE("linkedin_message"),
        @JsonProperty(value = "linkedin_voice") LINKEDIN_VOICE("linkedin_voice"),
        @JsonProperty(value = "research") RESEARCH("research"),
        @JsonProperty(value = "personalization") PERSONALIZATION("personalization"),
        @JsonProperty(value = "review") REVIEW("review"),
        @JsonProperty(value = "follow_up") FOLLOW_UP("follow_up"),
        @JsonProperty(value = "other") OTHER("other");
    }

}

