/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param approvedAt 
 * @param id 
 * @param language 
 * @param templateName 
 */


data class MailPostTemplatesRequestWhatsappApproval (

    @param:JsonProperty(value = "approvedAt", required = true)
    @get:JsonProperty("approvedAt")
    val approvedAt: kotlin.String,

    @param:JsonProperty(value = "id", required = true)
    @get:JsonProperty("id")
    val id: kotlin.String,

    @param:JsonProperty(value = "language", required = true)
    @get:JsonProperty("language")
    val language: kotlin.String,

    @param:JsonProperty(value = "templateName", required = true)
    @get:JsonProperty("templateName")
    val templateName: kotlin.String,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("approvedAt", "id", "language", "templateName"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("approvedAt", "id", "language", "templateName")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("approvedAt", "id", "language", "templateName")
    override fun reaconNullFields(): Set<String> = setOfNotNull()



}

