/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param domain 
 * @param dkimSelectors 
 */


data class MailPostDeliverabilityDomainHealthRequest (

    @param:JsonProperty(value = "domain", required = true)
    @get:JsonProperty("domain")
    val domain: kotlin.String,

    @param:JsonProperty("dkimSelectors")
    @get:JsonProperty("dkimSelectors")
    val dkimSelectors: kotlin.collections.List<kotlin.String>? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("domain", if (dkimSelectors != null) "dkimSelectors" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("domain", "dkimSelectors")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("domain")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (dkimSelectors == null) "dkimSelectors" else null)



}

