/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.MailPostSuppressionsRequestAnyOf
import io.reacon.sdk.kotlin.models.MailPostSuppressionsRequestAnyOf1

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonValue

/**
 * 
 *
 * @param scope 
 * @param `value` 
 */


data class MailPostSuppressionsRequest (

    @param:JsonProperty(value = "scope", required = true)
    @get:JsonProperty("scope")
    val scope: MailPostSuppressionsRequest.Scope,

    @param:JsonProperty("value")
    @get:JsonProperty("value")
    val `value`: kotlin.String,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("scope"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("scope")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("scope")
    override fun reaconNullFields(): Set<String> = setOfNotNull()


    /**
     * 
     *
     * Values: EMAIL,DOMAIN
     */
    enum class Scope(@get:JsonValue val value: kotlin.String) {
        @JsonProperty(value = "email") EMAIL("email"),
        @JsonProperty(value = "domain") DOMAIN("domain");
    }

}

