/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.MailCadenceRunRecord

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param runs 
 */


data class MailPostCadenceRunsResponse200 (

    @param:JsonProperty(value = "runs", required = true)
    @get:JsonProperty("runs")
    val runs: kotlin.collections.List<MailCadenceRunRecord>,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("runs"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("runs")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("runs")
    override fun reaconNullFields(): Set<String> = setOfNotNull()



}

