/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.MailMailAddress
import io.reacon.sdk.kotlin.models.MailMessagePolicy
import io.reacon.sdk.kotlin.models.MailProviderFailure
import io.reacon.sdk.kotlin.models.MailRenderedMessage

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param attemptCount 
 * @param bcc 
 * @param cc 
 * @param createdAt 
 * @param id 
 * @param idempotencyKey 
 * @param mailboxId 
 * @param metadata 
 * @param nextAttemptAt 
 * @param policy 
 * @param rendered 
 * @param replyTo 
 * @param scheduledAt 
 * @param status 
 * @param tenantId 
 * @param to 
 * @param updatedAt 
 * @param version 
 * @param acceptedAt 
 * @param internetMessageId 
 * @param lastError 
 * @param leaseExpiresAt 
 * @param leaseOwner 
 * @param parentMessageId 
 * @param providerMessageId 
 * @param providerThreadId 
 * @param sequenceRunId 
 * @param sequenceStepIndex 
 * @param variantId 
 */


data class MailMessageRecord (

    @param:JsonProperty(value = "attemptCount", required = true)
    @get:JsonProperty("attemptCount")
    val attemptCount: java.math.BigDecimal,

    @param:JsonProperty(value = "bcc", required = true)
    @get:JsonProperty("bcc")
    val bcc: kotlin.collections.List<MailMailAddress>,

    @param:JsonProperty(value = "cc", required = true)
    @get:JsonProperty("cc")
    val cc: kotlin.collections.List<MailMailAddress>,

    @param:JsonProperty(value = "createdAt", required = true)
    @get:JsonProperty("createdAt")
    val createdAt: kotlin.String,

    @param:JsonProperty(value = "id", required = true)
    @get:JsonProperty("id")
    val id: kotlin.String,

    @param:JsonProperty(value = "idempotencyKey", required = true)
    @get:JsonProperty("idempotencyKey")
    val idempotencyKey: kotlin.String,

    @param:JsonProperty(value = "mailboxId", required = true)
    @get:JsonProperty("mailboxId")
    val mailboxId: kotlin.String,

    @param:JsonProperty(value = "metadata", required = true)
    @get:JsonProperty("metadata")
    val metadata: kotlin.Any,

    @param:JsonProperty(value = "nextAttemptAt", required = true)
    @get:JsonProperty("nextAttemptAt")
    val nextAttemptAt: kotlin.String,

    @param:JsonProperty(value = "policy", required = true)
    @get:JsonProperty("policy")
    val policy: MailMessagePolicy,

    @param:JsonProperty(value = "rendered", required = true)
    @get:JsonProperty("rendered")
    val rendered: MailRenderedMessage,

    @param:JsonProperty(value = "replyTo", required = true)
    @get:JsonProperty("replyTo")
    val replyTo: MailMailAddress,

    @param:JsonProperty(value = "scheduledAt", required = true)
    @get:JsonProperty("scheduledAt")
    val scheduledAt: kotlin.String,

    @param:JsonProperty(value = "status", required = true)
    @get:JsonProperty("status")
    val status: kotlin.String,

    @param:JsonProperty(value = "tenantId", required = true)
    @get:JsonProperty("tenantId")
    val tenantId: kotlin.String,

    @param:JsonProperty(value = "to", required = true)
    @get:JsonProperty("to")
    val to: kotlin.collections.List<MailMailAddress>,

    @param:JsonProperty(value = "updatedAt", required = true)
    @get:JsonProperty("updatedAt")
    val updatedAt: kotlin.String,

    @param:JsonProperty(value = "version", required = true)
    @get:JsonProperty("version")
    val version: java.math.BigDecimal,

    @param:JsonProperty("acceptedAt")
    @get:JsonProperty("acceptedAt")
    val acceptedAt: kotlin.String? = null,

    @param:JsonProperty("internetMessageId")
    @get:JsonProperty("internetMessageId")
    val internetMessageId: kotlin.String? = null,

    @param:JsonProperty("lastError")
    @get:JsonProperty("lastError")
    val lastError: MailProviderFailure? = null,

    @param:JsonProperty("leaseExpiresAt")
    @get:JsonProperty("leaseExpiresAt")
    val leaseExpiresAt: kotlin.String? = null,

    @param:JsonProperty("leaseOwner")
    @get:JsonProperty("leaseOwner")
    val leaseOwner: kotlin.String? = null,

    @param:JsonProperty("parentMessageId")
    @get:JsonProperty("parentMessageId")
    val parentMessageId: kotlin.String? = null,

    @param:JsonProperty("providerMessageId")
    @get:JsonProperty("providerMessageId")
    val providerMessageId: kotlin.String? = null,

    @param:JsonProperty("providerThreadId")
    @get:JsonProperty("providerThreadId")
    val providerThreadId: kotlin.String? = null,

    @param:JsonProperty("sequenceRunId")
    @get:JsonProperty("sequenceRunId")
    val sequenceRunId: kotlin.String? = null,

    @param:JsonProperty("sequenceStepIndex")
    @get:JsonProperty("sequenceStepIndex")
    val sequenceStepIndex: java.math.BigDecimal? = null,

    @param:JsonProperty("variantId")
    @get:JsonProperty("variantId")
    val variantId: kotlin.String? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("attemptCount", "bcc", "cc", "createdAt", "id", "idempotencyKey", "mailboxId", "metadata", "nextAttemptAt", "policy", "rendered", "replyTo", "scheduledAt", "status", "tenantId", "to", "updatedAt", "version", if (acceptedAt != null) "acceptedAt" else null, if (internetMessageId != null) "internetMessageId" else null, if (lastError != null) "lastError" else null, if (leaseExpiresAt != null) "leaseExpiresAt" else null, if (leaseOwner != null) "leaseOwner" else null, if (parentMessageId != null) "parentMessageId" else null, if (providerMessageId != null) "providerMessageId" else null, if (providerThreadId != null) "providerThreadId" else null, if (sequenceRunId != null) "sequenceRunId" else null, if (sequenceStepIndex != null) "sequenceStepIndex" else null, if (variantId != null) "variantId" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("attemptCount", "bcc", "cc", "createdAt", "id", "idempotencyKey", "mailboxId", "metadata", "nextAttemptAt", "policy", "rendered", "replyTo", "scheduledAt", "status", "tenantId", "to", "updatedAt", "version", "acceptedAt", "internetMessageId", "lastError", "leaseExpiresAt", "leaseOwner", "parentMessageId", "providerMessageId", "providerThreadId", "sequenceRunId", "sequenceStepIndex", "variantId")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("attemptCount", "bcc", "cc", "createdAt", "id", "idempotencyKey", "mailboxId", "metadata", "nextAttemptAt", "policy", "rendered", "replyTo", "scheduledAt", "status", "tenantId", "to", "updatedAt", "version")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (acceptedAt == null) "acceptedAt" else null, if (internetMessageId == null) "internetMessageId" else null, if (lastError == null) "lastError" else null, if (leaseExpiresAt == null) "leaseExpiresAt" else null, if (leaseOwner == null) "leaseOwner" else null, if (parentMessageId == null) "parentMessageId" else null, if (providerMessageId == null) "providerMessageId" else null, if (providerThreadId == null) "providerThreadId" else null, if (sequenceRunId == null) "sequenceRunId" else null, if (sequenceStepIndex == null) "sequenceStepIndex" else null, if (variantId == null) "variantId" else null)



}

