/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param experimentId 
 * @param experimentKey 
 * @param exposedAt 
 * @param revision 
 * @param unitId 
 * @param variantId 
 */


data class MailCadenceExperimentContext (

    @param:JsonProperty(value = "experimentId", required = true)
    @get:JsonProperty("experimentId")
    val experimentId: kotlin.String,

    @param:JsonProperty(value = "experimentKey", required = true)
    @get:JsonProperty("experimentKey")
    val experimentKey: kotlin.String,

    @param:JsonProperty(value = "exposedAt", required = true)
    @get:JsonProperty("exposedAt")
    val exposedAt: kotlin.String,

    @param:JsonProperty(value = "revision", required = true)
    @get:JsonProperty("revision")
    val revision: java.math.BigDecimal,

    @param:JsonProperty(value = "unitId", required = true)
    @get:JsonProperty("unitId")
    val unitId: kotlin.String,

    @param:JsonProperty(value = "variantId", required = true)
    @get:JsonProperty("variantId")
    val variantId: kotlin.String,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("experimentId", "experimentKey", "exposedAt", "revision", "unitId", "variantId"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("experimentId", "experimentKey", "exposedAt", "revision", "unitId", "variantId")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("experimentId", "experimentKey", "exposedAt", "revision", "unitId", "variantId")
    override fun reaconNullFields(): Set<String> = setOfNotNull()



}

