/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonValue

/**
 * 
 *
 * @param `field` 
 * @param `operator` 
 * @param `value` 
 */


data class MailPostCadencesRequestNodesInnerAnyOf4Condition (

    @param:JsonProperty("field")
    @get:JsonProperty("field")
    val `field`: MailPostCadencesRequestNodesInnerAnyOf4Condition.`Field`,

    @param:JsonProperty("operator")
    @get:JsonProperty("operator")
    val `operator`: MailPostCadencesRequestNodesInnerAnyOf4Condition.`Operator`,

    @param:JsonProperty("value")
    @get:JsonProperty("value")
    val `value`: kotlin.String

) {

    /**
     * 
     *
     * Values: REPLY_CLASSIFICATION,CONTACT_STATUS,TASK_OUTCOME,ENGAGEMENT,SMS_CONSENT,WHATSAPP_CONSENT
     */
    enum class `Field`(@get:JsonValue val value: kotlin.String) {
        @JsonProperty(value = "reply_classification") REPLY_CLASSIFICATION("reply_classification"),
        @JsonProperty(value = "contact_status") CONTACT_STATUS("contact_status"),
        @JsonProperty(value = "task_outcome") TASK_OUTCOME("task_outcome"),
        @JsonProperty(value = "engagement") ENGAGEMENT("engagement"),
        @JsonProperty(value = "sms_consent") SMS_CONSENT("sms_consent"),
        @JsonProperty(value = "whatsapp_consent") WHATSAPP_CONSENT("whatsapp_consent");
    }
    /**
     * 
     *
     * Values: EQUALS,NOT_EQUALS
     */
    enum class `Operator`(@get:JsonValue val value: kotlin.String) {
        @JsonProperty(value = "equals") EQUALS("equals"),
        @JsonProperty(value = "not_equals") NOT_EQUALS("not_equals");
    }

}

