/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.MailCadenceCampaignRecord
import io.reacon.sdk.kotlin.models.MailCadenceRunRecord
import io.reacon.sdk.kotlin.models.MailPostCadenceCampaignsByCampaignIdStateResponse200AnyOf
import io.reacon.sdk.kotlin.models.MailPostCadenceCampaignsByCampaignIdStateResponse200AnyOf1

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param action 
 * @param campaignId 
 * @param changedRuns 
 * @param eligibleRuns 
 * @param totalRuns 
 * @param campaign 
 */


data class MailPostCadenceCampaignsByCampaignIdStateResponse200 (

    @param:JsonProperty(value = "action", required = true)
    @get:JsonProperty("action")
    val action: kotlin.String,

    @param:JsonProperty(value = "campaignId", required = true)
    @get:JsonProperty("campaignId")
    val campaignId: kotlin.String,

    @param:JsonProperty(value = "changedRuns", required = true)
    @get:JsonProperty("changedRuns")
    val changedRuns: kotlin.collections.List<MailCadenceRunRecord>,

    @param:JsonProperty(value = "eligibleRuns", required = true)
    @get:JsonProperty("eligibleRuns")
    val eligibleRuns: java.math.BigDecimal,

    @param:JsonProperty(value = "totalRuns", required = true)
    @get:JsonProperty("totalRuns")
    val totalRuns: java.math.BigDecimal,

    @param:JsonProperty(value = "campaign", required = true)
    @get:JsonProperty("campaign")
    val campaign: MailCadenceCampaignRecord,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("action", "campaignId", "changedRuns", "eligibleRuns", "totalRuns", "campaign"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("action", "campaignId", "changedRuns", "eligibleRuns", "totalRuns", "campaign")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("action", "campaignId", "changedRuns", "eligibleRuns", "totalRuns", "campaign")
    override fun reaconNullFields(): Set<String> = setOfNotNull()



}

