/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.MailConversationEntryFrom
import io.reacon.sdk.kotlin.models.MailConversationEntryLastError
import io.reacon.sdk.kotlin.models.MailReplyClassificationResult

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param direction 
 * @param from 
 * @param id 
 * @param mailboxId 
 * @param occurredAt 
 * @param subject 
 * @param text 
 * @param to 
 * @param updatedAt 
 * @param assignedToActorId 
 * @param contactId 
 * @param deliveryStatus 
 * @param inboundClassification 
 * @param inboxMessageId 
 * @param inboxStatus 
 * @param lastError 
 * @param nextAttemptAt 
 * @param outboundMessageId 
 * @param replyClassification 
 */


data class MailConversationEntry (

    @param:JsonProperty(value = "direction", required = true)
    @get:JsonProperty("direction")
    val direction: kotlin.String,

    @param:JsonProperty(value = "from", required = true)
    @get:JsonProperty("from")
    val from: MailConversationEntryFrom,

    @param:JsonProperty(value = "id", required = true)
    @get:JsonProperty("id")
    val id: kotlin.String,

    @param:JsonProperty(value = "mailboxId", required = true)
    @get:JsonProperty("mailboxId")
    val mailboxId: kotlin.String,

    @param:JsonProperty(value = "occurredAt", required = true)
    @get:JsonProperty("occurredAt")
    val occurredAt: kotlin.String,

    @param:JsonProperty(value = "subject", required = true)
    @get:JsonProperty("subject")
    val subject: kotlin.String,

    @param:JsonProperty(value = "text", required = true)
    @get:JsonProperty("text")
    val text: kotlin.String,

    @param:JsonProperty(value = "to", required = true)
    @get:JsonProperty("to")
    val to: kotlin.collections.List<MailConversationEntryFrom>,

    @param:JsonProperty(value = "updatedAt", required = true)
    @get:JsonProperty("updatedAt")
    val updatedAt: kotlin.String,

    @param:JsonProperty("assignedToActorId")
    @get:JsonProperty("assignedToActorId")
    val assignedToActorId: kotlin.String? = null,

    @param:JsonProperty("contactId")
    @get:JsonProperty("contactId")
    val contactId: kotlin.String? = null,

    @param:JsonProperty("deliveryStatus")
    @get:JsonProperty("deliveryStatus")
    val deliveryStatus: kotlin.String? = null,

    @param:JsonProperty("inboundClassification")
    @get:JsonProperty("inboundClassification")
    val inboundClassification: kotlin.String? = null,

    @param:JsonProperty("inboxMessageId")
    @get:JsonProperty("inboxMessageId")
    val inboxMessageId: kotlin.String? = null,

    @param:JsonProperty("inboxStatus")
    @get:JsonProperty("inboxStatus")
    val inboxStatus: kotlin.String? = null,

    @param:JsonProperty("lastError")
    @get:JsonProperty("lastError")
    val lastError: MailConversationEntryLastError? = null,

    @param:JsonProperty("nextAttemptAt")
    @get:JsonProperty("nextAttemptAt")
    val nextAttemptAt: kotlin.String? = null,

    @param:JsonProperty("outboundMessageId")
    @get:JsonProperty("outboundMessageId")
    val outboundMessageId: kotlin.String? = null,

    @param:JsonProperty("replyClassification")
    @get:JsonProperty("replyClassification")
    val replyClassification: MailReplyClassificationResult? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("direction", "from", "id", "mailboxId", "occurredAt", "subject", "text", "to", "updatedAt", if (assignedToActorId != null) "assignedToActorId" else null, if (contactId != null) "contactId" else null, if (deliveryStatus != null) "deliveryStatus" else null, if (inboundClassification != null) "inboundClassification" else null, if (inboxMessageId != null) "inboxMessageId" else null, if (inboxStatus != null) "inboxStatus" else null, if (lastError != null) "lastError" else null, if (nextAttemptAt != null) "nextAttemptAt" else null, if (outboundMessageId != null) "outboundMessageId" else null, if (replyClassification != null) "replyClassification" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("direction", "from", "id", "mailboxId", "occurredAt", "subject", "text", "to", "updatedAt", "assignedToActorId", "contactId", "deliveryStatus", "inboundClassification", "inboxMessageId", "inboxStatus", "lastError", "nextAttemptAt", "outboundMessageId", "replyClassification")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("direction", "from", "id", "mailboxId", "occurredAt", "subject", "text", "to", "updatedAt")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (assignedToActorId == null) "assignedToActorId" else null, if (contactId == null) "contactId" else null, if (deliveryStatus == null) "deliveryStatus" else null, if (inboundClassification == null) "inboundClassification" else null, if (inboxMessageId == null) "inboxMessageId" else null, if (inboxStatus == null) "inboxStatus" else null, if (lastError == null) "lastError" else null, if (nextAttemptAt == null) "nextAttemptAt" else null, if (outboundMessageId == null) "outboundMessageId" else null, if (replyClassification == null) "replyClassification" else null)



}

