/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.MailPostReplyAutomationsRequestActionsTask

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonValue

/**
 * 
 *
 * @param assignToActorId 
 * @param stage 
 * @param stopCadences 
 * @param task 
 */


data class MailPostReplyAutomationsRequestActions (

    @param:JsonProperty("assignToActorId")
    @get:JsonProperty("assignToActorId")
    val assignToActorId: kotlin.String? = null,

    @param:JsonProperty("stage")
    @get:JsonProperty("stage")
    val stage: MailPostReplyAutomationsRequestActions.Stage? = null,

    @param:JsonProperty("stopCadences")
    @get:JsonProperty("stopCadences")
    val stopCadences: kotlin.Boolean? = null,

    @param:JsonProperty("task")
    @get:JsonProperty("task")
    val task: MailPostReplyAutomationsRequestActionsTask? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull(if (assignToActorId != null) "assignToActorId" else null, if (stage != null) "stage" else null, if (stopCadences != null) "stopCadences" else null, if (task != null) "task" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("assignToActorId", "stage", "stopCadences", "task")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf()
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (assignToActorId == null) "assignToActorId" else null, if (stage == null) "stage" else null, if (stopCadences == null) "stopCadences" else null, if (task == null) "task" else null)


    /**
     * 
     *
     * Values: NEW,CONTACTED,REPLIED,QUALIFIED,UNQUALIFIED,CUSTOMER,DO_NOT_CONTACT
     */
    enum class Stage(@get:JsonValue val value: kotlin.String) {
        @JsonProperty(value = "new") NEW("new"),
        @JsonProperty(value = "contacted") CONTACTED("contacted"),
        @JsonProperty(value = "replied") REPLIED("replied"),
        @JsonProperty(value = "qualified") QUALIFIED("qualified"),
        @JsonProperty(value = "unqualified") UNQUALIFIED("unqualified"),
        @JsonProperty(value = "customer") CUSTOMER("customer"),
        @JsonProperty(value = "do_not_contact") DO_NOT_CONTACT("do_not_contact");
    }

}

