/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.MailSignatureCandidate

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param candidates 
 * @param nextCursor 
 */


data class MailGetSignaturesResponse200 (

    @param:JsonProperty(value = "candidates", required = true)
    @get:JsonProperty("candidates")
    val candidates: kotlin.collections.List<MailSignatureCandidate>,

    @param:JsonProperty("nextCursor")
    @get:JsonProperty("nextCursor")
    val nextCursor: kotlin.String? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("candidates", if (nextCursor != null) "nextCursor" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("candidates", "nextCursor")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("candidates")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (nextCursor == null) "nextCursor" else null)



}

