/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.MailPostCadencesRequestNodesInner
import io.reacon.sdk.kotlin.models.MailPostCadencesRequestStopConditions

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonValue

/**
 * 
 *
 * @param name 
 * @param nodes 
 * @param status 
 * @param id 
 * @param stopConditions 
 */


data class MailPostCadencesRequest (

    @param:JsonProperty(value = "name", required = true)
    @get:JsonProperty("name")
    val name: kotlin.String,

    @param:JsonProperty(value = "nodes", required = true)
    @get:JsonProperty("nodes")
    val nodes: kotlin.collections.List<MailPostCadencesRequestNodesInner>,

    @param:JsonProperty(value = "status", required = true)
    @get:JsonProperty("status")
    val status: MailPostCadencesRequest.Status,

    @param:JsonProperty("id")
    @get:JsonProperty("id")
    val id: kotlin.String? = null,

    @param:JsonProperty("stopConditions")
    @get:JsonProperty("stopConditions")
    val stopConditions: MailPostCadencesRequestStopConditions? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("name", "nodes", "status", if (id != null) "id" else null, if (stopConditions != null) "stopConditions" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("name", "nodes", "status", "id", "stopConditions")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("name", "nodes", "status")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (id == null) "id" else null, if (stopConditions == null) "stopConditions" else null)


    /**
     * 
     *
     * Values: DRAFT,PUBLISHED,ARCHIVED
     */
    enum class Status(@get:JsonValue val value: kotlin.String) {
        @JsonProperty(value = "draft") DRAFT("draft"),
        @JsonProperty(value = "published") PUBLISHED("published"),
        @JsonProperty(value = "archived") ARCHIVED("archived");
    }

}

