/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param lastUid 
 * @param mailboxPath 
 * @param uidValidity 
 */


data class MailImapCursor (

    @param:JsonProperty(value = "lastUid", required = true)
    @get:JsonProperty("lastUid")
    val lastUid: java.math.BigDecimal,

    @param:JsonProperty(value = "mailboxPath", required = true)
    @get:JsonProperty("mailboxPath")
    val mailboxPath: kotlin.String,

    @param:JsonProperty(value = "uidValidity", required = true)
    @get:JsonProperty("uidValidity")
    val uidValidity: kotlin.String,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("lastUid", "mailboxPath", "uidValidity"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("lastUid", "mailboxPath", "uidValidity")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("lastUid", "mailboxPath", "uidValidity")
    override fun reaconNullFields(): Set<String> = setOfNotNull()



}

