/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonValue

/**
 * 
 *
 * @param contactId 
 * @param stage 
 * @param outcome 
 * @param ownerActorId 
 */


data class MailPutCrmStatesRequest (

    @param:JsonProperty(value = "contactId", required = true)
    @get:JsonProperty("contactId")
    val contactId: kotlin.String,

    @param:JsonProperty(value = "stage", required = true)
    @get:JsonProperty("stage")
    val stage: MailPutCrmStatesRequest.Stage,

    @param:JsonProperty("outcome")
    @get:JsonProperty("outcome")
    val outcome: kotlin.String? = null,

    @param:JsonProperty("ownerActorId")
    @get:JsonProperty("ownerActorId")
    val ownerActorId: kotlin.String? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("contactId", "stage", if (outcome != null) "outcome" else null, if (ownerActorId != null) "ownerActorId" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("contactId", "stage", "outcome", "ownerActorId")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("contactId", "stage")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (outcome == null) "outcome" else null, if (ownerActorId == null) "ownerActorId" else null)


    /**
     * 
     *
     * Values: NEW,CONTACTED,REPLIED,QUALIFIED,UNQUALIFIED,CUSTOMER,DO_NOT_CONTACT
     */
    enum class Stage(@get:JsonValue val value: kotlin.String) {
        @JsonProperty(value = "new") NEW("new"),
        @JsonProperty(value = "contacted") CONTACTED("contacted"),
        @JsonProperty(value = "replied") REPLIED("replied"),
        @JsonProperty(value = "qualified") QUALIFIED("qualified"),
        @JsonProperty(value = "unqualified") UNQUALIFIED("unqualified"),
        @JsonProperty(value = "customer") CUSTOMER("customer"),
        @JsonProperty(value = "do_not_contact") DO_NOT_CONTACT("do_not_contact");
    }

}

