/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.MailInboxMessageRecord

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param needsReply 
 * @param recent 
 * @param unread 
 */


data class MailGetOverviewResponse200Inbox (

    @param:JsonProperty(value = "needsReply", required = true)
    @get:JsonProperty("needsReply")
    val needsReply: java.math.BigDecimal,

    @param:JsonProperty(value = "recent", required = true)
    @get:JsonProperty("recent")
    val recent: kotlin.collections.List<MailInboxMessageRecord>,

    @param:JsonProperty(value = "unread", required = true)
    @get:JsonProperty("unread")
    val unread: java.math.BigDecimal,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("needsReply", "recent", "unread"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("needsReply", "recent", "unread")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("needsReply", "recent", "unread")
    override fun reaconNullFields(): Set<String> = setOfNotNull()



}

