/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonValue

/**
 * 
 *
 * @param assignedToActorId 
 * @param contactId 
 * @param dueAt 
 * @param title 
 * @param type 
 */


data class MailPostCrmTasksRequest (

    @param:JsonProperty(value = "assignedToActorId", required = true)
    @get:JsonProperty("assignedToActorId")
    val assignedToActorId: kotlin.String,

    @param:JsonProperty(value = "contactId", required = true)
    @get:JsonProperty("contactId")
    val contactId: kotlin.String,

    @param:JsonProperty(value = "dueAt", required = true)
    @get:JsonProperty("dueAt")
    val dueAt: kotlin.String,

    @param:JsonProperty(value = "title", required = true)
    @get:JsonProperty("title")
    val title: kotlin.String,

    @param:JsonProperty(value = "type", required = true)
    @get:JsonProperty("type")
    val type: MailPostCrmTasksRequest.Type,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("assignedToActorId", "contactId", "dueAt", "title", "type"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("assignedToActorId", "contactId", "dueAt", "title", "type")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("assignedToActorId", "contactId", "dueAt", "title", "type")
    override fun reaconNullFields(): Set<String> = setOfNotNull()


    /**
     * 
     *
     * Values: CALL,MANUAL_EMAIL,LINKEDIN_PROFILE_VISIT,LINKEDIN_FOLLOW,LINKEDIN_CONNECTION,LINKEDIN_MESSAGE,LINKEDIN_VOICE,RESEARCH,PERSONALIZATION,REVIEW,FOLLOW_UP,OTHER
     */
    enum class Type(@get:JsonValue val value: kotlin.String) {
        @JsonProperty(value = "call") CALL("call"),
        @JsonProperty(value = "manual_email") MANUAL_EMAIL("manual_email"),
        @JsonProperty(value = "linkedin_profile_visit") LINKEDIN_PROFILE_VISIT("linkedin_profile_visit"),
        @JsonProperty(value = "linkedin_follow") LINKEDIN_FOLLOW("linkedin_follow"),
        @JsonProperty(value = "linkedin_connection") LINKEDIN_CONNECTION("linkedin_connection"),
        @JsonProperty(value = "linkedin_message") LINKEDIN_MESSAGE("linkedin_message"),
        @JsonProperty(value = "linkedin_voice") LINKEDIN_VOICE("linkedin_voice"),
        @JsonProperty(value = "research") RESEARCH("research"),
        @JsonProperty(value = "personalization") PERSONALIZATION("personalization"),
        @JsonProperty(value = "review") REVIEW("review"),
        @JsonProperty(value = "follow_up") FOLLOW_UP("follow_up"),
        @JsonProperty(value = "other") OTHER("other");
    }

}

