/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.ProductAccountInfoExecution
import io.reacon.sdk.kotlin.models.ProductCombinedEnrichExecution
import io.reacon.sdk.kotlin.models.ProductCompaniesListExecution
import io.reacon.sdk.kotlin.models.ProductCompanyDeleteExecution
import io.reacon.sdk.kotlin.models.ProductCompanyEnrichExecution
import io.reacon.sdk.kotlin.models.ProductCompanyListAddExecution
import io.reacon.sdk.kotlin.models.ProductCompanyListCreateExecution
import io.reacon.sdk.kotlin.models.ProductCompanyListRemoveExecution
import io.reacon.sdk.kotlin.models.ProductCompanyListsListExecution
import io.reacon.sdk.kotlin.models.ProductCompanyTrackExecution
import io.reacon.sdk.kotlin.models.ProductCompanyUpdateExecution
import io.reacon.sdk.kotlin.models.ProductConnectedAppPushExecution
import io.reacon.sdk.kotlin.models.ProductConnectedAppPushOutput
import io.reacon.sdk.kotlin.models.ProductConnectedAppsExecution
import io.reacon.sdk.kotlin.models.ProductCustomAttributeCreateExecution
import io.reacon.sdk.kotlin.models.ProductCustomAttributesListExecution
import io.reacon.sdk.kotlin.models.ProductDiscoverCompaniesExecution
import io.reacon.sdk.kotlin.models.ProductDiscoverPeopleExecution
import io.reacon.sdk.kotlin.models.ProductDomainFinderExecution
import io.reacon.sdk.kotlin.models.ProductEmailCountExecution
import io.reacon.sdk.kotlin.models.ProductLeadBulkDeleteExecution
import io.reacon.sdk.kotlin.models.ProductLeadCreateExecution
import io.reacon.sdk.kotlin.models.ProductLeadDeleteExecution
import io.reacon.sdk.kotlin.models.ProductLeadEnrichExecution
import io.reacon.sdk.kotlin.models.ProductLeadGetExecution
import io.reacon.sdk.kotlin.models.ProductLeadListAddLeadExecution
import io.reacon.sdk.kotlin.models.ProductLeadListCreateExecution
import io.reacon.sdk.kotlin.models.ProductLeadListDeleteExecution
import io.reacon.sdk.kotlin.models.ProductLeadListRemoveLeadExecution
import io.reacon.sdk.kotlin.models.ProductLeadListUpdateExecution
import io.reacon.sdk.kotlin.models.ProductLeadListsListExecution
import io.reacon.sdk.kotlin.models.ProductLeadTagAssignExecution
import io.reacon.sdk.kotlin.models.ProductLeadTagCreateExecution
import io.reacon.sdk.kotlin.models.ProductLeadTagRemoveExecution
import io.reacon.sdk.kotlin.models.ProductLeadTagsListExecution
import io.reacon.sdk.kotlin.models.ProductLeadUpdateExecution
import io.reacon.sdk.kotlin.models.ProductLeadUpsertExecution
import io.reacon.sdk.kotlin.models.ProductLeadsListExecution
import io.reacon.sdk.kotlin.models.ProductPersonEnrichExecution
import io.reacon.sdk.kotlin.models.ProductSavedSearchesListExecution
import io.reacon.sdk.kotlin.models.ProductSequenceRecipientAddExecution
import io.reacon.sdk.kotlin.models.ProductSequenceRecipientCancelExecution
import io.reacon.sdk.kotlin.models.ProductSequenceRecipientsAddExecution
import io.reacon.sdk.kotlin.models.ProductSequenceRecipientsListExecution
import io.reacon.sdk.kotlin.models.ProductSequenceStartExecution
import io.reacon.sdk.kotlin.models.ProductSequencesListExecution
import io.reacon.sdk.kotlin.models.ProductTeamMembersExecution
import io.reacon.sdk.kotlin.models.ProductUsageExecution
import io.reacon.sdk.kotlin.models.ProductUsageHistoryExecution

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonValue
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 * 
 *
 * @param executionId 
 * @param output 
 * @param replay 
 * @param tool 
 */
@JsonIgnoreProperties(
  value = ["tool"], // ignore manually set tool, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the tool to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "tool", visible = true)
@JsonSubTypes(
    JsonSubTypes.Type(value = ProductAccountInfoExecution::class, name = "account_info"),
    JsonSubTypes.Type(value = ProductCombinedEnrichExecution::class, name = "combined_enrich"),
    JsonSubTypes.Type(value = ProductCompaniesListExecution::class, name = "companies_list"),
    JsonSubTypes.Type(value = ProductCompanyDeleteExecution::class, name = "company_delete"),
    JsonSubTypes.Type(value = ProductCompanyEnrichExecution::class, name = "company_enrich"),
    JsonSubTypes.Type(value = ProductCompanyListAddExecution::class, name = "company_list_add"),
    JsonSubTypes.Type(value = ProductCompanyListCreateExecution::class, name = "company_list_create"),
    JsonSubTypes.Type(value = ProductCompanyListRemoveExecution::class, name = "company_list_remove"),
    JsonSubTypes.Type(value = ProductCompanyListsListExecution::class, name = "company_lists_list"),
    JsonSubTypes.Type(value = ProductCompanyTrackExecution::class, name = "company_track"),
    JsonSubTypes.Type(value = ProductCompanyUpdateExecution::class, name = "company_update"),
    JsonSubTypes.Type(value = ProductConnectedAppPushExecution::class, name = "connected_app_push"),
    JsonSubTypes.Type(value = ProductConnectedAppsExecution::class, name = "connected_apps"),
    JsonSubTypes.Type(value = ProductCustomAttributeCreateExecution::class, name = "custom_attribute_create"),
    JsonSubTypes.Type(value = ProductCustomAttributesListExecution::class, name = "custom_attributes_list"),
    JsonSubTypes.Type(value = ProductDiscoverCompaniesExecution::class, name = "discover_companies"),
    JsonSubTypes.Type(value = ProductDiscoverPeopleExecution::class, name = "discover_people"),
    JsonSubTypes.Type(value = ProductDomainFinderExecution::class, name = "domain_finder"),
    JsonSubTypes.Type(value = ProductEmailCountExecution::class, name = "email_count"),
    JsonSubTypes.Type(value = ProductLeadBulkDeleteExecution::class, name = "lead_bulk_delete"),
    JsonSubTypes.Type(value = ProductLeadCreateExecution::class, name = "lead_create"),
    JsonSubTypes.Type(value = ProductLeadDeleteExecution::class, name = "lead_delete"),
    JsonSubTypes.Type(value = ProductLeadEnrichExecution::class, name = "lead_enrich"),
    JsonSubTypes.Type(value = ProductLeadGetExecution::class, name = "lead_get"),
    JsonSubTypes.Type(value = ProductLeadListAddLeadExecution::class, name = "lead_list_add_lead"),
    JsonSubTypes.Type(value = ProductLeadListCreateExecution::class, name = "lead_list_create"),
    JsonSubTypes.Type(value = ProductLeadListDeleteExecution::class, name = "lead_list_delete"),
    JsonSubTypes.Type(value = ProductLeadListRemoveLeadExecution::class, name = "lead_list_remove_lead"),
    JsonSubTypes.Type(value = ProductLeadListUpdateExecution::class, name = "lead_list_update"),
    JsonSubTypes.Type(value = ProductLeadListsListExecution::class, name = "lead_lists_list"),
    JsonSubTypes.Type(value = ProductLeadTagAssignExecution::class, name = "lead_tag_assign"),
    JsonSubTypes.Type(value = ProductLeadTagCreateExecution::class, name = "lead_tag_create"),
    JsonSubTypes.Type(value = ProductLeadTagRemoveExecution::class, name = "lead_tag_remove"),
    JsonSubTypes.Type(value = ProductLeadTagsListExecution::class, name = "lead_tags_list"),
    JsonSubTypes.Type(value = ProductLeadUpdateExecution::class, name = "lead_update"),
    JsonSubTypes.Type(value = ProductLeadUpsertExecution::class, name = "lead_upsert"),
    JsonSubTypes.Type(value = ProductLeadsListExecution::class, name = "leads_list"),
    JsonSubTypes.Type(value = ProductPersonEnrichExecution::class, name = "person_enrich"),
    JsonSubTypes.Type(value = ProductSavedSearchesListExecution::class, name = "saved_searches_list"),
    JsonSubTypes.Type(value = ProductSequenceRecipientAddExecution::class, name = "sequence_recipient_add"),
    JsonSubTypes.Type(value = ProductSequenceRecipientCancelExecution::class, name = "sequence_recipient_cancel"),
    JsonSubTypes.Type(value = ProductSequenceRecipientsAddExecution::class, name = "sequence_recipients_add"),
    JsonSubTypes.Type(value = ProductSequenceRecipientsListExecution::class, name = "sequence_recipients_list"),
    JsonSubTypes.Type(value = ProductSequenceStartExecution::class, name = "sequence_start"),
    JsonSubTypes.Type(value = ProductSequencesListExecution::class, name = "sequences_list"),
    JsonSubTypes.Type(value = ProductTeamMembersExecution::class, name = "team_members"),
    JsonSubTypes.Type(value = ProductUsageExecution::class, name = "usage"),
    JsonSubTypes.Type(value = ProductUsageHistoryExecution::class, name = "usage_history")
)

interface ProductToolExecution {

    @get:JsonProperty("executionId")
    val executionId: java.util.UUID
    @get:JsonProperty("output")
    val output: ProductConnectedAppPushOutput
    @get:JsonProperty("replay")
    val replay: kotlin.Boolean
    @get:JsonProperty("tool")
    val tool: ProductToolExecution.Tool
    /**
     * 
     *
     * Values: CONNECTED_APP_PUSH
     */
    enum class Tool(@get:JsonValue val value: kotlin.String) {
        @JsonProperty(value = "connected_app_push") CONNECTED_APP_PUSH("connected_app_push");
    }

}

