/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param companyId 
 * @param idempotencyKey 
 * @param employeeRange 
 * @param industry 
 * @param name 
 */


data class ProductCompanyUpdateInput (

    @param:JsonProperty(value = "companyId", required = true)
    @get:JsonProperty("companyId")
    val companyId: java.util.UUID,

    @param:JsonProperty(value = "idempotencyKey", required = true)
    @get:JsonProperty("idempotencyKey")
    val idempotencyKey: kotlin.String,

    @param:JsonProperty("employeeRange")
    @get:JsonProperty("employeeRange")
    val employeeRange: kotlin.String? = null,

    @param:JsonProperty("industry")
    @get:JsonProperty("industry")
    val industry: kotlin.String? = null,

    @param:JsonProperty("name")
    @get:JsonProperty("name")
    val name: kotlin.String? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("companyId", "idempotencyKey", if (employeeRange != null) "employeeRange" else null, if (industry != null) "industry" else null, if (name != null) "name" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("companyId", "idempotencyKey", "employeeRange", "industry", "name")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("companyId", "idempotencyKey")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (employeeRange == null) "employeeRange" else null, if (industry == null) "industry" else null, if (name == null) "name" else null)



}

