/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.ProductUsageTransaction

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param items 
 * @param limit 
 * @param offset 
 * @param total 
 */


data class ProductUsageHistoryOutput (

    @param:JsonProperty(value = "items", required = true)
    @get:JsonProperty("items")
    val items: kotlin.collections.List<ProductUsageTransaction>,

    @param:JsonProperty(value = "limit", required = true)
    @get:JsonProperty("limit")
    val limit: kotlin.Int,

    @param:JsonProperty(value = "offset", required = true)
    @get:JsonProperty("offset")
    val offset: kotlin.Int,

    @param:JsonProperty(value = "total", required = true)
    @get:JsonProperty("total")
    val total: kotlin.Int,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("items", "limit", "offset", "total"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("items", "limit", "offset", "total")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("items", "limit", "offset", "total")
    override fun reaconNullFields(): Set<String> = setOfNotNull()



}

