/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param assigned 
 * @param leadId 
 * @param tagId 
 */


data class ProductLeadTagAssignOutput (

    @param:JsonProperty(value = "assigned", required = true)
    @get:JsonProperty("assigned")
    val assigned: kotlin.Boolean,

    @param:JsonProperty(value = "leadId", required = true)
    @get:JsonProperty("leadId")
    val leadId: java.util.UUID,

    @param:JsonProperty(value = "tagId", required = true)
    @get:JsonProperty("tagId")
    val tagId: java.util.UUID,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("assigned", "leadId", "tagId"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("assigned", "leadId", "tagId")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("assigned", "leadId", "tagId")
    override fun reaconNullFields(): Set<String> = setOfNotNull()



}

