/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.ProductRecipient

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param added 
 * @param items 
 */


data class ProductSequenceRecipientAddOutput (

    @param:JsonProperty(value = "added", required = true)
    @get:JsonProperty("added")
    val added: kotlin.Int,

    @param:JsonProperty(value = "items", required = true)
    @get:JsonProperty("items")
    val items: kotlin.collections.List<ProductRecipient>,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("added", "items"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("added", "items")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("added", "items")
    override fun reaconNullFields(): Set<String> = setOfNotNull()



}

