/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param email 
 * @param idempotencyKey 
 * @param attributes Attribute names must be at most 100 characters. The server enforces this constraint.
 * @param company 
 * @param firstName 
 * @param lastName 
 * @param position 
 */


data class ProductLeadCreateInput (

    @param:JsonProperty(value = "email", required = true)
    @get:JsonProperty("email")
    val email: kotlin.String,

    @param:JsonProperty(value = "idempotencyKey", required = true)
    @get:JsonProperty("idempotencyKey")
    val idempotencyKey: kotlin.String,

    /* Attribute names must be at most 100 characters. The server enforces this constraint. */
    @param:JsonProperty("attributes")
    @get:JsonProperty("attributes")
    val attributes: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @param:JsonProperty("company")
    @get:JsonProperty("company")
    val company: kotlin.String? = null,

    @param:JsonProperty("firstName")
    @get:JsonProperty("firstName")
    val firstName: kotlin.String? = null,

    @param:JsonProperty("lastName")
    @get:JsonProperty("lastName")
    val lastName: kotlin.String? = null,

    @param:JsonProperty("position")
    @get:JsonProperty("position")
    val position: kotlin.String? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("email", "idempotencyKey", if (attributes != null) "attributes" else null, if (company != null) "company" else null, if (firstName != null) "firstName" else null, if (lastName != null) "lastName" else null, if (position != null) "position" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("email", "idempotencyKey", "attributes", "company", "firstName", "lastName", "position")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("email", "idempotencyKey")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (attributes == null) "attributes" else null, if (company == null) "company" else null, if (firstName == null) "firstName" else null, if (lastName == null) "lastName" else null, if (position == null) "position" else null)



}

