/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param amount 
 * @param description 
 * @param id 
 * @param occurredAt 
 * @param type 
 */


data class ProductUsageTransaction (

    @param:JsonProperty(value = "amount", required = true)
    @get:JsonProperty("amount")
    val amount: kotlin.Int,

    @param:JsonProperty(value = "description", required = true)
    @get:JsonProperty("description")
    val description: kotlin.String?,

    @param:JsonProperty(value = "id", required = true)
    @get:JsonProperty("id")
    val id: java.util.UUID,

    @param:JsonProperty(value = "occurredAt", required = true)
    @get:JsonProperty("occurredAt")
    val occurredAt: kotlin.String,

    @param:JsonProperty(value = "type", required = true)
    @get:JsonProperty("type")
    val type: kotlin.String,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("amount", "description", "id", "occurredAt", "type"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("amount", "description", "id", "occurredAt", "type")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("amount", "description", "id", "occurredAt", "type")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (description == null) "description" else null)



}

