/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.ProductSequenceStartOutput

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonValue

/**
 * 
 *
 * @param executionId 
 * @param output 
 * @param replay 
 * @param tool 
 */


data class ProductSequenceStartExecution (

    @param:JsonProperty(value = "executionId", required = true)
    @get:JsonProperty("executionId")
    val executionId: java.util.UUID,

    @param:JsonProperty(value = "output", required = true)
    @get:JsonProperty("output")
    val output: ProductSequenceStartOutput,

    @param:JsonProperty(value = "replay", required = true)
    @get:JsonProperty("replay")
    val replay: kotlin.Boolean,

    @param:JsonProperty(value = "tool", required = true)
    @get:JsonProperty("tool")
    val tool: ProductSequenceStartExecution.Tool,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("executionId", "output", "replay", "tool"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("executionId", "output", "replay", "tool")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("executionId", "output", "replay", "tool")
    override fun reaconNullFields(): Set<String> = setOfNotNull()


    /**
     * 
     *
     * Values: SEQUENCE_START
     */
    enum class Tool(@get:JsonValue val value: kotlin.String) {
        @JsonProperty(value = "sequence_start") SEQUENCE_START("sequence_start");
    }

}

