/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param added 
 * @param companyId 
 * @param listId 
 */


data class ProductCompanyListAddOutput (

    @param:JsonProperty(value = "added", required = true)
    @get:JsonProperty("added")
    val added: kotlin.Boolean,

    @param:JsonProperty(value = "companyId", required = true)
    @get:JsonProperty("companyId")
    val companyId: java.util.UUID,

    @param:JsonProperty(value = "listId", required = true)
    @get:JsonProperty("listId")
    val listId: java.util.UUID,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("added", "companyId", "listId"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("added", "companyId", "listId")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("added", "companyId", "listId")
    override fun reaconNullFields(): Set<String> = setOfNotNull()



}

