/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param email 
 * @param idempotencyKey 
 * @param sequenceId 
 * @param leadId 
 */


data class ProductSequenceRecipientAddInput (

    @param:JsonProperty(value = "email", required = true)
    @get:JsonProperty("email")
    val email: kotlin.String,

    @param:JsonProperty(value = "idempotencyKey", required = true)
    @get:JsonProperty("idempotencyKey")
    val idempotencyKey: kotlin.String,

    @param:JsonProperty(value = "sequenceId", required = true)
    @get:JsonProperty("sequenceId")
    val sequenceId: java.util.UUID,

    @param:JsonProperty("leadId")
    @get:JsonProperty("leadId")
    val leadId: java.util.UUID? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("email", "idempotencyKey", "sequenceId", if (leadId != null) "leadId" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("email", "idempotencyKey", "sequenceId", "leadId")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("email", "idempotencyKey", "sequenceId")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (leadId == null) "leadId" else null)



}

