/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param confidence 
 * @param email 
 * @param firstName 
 * @param id 
 * @param lastName 
 * @param linkedin 
 * @param location 
 * @param phone 
 * @param position 
 * @param verificationStatus 
 */


data class ProductPerson (

    @param:JsonProperty(value = "confidence", required = true)
    @get:JsonProperty("confidence")
    val confidence: java.math.BigDecimal?,

    @param:JsonProperty(value = "email", required = true)
    @get:JsonProperty("email")
    val email: kotlin.String,

    @param:JsonProperty(value = "firstName", required = true)
    @get:JsonProperty("firstName")
    val firstName: kotlin.String?,

    @param:JsonProperty(value = "id", required = true)
    @get:JsonProperty("id")
    val id: java.util.UUID,

    @param:JsonProperty(value = "lastName", required = true)
    @get:JsonProperty("lastName")
    val lastName: kotlin.String?,

    @param:JsonProperty(value = "linkedin", required = true)
    @get:JsonProperty("linkedin")
    val linkedin: kotlin.String?,

    @param:JsonProperty(value = "location", required = true)
    @get:JsonProperty("location")
    val location: kotlin.String?,

    @param:JsonProperty(value = "phone", required = true)
    @get:JsonProperty("phone")
    val phone: kotlin.String?,

    @param:JsonProperty(value = "position", required = true)
    @get:JsonProperty("position")
    val position: kotlin.String?,

    @param:JsonProperty(value = "verificationStatus", required = true)
    @get:JsonProperty("verificationStatus")
    val verificationStatus: kotlin.String?,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("confidence", "email", "firstName", "id", "lastName", "linkedin", "location", "phone", "position", "verificationStatus"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("confidence", "email", "firstName", "id", "lastName", "linkedin", "location", "phone", "position", "verificationStatus")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("confidence", "email", "firstName", "id", "lastName", "linkedin", "location", "phone", "position", "verificationStatus")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (confidence == null) "confidence" else null, if (firstName == null) "firstName" else null, if (lastName == null) "lastName" else null, if (linkedin == null) "linkedin" else null, if (location == null) "location" else null, if (phone == null) "phone" else null, if (position == null) "position" else null, if (verificationStatus == null) "verificationStatus" else null)



}

