/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param creditsAvailable 
 * @param creditsUsed 
 * @param nextExpiration 
 * @param requests 
 */


data class ProductUsageOutput (

    @param:JsonProperty(value = "creditsAvailable", required = true)
    @get:JsonProperty("creditsAvailable")
    val creditsAvailable: kotlin.Int,

    @param:JsonProperty(value = "creditsUsed", required = true)
    @get:JsonProperty("creditsUsed")
    val creditsUsed: kotlin.Int,

    @param:JsonProperty(value = "nextExpiration", required = true)
    @get:JsonProperty("nextExpiration")
    val nextExpiration: kotlin.String?,

    @param:JsonProperty(value = "requests", required = true)
    @get:JsonProperty("requests")
    val requests: kotlin.Int,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("creditsAvailable", "creditsUsed", "nextExpiration", "requests"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("creditsAvailable", "creditsUsed", "nextExpiration", "requests")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("creditsAvailable", "creditsUsed", "nextExpiration", "requests")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (nextExpiration == null) "nextExpiration" else null)



}

