/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.ProductCompaniesListInput
import io.reacon.sdk.kotlin.models.ProductCompanyDeleteInput
import io.reacon.sdk.kotlin.models.ProductCompanyListAddInput
import io.reacon.sdk.kotlin.models.ProductCompanyTrackInput
import io.reacon.sdk.kotlin.models.ProductCompanyUpdateInput
import io.reacon.sdk.kotlin.models.ProductConnectedAppPushInput
import io.reacon.sdk.kotlin.models.ProductCustomAttributeCreateInput
import io.reacon.sdk.kotlin.models.ProductDiscoverCompaniesInput
import io.reacon.sdk.kotlin.models.ProductDiscoverPeopleInput
import io.reacon.sdk.kotlin.models.ProductDomainFinderInput
import io.reacon.sdk.kotlin.models.ProductEmailCountInput
import io.reacon.sdk.kotlin.models.ProductLeadBulkDeleteInput
import io.reacon.sdk.kotlin.models.ProductLeadCreateInput
import io.reacon.sdk.kotlin.models.ProductLeadDeleteInput
import io.reacon.sdk.kotlin.models.ProductLeadGetInput
import io.reacon.sdk.kotlin.models.ProductLeadListAddLeadInput
import io.reacon.sdk.kotlin.models.ProductLeadListDeleteInput
import io.reacon.sdk.kotlin.models.ProductLeadListUpdateInput
import io.reacon.sdk.kotlin.models.ProductLeadTagAssignInput
import io.reacon.sdk.kotlin.models.ProductLeadTagCreateInput
import io.reacon.sdk.kotlin.models.ProductLeadUpdateInput
import io.reacon.sdk.kotlin.models.ProductLeadsListInput
import io.reacon.sdk.kotlin.models.ProductPersonEnrichInput
import io.reacon.sdk.kotlin.models.ProductSequenceRecipientAddInput
import io.reacon.sdk.kotlin.models.ProductSequenceRecipientCancelInput
import io.reacon.sdk.kotlin.models.ProductSequenceRecipientsAddInput
import io.reacon.sdk.kotlin.models.ProductSequenceRecipientsAddInputRecipientsInner
import io.reacon.sdk.kotlin.models.ProductSequenceRecipientsListInput
import io.reacon.sdk.kotlin.models.ProductSequenceStartInput

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Use the input model matching the tool path parameter. Equivalent input shapes appear once in this anyOf union; the tool catalog retains every named model.
 *
 * @param domain The server applies trim, toLowerCase before validating {\"type\":\"string\",\"pattern\":\"^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\\\\.)+[a-z]{2,63}$\"}.
 * @param company 
 * @param email 
 * @param listId 
 * @param leadId 
 * @param idempotencyKey 
 * @param leadIds 
 * @param name 
 * @param tagId 
 * @param key 
 * @param companyId 
 * @param sequenceId 
 * @param recipients 
 * @param recipientId 
 * @param connectionId 
 * @param industry 
 * @param limit 
 * @param location 
 * @param query 
 * @param jobTitle 
 * @param offset 
 * @param attributes Attribute names must be at most 100 characters. The server enforces this constraint.
 * @param firstName 
 * @param lastName 
 * @param position 
 * @param employeeRange 
 */


data class ProductToolRequestInput (

    /* The server applies trim, toLowerCase before validating {\"type\":\"string\",\"pattern\":\"^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\\\\.)+[a-z]{2,63}$\"}. */
    @param:JsonProperty(value = "domain", required = true)
    @get:JsonProperty("domain")
    val domain: kotlin.String,

    @param:JsonProperty(value = "company", required = true)
    @get:JsonProperty("company")
    val company: kotlin.String,

    @param:JsonProperty(value = "email", required = true)
    @get:JsonProperty("email")
    val email: kotlin.String,

    @param:JsonProperty(value = "listId", required = true)
    @get:JsonProperty("listId")
    val listId: java.util.UUID,

    @param:JsonProperty(value = "leadId", required = true)
    @get:JsonProperty("leadId")
    val leadId: java.util.UUID,

    @param:JsonProperty(value = "idempotencyKey", required = true)
    @get:JsonProperty("idempotencyKey")
    val idempotencyKey: kotlin.String,

    @param:JsonProperty(value = "leadIds", required = true)
    @get:JsonProperty("leadIds")
    val leadIds: kotlin.collections.List<java.util.UUID>,

    @param:JsonProperty(value = "name", required = true)
    @get:JsonProperty("name")
    val name: kotlin.String,

    @param:JsonProperty(value = "tagId", required = true)
    @get:JsonProperty("tagId")
    val tagId: java.util.UUID,

    @param:JsonProperty(value = "key", required = true)
    @get:JsonProperty("key")
    val key: kotlin.String,

    @param:JsonProperty(value = "companyId", required = true)
    @get:JsonProperty("companyId")
    val companyId: java.util.UUID,

    @param:JsonProperty(value = "sequenceId", required = true)
    @get:JsonProperty("sequenceId")
    val sequenceId: java.util.UUID,

    @param:JsonProperty(value = "recipients", required = true)
    @get:JsonProperty("recipients")
    val recipients: kotlin.collections.List<ProductSequenceRecipientsAddInputRecipientsInner>,

    @param:JsonProperty(value = "recipientId", required = true)
    @get:JsonProperty("recipientId")
    val recipientId: java.util.UUID,

    @param:JsonProperty(value = "connectionId", required = true)
    @get:JsonProperty("connectionId")
    val connectionId: java.util.UUID,

    @param:JsonProperty("industry")
    @get:JsonProperty("industry")
    val industry: kotlin.String? = null,

    @param:JsonProperty("limit")
    @get:JsonProperty("limit")
    val limit: kotlin.Int? = null,

    @param:JsonProperty("location")
    @get:JsonProperty("location")
    val location: kotlin.String? = null,

    @param:JsonProperty("query")
    @get:JsonProperty("query")
    val query: kotlin.String? = null,

    @param:JsonProperty("jobTitle")
    @get:JsonProperty("jobTitle")
    val jobTitle: kotlin.String? = null,

    @param:JsonProperty("offset")
    @get:JsonProperty("offset")
    val offset: kotlin.Int? = null,

    /* Attribute names must be at most 100 characters. The server enforces this constraint. */
    @param:JsonProperty("attributes")
    @get:JsonProperty("attributes")
    val attributes: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @param:JsonProperty("firstName")
    @get:JsonProperty("firstName")
    val firstName: kotlin.String? = null,

    @param:JsonProperty("lastName")
    @get:JsonProperty("lastName")
    val lastName: kotlin.String? = null,

    @param:JsonProperty("position")
    @get:JsonProperty("position")
    val position: kotlin.String? = null,

    @param:JsonProperty("employeeRange")
    @get:JsonProperty("employeeRange")
    val employeeRange: kotlin.String? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("domain", "company", "email", "listId", "leadId", "idempotencyKey", "leadIds", "name", "tagId", "key", "companyId", "sequenceId", "recipients", "recipientId", "connectionId", if (industry != null) "industry" else null, if (limit != null) "limit" else null, if (location != null) "location" else null, if (query != null) "query" else null, if (jobTitle != null) "jobTitle" else null, if (offset != null) "offset" else null, if (attributes != null) "attributes" else null, if (firstName != null) "firstName" else null, if (lastName != null) "lastName" else null, if (position != null) "position" else null, if (employeeRange != null) "employeeRange" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("domain", "company", "email", "listId", "leadId", "idempotencyKey", "leadIds", "name", "tagId", "key", "companyId", "sequenceId", "recipients", "recipientId", "connectionId", "industry", "limit", "location", "query", "jobTitle", "offset", "attributes", "firstName", "lastName", "position", "employeeRange")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("domain", "company", "email", "listId", "leadId", "idempotencyKey", "leadIds", "name", "tagId", "key", "companyId", "sequenceId", "recipients", "recipientId", "connectionId")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (industry == null) "industry" else null, if (limit == null) "limit" else null, if (location == null) "location" else null, if (query == null) "query" else null, if (jobTitle == null) "jobTitle" else null, if (offset == null) "offset" else null, if (attributes == null) "attributes" else null, if (firstName == null) "firstName" else null, if (lastName == null) "lastName" else null, if (position == null) "position" else null, if (employeeRange == null) "employeeRange" else null)



}

