/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param createdAt 
 * @param domain 
 * @param employeeRange 
 * @param id 
 * @param industry 
 * @param name 
 * @param numberOfEmployees 
 * @param website 
 */


data class ProductTrackedCompany (

    @param:JsonProperty(value = "createdAt", required = true)
    @get:JsonProperty("createdAt")
    val createdAt: kotlin.String,

    @param:JsonProperty(value = "domain", required = true)
    @get:JsonProperty("domain")
    val domain: kotlin.String?,

    @param:JsonProperty(value = "employeeRange", required = true)
    @get:JsonProperty("employeeRange")
    val employeeRange: kotlin.String?,

    @param:JsonProperty(value = "id", required = true)
    @get:JsonProperty("id")
    val id: java.util.UUID,

    @param:JsonProperty(value = "industry", required = true)
    @get:JsonProperty("industry")
    val industry: kotlin.String?,

    @param:JsonProperty(value = "name", required = true)
    @get:JsonProperty("name")
    val name: kotlin.String?,

    @param:JsonProperty(value = "numberOfEmployees", required = true)
    @get:JsonProperty("numberOfEmployees")
    val numberOfEmployees: kotlin.Int?,

    @param:JsonProperty(value = "website", required = true)
    @get:JsonProperty("website")
    val website: kotlin.String?,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("createdAt", "domain", "employeeRange", "id", "industry", "name", "numberOfEmployees", "website"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("createdAt", "domain", "employeeRange", "id", "industry", "name", "numberOfEmployees", "website")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("createdAt", "domain", "employeeRange", "id", "industry", "name", "numberOfEmployees", "website")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (domain == null) "domain" else null, if (employeeRange == null) "employeeRange" else null, if (industry == null) "industry" else null, if (name == null) "name" else null, if (numberOfEmployees == null) "numberOfEmployees" else null, if (website == null) "website" else null)



}

