/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param connectionId 
 * @param createdAt 
 * @param healthState 
 * @param label 
 * @param provider 
 * @param status 
 */


data class ProductConnectedApp (

    @param:JsonProperty(value = "connectionId", required = true)
    @get:JsonProperty("connectionId")
    val connectionId: java.util.UUID,

    @param:JsonProperty(value = "createdAt", required = true)
    @get:JsonProperty("createdAt")
    val createdAt: kotlin.String,

    @param:JsonProperty(value = "healthState", required = true)
    @get:JsonProperty("healthState")
    val healthState: kotlin.String,

    @param:JsonProperty(value = "label", required = true)
    @get:JsonProperty("label")
    val label: kotlin.String,

    @param:JsonProperty(value = "provider", required = true)
    @get:JsonProperty("provider")
    val provider: kotlin.String,

    @param:JsonProperty(value = "status", required = true)
    @get:JsonProperty("status")
    val status: kotlin.String,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("connectionId", "createdAt", "healthState", "label", "provider", "status"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("connectionId", "createdAt", "healthState", "label", "provider", "status")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("connectionId", "createdAt", "healthState", "label", "provider", "status")
    override fun reaconNullFields(): Set<String> = setOfNotNull()



}

