/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param emails 
 * @param mentions 
 * @param version 
 * @param apiProtocolVersion Wire protocol major version, independent of SDK and actions-package versions.
 */


data class PublicStats (

    @param:JsonProperty(value = "emails", required = true)
    @get:JsonProperty("emails")
    val emails: kotlin.Int,

    @param:JsonProperty(value = "mentions", required = true)
    @get:JsonProperty("mentions")
    val mentions: kotlin.Int,

    @param:JsonProperty(value = "version", required = true)
    @get:JsonProperty("version")
    val version: kotlin.String,

    /* Wire protocol major version, independent of SDK and actions-package versions. */
    @param:JsonProperty("apiProtocolVersion")
    @get:JsonProperty("apiProtocolVersion")
    val apiProtocolVersion: kotlin.Int? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("emails", "mentions", "version", if (apiProtocolVersion != null) "apiProtocolVersion" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("emails", "mentions", "version", "apiProtocolVersion")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("emails", "mentions", "version")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (apiProtocolVersion == null) "apiProtocolVersion" else null)



}

