/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.QueuedIntegrationJobStreamPosition

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param attempt 
 * @param cancelRequestedAt 
 * @param cancelRequestedByUserId 
 * @param canonicalEventId 
 * @param connectionId 
 * @param counters 
 * @param createdAt 
 * @param createdByUserId 
 * @param errorCode 
 * @param errorMessageRedacted 
 * @param finishedAt 
 * @param id 
 * @param idempotencyKey 
 * @param inputRef 
 * @param jobType Known values: crm_export, crm_delete, crm_activity, sheet_preview, sheet_writeback, notification_delivery, form_ingestion. Clients preserve future values.
 * @param leaseExpiresAt 
 * @param leaseOwner 
 * @param maxAttempts 
 * @param nextAttemptAt 
 * @param resultRef 
 * @param startedAt 
 * @param status Known values: pending, running, succeeded, failed, cancelled. Clients preserve future values.
 * @param streamPosition 
 * @param subjectId 
 * @param subjectType Known values: lead, sequence. Clients preserve future values.
 * @param teamId 
 * @param updatedAt 
 */


data class QueuedIntegrationJob (

    @param:JsonProperty(value = "attempt", required = true)
    @get:JsonProperty("attempt")
    val attempt: kotlin.Int,

    @param:JsonProperty(value = "cancel_requested_at", required = true)
    @get:JsonProperty("cancel_requested_at")
    val cancelRequestedAt: kotlin.String?,

    @param:JsonProperty(value = "cancel_requested_by_user_id", required = true)
    @get:JsonProperty("cancel_requested_by_user_id")
    val cancelRequestedByUserId: kotlin.String?,

    @param:JsonProperty(value = "canonical_event_id", required = true)
    @get:JsonProperty("canonical_event_id")
    val canonicalEventId: kotlin.String?,

    @param:JsonProperty(value = "connection_id", required = true)
    @get:JsonProperty("connection_id")
    val connectionId: kotlin.String,

    @param:JsonProperty(value = "counters", required = true)
    @get:JsonProperty("counters")
    val counters: kotlin.collections.Map<kotlin.String, kotlin.Any>,

    @param:JsonProperty(value = "created_at", required = true)
    @get:JsonProperty("created_at")
    val createdAt: kotlin.String,

    @param:JsonProperty(value = "created_by_user_id", required = true)
    @get:JsonProperty("created_by_user_id")
    val createdByUserId: kotlin.String?,

    @param:JsonProperty(value = "error_code", required = true)
    @get:JsonProperty("error_code")
    val errorCode: kotlin.String?,

    @param:JsonProperty(value = "error_message_redacted", required = true)
    @get:JsonProperty("error_message_redacted")
    val errorMessageRedacted: kotlin.String?,

    @param:JsonProperty(value = "finished_at", required = true)
    @get:JsonProperty("finished_at")
    val finishedAt: kotlin.String?,

    @param:JsonProperty(value = "id", required = true)
    @get:JsonProperty("id")
    val id: kotlin.String,

    @param:JsonProperty(value = "idempotency_key", required = true)
    @get:JsonProperty("idempotency_key")
    val idempotencyKey: kotlin.String,

    @param:JsonProperty(value = "input_ref", required = true)
    @get:JsonProperty("input_ref")
    val inputRef: kotlin.collections.Map<kotlin.String, kotlin.Any>,

    /* Known values: crm_export, crm_delete, crm_activity, sheet_preview, sheet_writeback, notification_delivery, form_ingestion. Clients preserve future values. */
    @param:JsonProperty(value = "job_type", required = true)
    @get:JsonProperty("job_type")
    val jobType: kotlin.String,

    @param:JsonProperty(value = "lease_expires_at", required = true)
    @get:JsonProperty("lease_expires_at")
    val leaseExpiresAt: kotlin.String?,

    @param:JsonProperty(value = "lease_owner", required = true)
    @get:JsonProperty("lease_owner")
    val leaseOwner: kotlin.String?,

    @param:JsonProperty(value = "max_attempts", required = true)
    @get:JsonProperty("max_attempts")
    val maxAttempts: kotlin.Int,

    @param:JsonProperty(value = "next_attempt_at", required = true)
    @get:JsonProperty("next_attempt_at")
    val nextAttemptAt: kotlin.String,

    @param:JsonProperty(value = "result_ref", required = true)
    @get:JsonProperty("result_ref")
    val resultRef: kotlin.collections.Map<kotlin.String, kotlin.Any>?,

    @param:JsonProperty(value = "started_at", required = true)
    @get:JsonProperty("started_at")
    val startedAt: kotlin.String?,

    /* Known values: pending, running, succeeded, failed, cancelled. Clients preserve future values. */
    @param:JsonProperty(value = "status", required = true)
    @get:JsonProperty("status")
    val status: kotlin.String,

    @param:JsonProperty(value = "stream_position", required = true)
    @get:JsonProperty("stream_position")
    val streamPosition: QueuedIntegrationJobStreamPosition,

    @param:JsonProperty(value = "subject_id", required = true)
    @get:JsonProperty("subject_id")
    val subjectId: kotlin.String?,

    /* Known values: lead, sequence. Clients preserve future values. */
    @param:JsonProperty(value = "subject_type", required = true)
    @get:JsonProperty("subject_type")
    val subjectType: kotlin.String?,

    @param:JsonProperty(value = "team_id", required = true)
    @get:JsonProperty("team_id")
    val teamId: kotlin.String,

    @param:JsonProperty(value = "updated_at", required = true)
    @get:JsonProperty("updated_at")
    val updatedAt: kotlin.String,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("attempt", "cancel_requested_at", "cancel_requested_by_user_id", "canonical_event_id", "connection_id", "counters", "created_at", "created_by_user_id", "error_code", "error_message_redacted", "finished_at", "id", "idempotency_key", "input_ref", "job_type", "lease_expires_at", "lease_owner", "max_attempts", "next_attempt_at", "result_ref", "started_at", "status", "stream_position", "subject_id", "subject_type", "team_id", "updated_at"),
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    val additionalProperties: MutableMap<String, Any?> = mutableMapOf(),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("attempt", "cancel_requested_at", "cancel_requested_by_user_id", "canonical_event_id", "connection_id", "counters", "created_at", "created_by_user_id", "error_code", "error_message_redacted", "finished_at", "id", "idempotency_key", "input_ref", "job_type", "lease_expires_at", "lease_owner", "max_attempts", "next_attempt_at", "result_ref", "started_at", "status", "stream_position", "subject_id", "subject_type", "team_id", "updated_at")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("attempt", "cancel_requested_at", "cancel_requested_by_user_id", "canonical_event_id", "connection_id", "counters", "created_at", "created_by_user_id", "error_code", "error_message_redacted", "finished_at", "id", "idempotency_key", "input_ref", "job_type", "lease_expires_at", "lease_owner", "max_attempts", "next_attempt_at", "result_ref", "started_at", "status", "stream_position", "subject_id", "subject_type", "team_id", "updated_at")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (cancelRequestedAt == null) "cancel_requested_at" else null, if (cancelRequestedByUserId == null) "cancel_requested_by_user_id" else null, if (canonicalEventId == null) "canonical_event_id" else null, if (createdByUserId == null) "created_by_user_id" else null, if (errorCode == null) "error_code" else null, if (errorMessageRedacted == null) "error_message_redacted" else null, if (finishedAt == null) "finished_at" else null, if (leaseExpiresAt == null) "lease_expires_at" else null, if (leaseOwner == null) "lease_owner" else null, if (resultRef == null) "result_ref" else null, if (startedAt == null) "started_at" else null, if (subjectId == null) "subject_id" else null, if (subjectType == null) "subject_type" else null)

    @com.fasterxml.jackson.annotation.JsonAnyGetter
    fun additionalProperties(): Map<String, Any?> = additionalProperties
    @com.fasterxml.jackson.annotation.JsonAnySetter
    fun putAdditionalProperty(key: String, value: Any?) {
        require(key !in reaconKnownFields) { "Declared property cannot be overridden as an additional property" }
        additionalProperties[key] = value
    }



}

