/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.SheetWorkflow
import io.reacon.sdk.kotlin.models.SheetWorkflowDeleted
import io.reacon.sdk.kotlin.models.SheetWorkflowResponse

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param workflow 
 * @param deleted 
 * @param workflowId 
 */


data class SheetWorkflowStateResponse (

    @param:JsonProperty(value = "workflow", required = true)
    @get:JsonProperty("workflow")
    val workflow: SheetWorkflow,

    @param:JsonProperty(value = "deleted", required = true)
    @get:JsonProperty("deleted")
    val deleted: kotlin.Boolean,

    @param:JsonProperty(value = "workflowId", required = true)
    @get:JsonProperty("workflowId")
    val workflowId: kotlin.String,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("workflow", "deleted", "workflowId"),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("workflow", "deleted", "workflowId")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("workflow", "deleted", "workflowId")
    override fun reaconNullFields(): Set<String> = setOfNotNull()



}

