/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param authorizationServer 
 * @param resourceUrl 
 * @param returnPath 
 */


data class StartIntegrationOAuthRequest (

    @param:JsonProperty("authorizationServer")
    @get:JsonProperty("authorizationServer")
    val authorizationServer: kotlin.String? = null,

    @param:JsonProperty("resourceUrl")
    @get:JsonProperty("resourceUrl")
    val resourceUrl: kotlin.String? = null,

    @param:JsonProperty("returnPath")
    @get:JsonProperty("returnPath")
    val returnPath: kotlin.String? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull(if (authorizationServer != null) "authorizationServer" else null, if (resourceUrl != null) "resourceUrl" else null, if (returnPath != null) "returnPath" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("authorizationServer", "resourceUrl", "returnPath")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf()
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (authorizationServer == null) "authorizationServer" else null, if (resourceUrl == null) "resourceUrl" else null, if (returnPath == null) "returnPath" else null)



}

