/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models

import io.reacon.sdk.kotlin.models.CompanyListResultsInnerAddressesInner
import io.reacon.sdk.kotlin.models.UpdateLeadRequestCompany
import io.reacon.sdk.kotlin.models.UpdateLeadRequestPerson

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param company 
 * @param companyAddresses 
 * @param companyFoundedOn 
 * @param companyIndustry 
 * @param companyLinkedin 
 * @param companyLocation 
 * @param companyName 
 * @param companyNumberOfEmployees 
 * @param companyStock 
 * @param companyTwitter 
 * @param companyType 
 * @param companyWebsite 
 * @param person 
 * @param personFirstName 
 * @param personLastName 
 * @param personLeadLocation 
 * @param personLinkedin 
 * @param personPhoneNumber 
 * @param personPosition 
 * @param personTwitter 
 * @param tags 
 */


data class UpdateLeadRequest (

    @param:JsonProperty("company")
    @get:JsonProperty("company")
    val company: UpdateLeadRequestCompany? = null,

    @param:JsonProperty("company_addresses")
    @get:JsonProperty("company_addresses")
    val companyAddresses: kotlin.collections.List<CompanyListResultsInnerAddressesInner>? = null,

    @param:JsonProperty("company_founded_on")
    @get:JsonProperty("company_founded_on")
    val companyFoundedOn: kotlin.String? = null,

    @param:JsonProperty("company_industry")
    @get:JsonProperty("company_industry")
    val companyIndustry: kotlin.String? = null,

    @param:JsonProperty("company_linkedin")
    @get:JsonProperty("company_linkedin")
    val companyLinkedin: kotlin.String? = null,

    @param:JsonProperty("company_location")
    @get:JsonProperty("company_location")
    val companyLocation: kotlin.String? = null,

    @param:JsonProperty("company_name")
    @get:JsonProperty("company_name")
    val companyName: kotlin.String? = null,

    @param:JsonProperty("company_number_of_employees")
    @get:JsonProperty("company_number_of_employees")
    val companyNumberOfEmployees: kotlin.Int? = null,

    @param:JsonProperty("company_stock")
    @get:JsonProperty("company_stock")
    val companyStock: kotlin.String? = null,

    @param:JsonProperty("company_twitter")
    @get:JsonProperty("company_twitter")
    val companyTwitter: kotlin.String? = null,

    @param:JsonProperty("company_type")
    @get:JsonProperty("company_type")
    val companyType: kotlin.String? = null,

    @param:JsonProperty("company_website")
    @get:JsonProperty("company_website")
    val companyWebsite: kotlin.String? = null,

    @param:JsonProperty("person")
    @get:JsonProperty("person")
    val person: UpdateLeadRequestPerson? = null,

    @param:JsonProperty("person_first_name")
    @get:JsonProperty("person_first_name")
    val personFirstName: kotlin.String? = null,

    @param:JsonProperty("person_last_name")
    @get:JsonProperty("person_last_name")
    val personLastName: kotlin.String? = null,

    @param:JsonProperty("person_lead_location")
    @get:JsonProperty("person_lead_location")
    val personLeadLocation: kotlin.String? = null,

    @param:JsonProperty("person_linkedin")
    @get:JsonProperty("person_linkedin")
    val personLinkedin: kotlin.String? = null,

    @param:JsonProperty("person_phone_number")
    @get:JsonProperty("person_phone_number")
    val personPhoneNumber: kotlin.String? = null,

    @param:JsonProperty("person_position")
    @get:JsonProperty("person_position")
    val personPosition: kotlin.String? = null,

    @param:JsonProperty("person_twitter")
    @get:JsonProperty("person_twitter")
    val personTwitter: kotlin.String? = null,

    @param:JsonProperty("tags")
    @get:JsonProperty("tags")
    val tags: kotlin.collections.List<kotlin.String>? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull(if (company != null) "company" else null, if (companyAddresses != null) "company_addresses" else null, if (companyFoundedOn != null) "company_founded_on" else null, if (companyIndustry != null) "company_industry" else null, if (companyLinkedin != null) "company_linkedin" else null, if (companyLocation != null) "company_location" else null, if (companyName != null) "company_name" else null, if (companyNumberOfEmployees != null) "company_number_of_employees" else null, if (companyStock != null) "company_stock" else null, if (companyTwitter != null) "company_twitter" else null, if (companyType != null) "company_type" else null, if (companyWebsite != null) "company_website" else null, if (person != null) "person" else null, if (personFirstName != null) "person_first_name" else null, if (personLastName != null) "person_last_name" else null, if (personLeadLocation != null) "person_lead_location" else null, if (personLinkedin != null) "person_linkedin" else null, if (personPhoneNumber != null) "person_phone_number" else null, if (personPosition != null) "person_position" else null, if (personTwitter != null) "person_twitter" else null, if (tags != null) "tags" else null),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("company", "company_addresses", "company_founded_on", "company_industry", "company_linkedin", "company_location", "company_name", "company_number_of_employees", "company_stock", "company_twitter", "company_type", "company_website", "person", "person_first_name", "person_last_name", "person_lead_location", "person_linkedin", "person_phone_number", "person_position", "person_twitter", "tags")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf()
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (company == null) "company" else null, if (companyAddresses == null) "company_addresses" else null, if (companyFoundedOn == null) "company_founded_on" else null, if (companyIndustry == null) "company_industry" else null, if (companyLinkedin == null) "company_linkedin" else null, if (companyLocation == null) "company_location" else null, if (companyName == null) "company_name" else null, if (companyNumberOfEmployees == null) "company_number_of_employees" else null, if (companyStock == null) "company_stock" else null, if (companyTwitter == null) "company_twitter" else null, if (companyType == null) "company_type" else null, if (companyWebsite == null) "company_website" else null, if (person == null) "person" else null, if (personFirstName == null) "person_first_name" else null, if (personLastName == null) "person_last_name" else null, if (personLeadLocation == null) "person_lead_location" else null, if (personLinkedin == null) "person_linkedin" else null, if (personPhoneNumber == null) "person_phone_number" else null, if (personPosition == null) "person_position" else null, if (personTwitter == null) "person_twitter" else null, if (tags == null) "tags" else null)



}

