/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param code 
 * @param error 
 * @param updatedAt 
 * @param remainingCredits 
 * @param status 
 */


data class VerificationStreamError (

    @param:JsonProperty(value = "code", required = true)
    @get:JsonProperty("code")
    val code: kotlin.String,

    @param:JsonProperty(value = "error", required = true)
    @get:JsonProperty("error")
    val error: kotlin.String,

    @param:JsonProperty(value = "updatedAt", required = true)
    @get:JsonProperty("updatedAt")
    val updatedAt: kotlin.String,

    @param:JsonProperty("remainingCredits")
    @get:JsonProperty("remainingCredits")
    val remainingCredits: java.math.BigDecimal? = null,

    @param:JsonProperty("status")
    @get:JsonProperty("status")
    val status: kotlin.Int? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("code", "error", "updatedAt", if (remainingCredits != null) "remainingCredits" else null, if (status != null) "status" else null),
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    val additionalProperties: MutableMap<String, Any?> = mutableMapOf(),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("code", "error", "updatedAt", "remainingCredits", "status")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("code", "error", "updatedAt")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (remainingCredits == null) "remainingCredits" else null, if (status == null) "status" else null)

    @com.fasterxml.jackson.annotation.JsonAnyGetter
    fun additionalProperties(): Map<String, Any?> = additionalProperties
    @com.fasterxml.jackson.annotation.JsonAnySetter
    fun putAdditionalProperty(key: String, value: Any?) {
        require(key !in reaconKnownFields) { "Declared property cannot be overridden as an additional property" }
        additionalProperties[key] = value
    }



}

