/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param requestId 
 * @param state Known values: queued, processing. Clients preserve future values.
 * @param updatedAt 
 * @param capabilityEpoch 
 * @param greylistAttempt 
 * @param invalidationReason 
 * @param mxFingerprint 
 * @param nextRetryAt 
 * @param preferredIp 
 * @param reputationGeneration 
 * @param requiredTier Known values: clean, dirty. Clients preserve future values.
 */


data class VerificationProgress (

    @param:JsonProperty(value = "requestId", required = true)
    @get:JsonProperty("requestId")
    val requestId: kotlin.String,

    /* Known values: queued, processing. Clients preserve future values. */
    @param:JsonProperty(value = "state", required = true)
    @get:JsonProperty("state")
    val state: kotlin.String,

    @param:JsonProperty(value = "updatedAt", required = true)
    @get:JsonProperty("updatedAt")
    val updatedAt: kotlin.String,

    @param:JsonProperty("capabilityEpoch")
    @get:JsonProperty("capabilityEpoch")
    val capabilityEpoch: kotlin.Int? = null,

    @param:JsonProperty("greylistAttempt")
    @get:JsonProperty("greylistAttempt")
    val greylistAttempt: kotlin.Int? = null,

    @param:JsonProperty("invalidationReason")
    @get:JsonProperty("invalidationReason")
    val invalidationReason: kotlin.String? = null,

    @param:JsonProperty("mxFingerprint")
    @get:JsonProperty("mxFingerprint")
    val mxFingerprint: kotlin.String? = null,

    @param:JsonProperty("nextRetryAt")
    @get:JsonProperty("nextRetryAt")
    val nextRetryAt: kotlin.String? = null,

    @param:JsonProperty("preferredIp")
    @get:JsonProperty("preferredIp")
    val preferredIp: kotlin.String? = null,

    @param:JsonProperty("reputationGeneration")
    @get:JsonProperty("reputationGeneration")
    val reputationGeneration: kotlin.Int? = null,

    /* Known values: clean, dirty. Clients preserve future values. */
    @param:JsonProperty("requiredTier")
    @get:JsonProperty("requiredTier")
    val requiredTier: kotlin.String? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("requestId", "state", "updatedAt", if (capabilityEpoch != null) "capabilityEpoch" else null, if (greylistAttempt != null) "greylistAttempt" else null, if (invalidationReason != null) "invalidationReason" else null, if (mxFingerprint != null) "mxFingerprint" else null, if (nextRetryAt != null) "nextRetryAt" else null, if (preferredIp != null) "preferredIp" else null, if (reputationGeneration != null) "reputationGeneration" else null, if (requiredTier != null) "requiredTier" else null),
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    val additionalProperties: MutableMap<String, Any?> = mutableMapOf(),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("requestId", "state", "updatedAt", "capabilityEpoch", "greylistAttempt", "invalidationReason", "mxFingerprint", "nextRetryAt", "preferredIp", "reputationGeneration", "requiredTier")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("requestId", "state", "updatedAt")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (capabilityEpoch == null) "capabilityEpoch" else null, if (greylistAttempt == null) "greylistAttempt" else null, if (invalidationReason == null) "invalidationReason" else null, if (mxFingerprint == null) "mxFingerprint" else null, if (nextRetryAt == null) "nextRetryAt" else null, if (preferredIp == null) "preferredIp" else null, if (reputationGeneration == null) "reputationGeneration" else null, if (requiredTier == null) "requiredTier" else null)

    @com.fasterxml.jackson.annotation.JsonAnyGetter
    fun additionalProperties(): Map<String, Any?> = additionalProperties
    @com.fasterxml.jackson.annotation.JsonAnySetter
    fun putAdditionalProperty(key: String, value: Any?) {
        require(key !in reaconKnownFields) { "Declared property cannot be overridden as an additional property" }
        additionalProperties[key] = value
    }



}

