/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.reacon.sdk.kotlin.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param acceptsAll 
 * @param catchAll 
 * @param disposable 
 * @param status Known values: deliverable, risky, undeliverable. Clients preserve future values.
 * @param cached 
 * @param cachePolicy Known values: live, 1d, 1w, 1m. Clients preserve future values.
 * @param mxHost 
 * @param resolvedIp 
 * @param score 
 */


data class VerificationResult (

    @param:JsonProperty(value = "acceptsAll", required = true)
    @get:JsonProperty("acceptsAll")
    val acceptsAll: kotlin.Boolean?,

    @param:JsonProperty(value = "catchAll", required = true)
    @get:JsonProperty("catchAll")
    val catchAll: kotlin.Boolean,

    @param:JsonProperty(value = "disposable", required = true)
    @get:JsonProperty("disposable")
    val disposable: kotlin.Boolean,

    /* Known values: deliverable, risky, undeliverable. Clients preserve future values. */
    @param:JsonProperty(value = "status", required = true)
    @get:JsonProperty("status")
    val status: kotlin.String,

    @param:JsonProperty("cached")
    @get:JsonProperty("cached")
    val cached: kotlin.Boolean? = null,

    /* Known values: live, 1d, 1w, 1m. Clients preserve future values. */
    @param:JsonProperty("cachePolicy")
    @get:JsonProperty("cachePolicy")
    val cachePolicy: kotlin.String? = null,

    @param:JsonProperty("mxHost")
    @get:JsonProperty("mxHost")
    val mxHost: kotlin.String? = null,

    @param:JsonProperty("resolvedIp")
    @get:JsonProperty("resolvedIp")
    val resolvedIp: kotlin.String? = null,

    @param:JsonProperty("score")
    @get:JsonProperty("score")
    val score: java.math.BigDecimal? = null,

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override var reaconFieldPresence: Set<String> = setOfNotNull("acceptsAll", "catchAll", "disposable", "status", if (cached != null) "cached" else null, if (cachePolicy != null) "cachePolicy" else null, if (mxHost != null) "mxHost" else null, if (resolvedIp != null) "resolvedIp" else null, if (score != null) "score" else null),
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    val additionalProperties: MutableMap<String, Any?> = mutableMapOf(),
) : io.reacon.sdk.kotlin.infrastructure.FieldPresence {

    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconKnownFields: Set<String> get() = setOf("acceptsAll", "catchAll", "disposable", "status", "cached", "cachePolicy", "mxHost", "resolvedIp", "score")
    @get:com.fasterxml.jackson.annotation.JsonIgnore
    override val reaconRequiredFields: Set<String> get() = setOf("acceptsAll", "catchAll", "disposable", "status")
    override fun reaconNullFields(): Set<String> = setOfNotNull(if (acceptsAll == null) "acceptsAll" else null, if (cached == null) "cached" else null, if (cachePolicy == null) "cachePolicy" else null, if (mxHost == null) "mxHost" else null, if (resolvedIp == null) "resolvedIp" else null, if (score == null) "score" else null)

    @com.fasterxml.jackson.annotation.JsonAnyGetter
    fun additionalProperties(): Map<String, Any?> = additionalProperties
    @com.fasterxml.jackson.annotation.JsonAnySetter
    fun putAdditionalProperty(key: String, value: Any?) {
        require(key !in reaconKnownFields) { "Declared property cannot be overridden as an additional property" }
        additionalProperties[key] = value
    }



}

